### ISSUE TITLE
"ticks" style only show ticks on one side with mpl2.0b3

### ISSUE THREAD

**Issue by anntzer** [mwaskom/seaborn#1006]
Empty axes with "ticks" style (`sns.set(style="ticks"); plt.gca(); plt.show()`), mpl1.5.1:
![151](https://cloud.githubusercontent.com/assets/1322974/18289833/ead13662-7435-11e6-93aa-857f37261ebe.png)
mpl2.0b3:
![20b3](https://cloud.githubusercontent.com/assets/1322974/18289826/e78d2dc6-7435-11e6-9291-538d6dd520d2.png)

**Comment by mwaskom** [comment]
I haven't really been paying attention to what they have changed, can you try to figure it out? FWIW I greatly prefer the second plot so I'm not sure this is a problem!.

**Comment by mwaskom** [comment]
This is an intentional change in matplotlib: http://matplotlib.org/devdocs/users/dflt_style_changes.html#ticks

I think this is a very good change, and the only reason it wasn't the way the `ticks` style used to work in seaborn was that there wasn't any clean way to implement it.

Note that if you need exact backwards compatibility for some reason, matplotlib has introduced new rcParams that can be used to produce the old look.
