### ISSUE TITLE
Bug: Annotate Heatmap with string array fails

### ISSUE THREAD

**Issue by Khris777** [mwaskom/seaborn#1068]
I want to annotate my heatmap with strings so I can define the format of the annotations, however setting a string array as annotation fails:

	import numpy as np
	import seaborn as sns
	import string
	testArray = np.random.rand(10,10)
	charArray = np.random.choice(list(string.letters),size=(10,10))
	sns.heatmap(testArray,annot=charArray)

Error Message:

    ValueError: Unknown format code 'g' for object of type 'numpy.string_'

Edit: 
Seaborn version 0.7.1
Python version 2.7.12

**Comment by mwaskom** [comment]
You can't format letters with a floating point specification.

**Comment by Khris777** [comment]
Can you please be more specific about what I'm doing wrong?

**Comment by AllanLRH** [comment]
I think that Seaborn should just use the string array "as is" when provided with one. It allows for more fine grained control over the annotation without needing an more advanced interface.
An use case would be if annotation are only wanted at select coordinates, where which could be achieved by parsing an array with mostly empty strings, and a few strings representing an already numerical values for the relevant coordinates. I realize that Seaborn probably wont be able to (and IMHO shouldn't) format the annotations, but I think that's all right, since the user made an extra effort when providing the annotation data.
