### ISSUE TITLE
Recursion error on clustermap

### ISSUE THREAD

**Issue by amueller** [mwaskom/seaborn#1152]
![image](https://cloud.githubusercontent.com/assets/449558/24776065/5c4b0be8-1aed-11e7-9e5c-801b1dfb4370.png)
Full traceback here:
https://pastebin.com/NngZDJtp

The matrix is all binary entries.

I tried to use scipy directly to investigate but got this again: https://github.com/scipy/scipy/issues/7271

**Comment by mwaskom** [comment]
I can't reproduce this error on try.jupyter.org with random data (`X = np.random.rand(686, 6598) > .5`). I eventually get a plot (although it's not very informative because it's not possible resolve the lines of the dendrogram on my display). If your scipy version is different than what's on there (17.1) could be the cause. Note that seaborn will use fastcluster if it is installed.

**Comment by amueller** [comment]
```python
import numpy as np
import pandas as pd
import seaborn as sns

rng = np.random.RandomState(3)
X_ = (rng.uniform(size=(6597, 686)) < .02).astype(int)
sns.clustermap(pd.DataFrame(X_))
```
gives the recursion error but I could reproduce it in scipy.

**Comment by amueller** [comment]
Looks like an upstream issue so closing here.

**Comment by amueller** [comment]
Looks like an upstream issue so closing here.
