### ISSUE TITLE
conflict between hspace/wspace in gridspec_kws and calls to tight_layout()

### ISSUE THREAD

**Issue by azag0** [mwaskom/seaborn#1174]
I'd like to manually set `hspace` and/or `wspace` for FaceGrid by supplying them to `gridspec_kws`, but this currently conflicts with calls to `fig.tight_layout()` in `FacetGrid.__init__()` and in `FacetGrid._finalize_grid()`:

```python
import seaborn as sns
import pandas as pd
%matplotlib inline

sns.FacetGrid(
    data=pd.DataFrame({'x': list(range(10)), 'y': list(range(10)), 'z': 5*[0] + 5*[1]}),
    col='z',
    gridspec_kws={'wspace': .03}
).map(sns.plt.plot, 'x', 'y')
```

This results in `ValueError: max() arg is an empty sequence`. By commenting out the two calls to `tight_layout()`, I'm able to run this snippet.

Is this a bug? Or is it simply not supported? Any way how to do this without modifying Seaborn?

**Comment by azag0** [comment]
This maybe a problem in matpltotlib matplotlib/matplotlib#8578

**Comment by mwaskom** [comment]
I would imagine this is in the matplotlib layer as seaborn isn't doing anything with the gridspec kws other than passing them to the `plt.subplots` call. And I think every call to `tight_layout` inside `FacetGrid` calls the method on the Figure object (cf the matplotlib issue).

You should be able to work around this by adjusting the wspace post-hoc with `FacetGrid.fig.subplots_adjust`.

You could also try using a different backend, I'm not sure exactly where the issue is in matplotlib but lots of tight_layout bugs that I've seen are backend-specific.

**Comment by azag0** [comment]
Should have known about `FacetGrid.fig.subplots_adjust`. Thanks for the help.
