### ISSUE TITLE
Categorical plots can mix x-axis labels on figures with sharex

### ISSUE THREAD

**Issue by nfourcau** [mwaskom/seaborn#1306]
Here is a MWE of the bug (the bug is reproducible with any of the categorical plot function)

```
import seaborn as sns
import matplotlib.pyplot as plt

func=sns.swarmplot
dat1=[['a','b'],[0,1]]
dat2=[['a','b'],[2,3]]
#~ dat2=[['b','a'],[2,3]] # Usage of this line reverse labels of first panel without reversing data points !!!
fig=plt.figure()
ax1=fig.add_subplot(121)
func(*dat1,ax=ax1)
ax2=fig.add_subplot(122,sharex=ax1)
func(*dat2,ax=ax2)
plt.show()
```
When the commented line is uncommented, x-axis labels on ax1 are reversed compared to what they should be.

The problem comes from the combination of sharex and annotate_axes from class _CategoricalPlotter. Xtick labels are given after points are plotted in the order they come, thus if the label order for ax2 is not the same as for ax1, the sharex changes ax1 labels (giving wrong labels). 

Current workaround is to avoid any sharex (especially in Grid like FacetGrid where it is on by default) for categorical plot.

**Comment by mwaskom** [comment]
Yes, it is a well known issue. The problem is that matplotlib has no native support for "categorical" axes, and some features on the matplotlib that make sense for quantitative data 

The correct way to avoid the problem is to specify categorical orders, either by passing data with a pandas Categorical type, or by using the `order`/`hue_order` parameters. Fairly recently, because I realized that this was not obvious to people, I changed FacetGrid to fire  warning if it is used with a categorical plot and these parameters are not specified. However, I do not believe it's possible (or at least I don't know how) to reliably detect if an axis is shared at the matplotlib level, so it's not possible to implement that warning for the very low-level API that you're using.

**Comment by nfourcau** [comment]
Thank you for the answer, thinking about it I realized this was not a "real" bug but more an API problem (and a "categorical" axis in matplotlib would be a good solution). I showed this low level API above because I was tracking what was going wrong with my FacetGrid. I have now seen the warning but I still think it is easy to be flawed without noticing something is wrong. I wonder if it would not be better to change the "warning" into an "error"?

**Comment by mwaskom** [comment]
> I wonder if it would not be better to change the "warning" into an "error"?

No, because there are cases where it will work, e.g. if the dataframe is sorted properly.

Is there some reason you're using `FacetGrid` directly instead of `factorplot`? It exists to handle this bookkeeping for the user.

**Comment by nfourcau** [comment]
Indeed I should use factorplot. I will see if it matches all my current needs. Thank you.
