### ISSUE TITLE
Index Error: index -1 is out of bounds for index 0 and size 0

### ISSUE THREAD

**Issue by karanthpallavi** [mwaskom/seaborn#1416]
Hello,

My .csv has two columns and looks like this:

SemDist,RegularDist
0.7,1.0
0.3,2.0
2.0,3.0
10000,10000
0.3,2.0
3.4,2.0
0.1,1.0
3.1,4.0
0.1,1.0
10000,10000
0.1,1.0
0.1,1.0
0.1,1.0
1.8,2.0
1.8,2.0
4.5,3.0
0.5,3.0
0.3,2.0
0.5,3.0
0.3,2.0
0.3,2.0
0.3,2.0
0.3,2.0
0.3,2.0
0.3,2.0
0.3,2.0
10000,10000
10000,10000
10000,10000
10000,10000
10000,10000
0.7,1.0

My script is:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

new_names = ['SemDist','RegularDist']
df = pd.read_csv('./SemanticDistance.csv',names=new_names)
print(df.columns.values)
print(type(df.SemDist))
df.replace('..', np.nan, inplace=True)
sns.pairplot(df,hue='species', size=2.5);

Am new to seaborn,
Kindly help,
Unable to visualise data using any kind of plot.

Thanks in advance

**Comment by CRiddler** [comment]
Based on what you pasted, I'm not sure why you're getting a `IndexError`so my guess is that what you pasted isn't specifically related to the error you're getting. If you can paste in the full traceback, then I can be of some more help.

On a semi-related note, the name 'species' that you're specifying for the `hue` argument needs to be a column in the dataframe `df`. In the data that you pasted, you have no column named 'species', so this should be throwing a `KeyError`

**Comment by mwaskom** [comment]
I agree that @CRiddler that the error message doesn't seem likely to be produced by the code you provided and that your code will not work because you're specifying a hue variable that doesn't exist in the dataset. It looks like you've over-literally copied from the iris example.  You might want to take a step back and read through the [tutorial](http://seaborn.pydata.org/tutorial.html) to understand the different kind of functions in seaborn.

**Comment by vaughnkoch** [comment]
I had the same exception. 

In this function, if one your otherwise numeric columns has a single None in it, it will kill the entire column. If that repeats and results in having no columns, then seaborn will throw an exception because it needs data to survive.

### axisgrid.py
```

def _find_numeric_cols(self, data):
    """Find which variables in a DataFrame are numeric."""
    # This can't be the best way to do this, but  I do not
    # know what the best way might be, so this seems ok
    numeric_cols = []
    for col in data:
        try:
            data[col].astype(np.float)
            numeric_cols.append(col)
        except (ValueError, TypeError):
            pass
    return numeric_cols
```

which causes plt.subplots to return no axes, since there's no data in y_vars or x_vars:

```
fig, axes = plt.subplots(len(y_vars), len(x_vars),
                         figsize=figsize,
                         sharex="col", sharey="row",
                         squeeze=False)

self.fig = fig

self.axes = axes
self.data = data
```

The exception is caused by a negative index on self.axes, e.g.:
```
for ax, label in zip(self.axes[-1, :], self.x_vars):
```


I'm sure I can massage my data beforehand, but it would be great if this were more robust. Thanks for creating a great library, btw :)

**Comment by mwaskom** [comment]
Can you provide an example of a dataset that fails?

**Comment by CRiddler** [comment]
> In this function, if one your otherwise numeric columns has a single None in it, it will kill the entire column.

I'm not sure if I see what you're saying here, because when you use `.astype` on a series that has a None in it, then None becomes NaN if the column is convertible.

    >>> import pandas as pd
    >>> import numpy as np
    >>> s = pd.Series([1,2,3,4])
    >>> s.loc[4] = None #add in None after series creation because pd.Series will convert None to NaN
    >>> s
    0       1
    1       2
    2       3
    3       4
    4    None
    dtype: object
    >>> s.astype(np.float)
    0    1.0
    1    2.0
    2    3.0
    3    4.0
    4    NaN
    dtype: float64

The difference between `_find_numeric_cols` has over `DataFrame.select_dtypes` is that `_find_numeric_cols` will first try to convert a column to a numeric type before giving up. `.select_dtypes` will only get columns that are **currently** numeric.

Which actually brings up the question: Are we relying on plotting functions to implicitly cast inputs to numeric, and is this an appropriate thing to do?

**Comment by vaughnkoch** [comment]
Hi guys, I tried to get a repro dataset but it's slipperier than I expected. If I find it again, I'll post an example here. I did have all the columns as dtype=object, so that may have something to do with it.
