### ISSUE TITLE
Seaborn not being recognized, plots showing up as matplotlib

### ISSUE THREAD

**Issue by jmayerstone** [mwaskom/seaborn#1418]
I have no idea why, but on my computer, whenever I do a seaborn plot, it shows up as matplotlib. 
I tried uninstalling / reinstalling both seaborn and matplotlib, and nothing works. 

Has anyone else experienced this? 

![image](https://user-images.githubusercontent.com/2948702/39552285-6624f8ae-4e1d-11e8-9a48-c40371131755.png)

**Comment by jona-sassenhagen** [comment]
Looks like a perfectly fine seaboard plot? Maybe you want to `sns.set_style`?

**Comment by mwaskom** [comment]
There's no meaningful distinction between a "seaborn plot" and a "matplotlib plot". Seaborn functions are just interfaces for drawing matplotlib plots. What I think you mean is that the style of the plot has matplotlib defaults rather than [a seaborn style](http://seaborn.pydata.org/tutorial/aesthetics.html). To get the latter, you should call `sns.set()`. This used to happen on import but now must be called explicitly.

**Comment by jmayerstone** [comment]
thank you both! I had never had it look like matplotlib out of the box before, so I didn't realize that sns.set() had to be called explicitly now.
