### ISSUE TITLE
joinplot issue

### ISSUE THREAD

**Issue by Hamidreza3252** [mwaskom/seaborn#1420]
Hi,
I am getting a warning causing the contour plot does not work. Can you please help resolve this issue? Could it be that I have to downgrade my matplotlib library?

`my_data = np.array([[ 278.57142857,  278.57142857,  278.57142857,  278.57142857,
         278.57142857,  278.57142857,  278.57142857,  278.57142857,
         278.57142857,  278.57142857],
       [ 314.28571429,  314.28571429,  314.28571429,  314.28571429,
         314.28571429,  314.28571429,  314.28571429,  314.28571429,
         314.28571429,  314.28571429]])

sns.jointplot(my_data[0, :], my_data[1, :], stat_func=None, kind='kde')`

**C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py:1480: UserWarning: Warning: converting a masked element to nan.
  self.zmax = float(z.max())
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py:1481: UserWarning: Warning: converting a masked element to nan.
  self.zmin = float(z.min())**

**Comment by mwaskom** [comment]
The problem is that there is no variance in your data, which is causing scipy to be unable to choose a default bandwidth for the data. You can pass the bandwidth you want to use to the `bw` kwarg (that gets passed down to `seaborn.kdeplot`, but the more general issue is that representing a number of identical paired observations with a bivariate gaussian is probably not the best way to show your data!

**Comment by Hamidreza3252** [comment]
Thanks. It worked! Some portion of data I extracted from the whole set are correlated and I missed to glance through the data points.
