### ISSUE TITLE
[Feature Request] Asymmetric barplot error bars

### ISSUE THREAD

**Issue by StarvingMathematician** [mwaskom/seaborn#1449]
I just started using seaborn and am *loving* it so far (going from matplotlib to seaborn is like going from R's standard plotter to ggplot2), but I just ran into what, for me, is a frustrating limitation. As far as I can tell, there's no native support for adding asymmetric error bars to seaborn barplots. Much of the data that I work with comes from highly skewed distributions, so support for asymmetric error bars is essential.

[I found a partial workaround on stackoverflow](https://stackoverflow.com/a/45895947/2562771), but it's really clunky, and basically eliminates the benefits of using seaborn in the first place. Any chance support for asymmetric error bars will be added in the near future? Thanks!

**Comment by mwaskom** [comment]
I'm not sure I understand what you're asking because seaborn draws all error bars by computing confidence intervals from the data. So, if the bootstrap distribution is skewed, the error bar will be asymmetric.

There's not, in general, support for specifying the size of the error bars on the bar plot independently from the data, and that's not going to change.

**Comment by StarvingMathematician** [comment]
Oh, perfect! I was manually doing the bootstrap and computing the CI bounds myself, I didn't realize seaborn was smart enough to take care of that part. Thanks!
