### ISSUE TITLE
Feature request: Allow user to provide bootstrap values (e.g. from a column)

### ISSUE THREAD

**Issue by SynapticSage** [mwaskom/seaborn#1451]
Seaborn has a great design for error bars with SDs or bootstraps that seaborn calculates itself. But there currently seems to be a limit on options available to those of us that want to generate our bootstraps up front (perhaps because of a massive dataset), and then reuse those bootstraps to then try several plot variations. It seems like that's not an option right now **(someone please correct me if I'm wrong)**. 

The way I do this, and I imagine others, too, is to manually plot the CIs. But the framework looks already well-positioned to make that task easier. Perhaps a modification in the spirit of the code snippet below could with that task in a future version? 

... an example modification of the CI code to fit that purpose:

#### categorical.py
```
            # Get a confidence interval for this estimate
                if ci is not None:

                    if stat_data.size < 2:
                        confint.append([np.nan, np.nan])
                        continue
                    **if bootstrap_column and not ci == "sd": # if bootstrap column provided in upstream functions
                       estimate = esimtator(stat_data)
                       confint.append(utils.ci(self.data[bootstrap_column], ci))
                    elif ci == "sd":**

                        estimate = estimator(stat_data)
                        sd = np.std(stat_data)
                        confint.append((estimate - sd, estimate + sd))

                    else:

                        boots = bootstrap(stat_data, func=estimator,
                                          n_boot=n_boot,
                                          units=unit_data)
                        confint.append(utils.ci(boots, ci))
```

Also, no attempt is made in the above code to follow the squeaky clean structural conventions within the existing code base. I'm just trying to clarify what's being asked.

**Comment by mwaskom** [comment]
Sorry, but there's just no way to add this without very large and disruptive changes throughout the library.

(I also think your proposed change doesn't make sense because how could a tidy dataframe have both observations and bootstrap samples in the rows? They'd have to be different input data objects.)

If you really need to compute your own confidence intervals and plot them, I'd say the existing functionality for doing so already exists in matplotlib. And their support for categorical variables has improved a lot recently, and is continuing to improve.

I'd note that there is an `n_boot` parameter to control the number of bootstrap iterations. Something I frequently do when making figures for paper with a large dataset is set that to a very small value for quick iteration, and then set it back  to the default (or often to an even larger value) when I want to finalize the plot.

A while back, I explored using joblib internally to cache confidence intervals and other computationally expensive operations for quick re-drawing, but it ended up not being exactly the usecase joblib was built for and seemed a bit too much of a hack for something that's probably only occasionally helpful.

I'm going to close because this question has of course come up before, and the answer isn't going to change.

**Comment by SynapticSage** [comment]
Alrighty. Well, thanks for the response. I appreciate all the work that's gone into this library.
