### ISSUE TITLE
Conditional colors when using sns.FacetGrid()

### ISSUE THREAD

**Issue by xslates** [mwaskom/seaborn#1493]
Hi,

I'm trying to understand some strange behavior from `sns.FacetGrid()` when using conditional colors. 

I don't know if I'm doing something wrong or if this is a bug. Here's a snippet to reproduce the behavior:

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

df = pd.DataFrame({'val': np.random.randn(100),
                   'group': np.repeat([0, 1], 50)})

df['positive'] = np.where(df['val'] >= 0, 'yes', 'no')

col = np.where(df['positive']=='yes', 'red', 'black')

t = sns.FacetGrid(df, col='group', size=5, despine=False, sharex=False, sharey=False)
t = t.map(plt.scatter, 'val', 'val', 
          color=col, 
          edgecolor='white')
```

This leads to the following plot:

<img width="742" alt="screen shot 2018-07-14 at 13 14 19" src="https://user-images.githubusercontent.com/8994002/42723885-517c68f4-8768-11e8-80dd-8b67174e2b18.png">

Everything checks out in the first facet, but I can't figure out why the second one looks like that. This problem extends as the number of groups increases.

**Comment by mwaskom** [comment]
This can't work because the dataset on each facet is a subset of the full dataset and so there will be no correspondance between the x,y coordinates each call to `plt.scatter` gets and the full vector of colors you're passing.

In `FacetGrid` the way you assign conditional colors is using the `hue` parameter. There's a tutorial and lots of other information in [the docs](http://seaborn.pydata.org/tutorial/axis_grids.html).
