### ISSUE TITLE
How to use lineplot with numpy array

### ISSUE THREAD

**Issue by Seanny123** [mwaskom/seaborn#1499]
Related to [this StackOverflow question](https://stackoverflow.com/q/47581672/1079075), I'm confused about how to replace the error-bar functionality of `tsplot`. Previously, it was possible to make a time-series plot with confidence interval shading using:

```
x = np.linspace(0, 15, 31)
data = np.sin(x) + np.random.rand(10, 31) + np.random.randn(10, 1)
sns.tsplot(data)
```

How do I replace this with `sns.linplot` call? When I try `sns.lineplot(data=data)` it tells me `ValueError: These `style` levels are missing dashes: {6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30}`.

I tried looking at the code to see if I could make the fix myself, but it seems almost as if what I'm trying to do is a bad idea. Is Seaborn not intended to satisfy this case? Is the key to manipulate the data into a DataFrame? Is there any way I can discuss the design of plotting time-series with you or has the window for this discussion passed?

**Comment by mwaskom** [comment]
The equivalent would be to make a long-form pandas dataframe:

```
x = np.linspace(0, 15, 31)
data = np.sin(x) + np.random.rand(10, 31) + np.random.randn(10, 1)
df = pd.DataFrame(data).melt()
sns.lineplot(x="variable", y="value", data=df)
```
![image](https://user-images.githubusercontent.com/315810/42795203-09f385a4-8951-11e8-991b-aa6a56a5b637.png)

`lineplot` has some support for wide form data, but like other modern seaborn functions it's limited in what it can do with it.

**Comment by Seanny123** [comment]
Thank you for taking the time to reply and explaining the intentionally designed limitations of Seaborn.

**Comment by diego898** [comment]
I came across this as well, with a numpy array of size `(numOfTimeSeries x lengthOfTimeSeries)`. Unfortunately, this now gives you  x-axis values from 0 to `lengthOfTimeSeries` instead of what you expect. 

As this has replaced `tsplot`, there should probably be a straightforward way to plot an array of size `(numOfTimeSeries x lengthOfTimeSeries)` as it was under `tsplot`.

**Comment by mwaskom** [comment]
There is a straightforward way, and it’s provided in the second comment in this thread.

**Comment by diego898** [comment]
Previously, you would be able to type: 

```
# myArrayOfEstimates = generate the array of size (numOfTimeSeries x lengthOfTimeSeries)
plt.plot(x,f(x),label='f(x)');
sns.tsplot(myArrayOfEstimates,time=x,color='orange',err_style='unit_traces');
```
to generate something that looks like: 
![image](https://user-images.githubusercontent.com/742407/92037648-b8f0e280-ed37-11ea-99c9-ebd816ec6c6a.png)

Now, as I understand it, I have to use pandas to melt my array and then perform various shifts/corrections in order to be able to use this plot with something else.
