### ISSUE TITLE
Interaction Between Catplot and Plt.Subplots Creates Empty Extra Graph

### ISSUE THREAD

**Issue by nathantchan** [mwaskom/seaborn#1514]
The following code will create an extra graph in a jupyter notebook:
Python: 2.7
Jupyter: 1.0.0
Matplotlib: 1.4.3
Seaborn: 0.9.0
```
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline
cats = np.random.random_integers(1, 10, 10)
numbers = np.random.sample(size = 10)
data = pd.DataFrame({'x': cats, 'y': numbers})
a4_dims = (11.7, 8.27)
fig, ax = plt.subplots(1, 1, figsize = a4_dims)
sns.catplot(y = "x", x="y", ax = ax, data = data)
```
![screenshot from 2018-07-24 14-49-37](https://user-images.githubusercontent.com/7768884/43168091-d191e7f4-8f50-11e8-8de5-8a602511ac63.png)

**Comment by mwaskom** [comment]
That's because `catplot` is a figure-level function: http://seaborn.pydata.org/introduction.html#figure-level-and-axes-level-functions

What's happening is that `ax` is getting passed down to `sns.stripplot` which can use it, but that's basically by accident. If you want to try a strip plot on an existing axes, you should use `sns.stripplot`.

**Comment by xavier-earnin** [comment]
So what is the solution for the catplot case ?

**Comment by sidthakur08** [comment]
plt.close(2) helps to hide the 2nd empty graph
