### ISSUE TITLE
lineplot ignores ls="" without style set

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#1526]
But probably shouldn't.

**Comment by id0158** [comment]
Hello,

I was about to open an issue exactly about this behavior according to the [new features guidelines](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#new-features), but was pleased to discover that you have marked it yourself like a potential improvement ! :smiley:

There are others who also encountered this problem as shown at least by this StackOverflow [question](https://stackoverflow.com/questions/51963725/how-to-plot-a-dashed-line-on-seaborn-lineplot).
The workaround consists in accessing directly the lines of the Axes object in order to set the linestyle.
But if you also want a legend, you have to apply the changes [there too](https://stackoverflow.com/questions/52278350/seaborn-dashed-line-not-dashed-in-the-legend) or manually add [your handles](https://matplotlib.org/3.1.1/tutorials/intermediate/legend_guide.html#creating-artists-specifically-for-adding-to-the-legend-aka-proxy-artists).
Thus, instead of a simple command like this:
```python
sns.lineplot(x='species', y='petal_width', data=sns.load_dataset('iris'),
                  label="Petal width", marker='X', ci=None, linestyle='--')
```
Currently, you have to write:
```python
ax = sns.lineplot(x='species', y='petal_width', data=sns.load_dataset('iris'),
                  label="Petal width", marker='X', ci=None)

ax.lines[0].set_linestyle('--')
ax.legend().get_lines()[0].set_linestyle('--')
```

It is just two more lines, but it took some time to find them.

I also had a look at the [Seaborn code](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L681) and there seems to be a conflict with the [matplotlib.lines.Line2D](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib-lines-line2d)'s `dashes` kwarg which overwrites `linestyle`.
By looking for the interaction between `linestyle` and `dashes`, I first found [this](https://stackoverflow.com/questions/35099130/change-spacing-of-dashes-in-dashed-line-in-matplotlib/35120310#35120310) and then got the confirmation with the [source code](https://matplotlib.org/_modules/matplotlib/lines.html#Line2D.set_dashes) itself.

Thus:
```python
plt.plot([0, 1], [0, 1], linestyle="--", dashes="")
```
![ls_ _dashes](https://user-images.githubusercontent.com/14804964/75587446-ca022380-5a76-11ea-9b46-1662615c8067.jpeg)

Same for:
```python
plt.plot([0, 1], [0, 1], linestyle='-', dashes=(8, 6))
```
![ls_ _dashes2](https://user-images.githubusercontent.com/14804964/75588350-beaff780-5a78-11ea-8641-d26e564e025f.jpeg)

For Seaborn, the problem seems to root [at this line](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L814) where the `dashes` kwarg is _always initialized_ and thus _always overwriting_ `linestyle` when passed to Matplotlib.

At this point, I see two possible solutions:

1. Simply rename the Seaborn's `dashes` keyword. But API breaking, thus perhaps unlikely.
2. Change the [previous line](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L814) with something explicitly depending on the `style` kwarg as it is already stated in the [documentation](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L1169-L1175).

For second solution, something as little as an `if` statement could probably work ?
```python
if style:
    kws["dashes"] = self.dashes.get(style, orig_dashes)
```
As `style=None` by default, Seaborn would not anymore persistently initialize `dashes` kwarg and thus it would let `linestyle` express itself.
A compelling consequence of this fix would be that even the `dashes` kwarg itself could be passed to Matplotlib unchanged by Seaborn when `style` is not defined. The documentation would have to be updated in this case though.

Hope I'm reading all this right and nothing obvious escape me. :sweat_smile: 

Thank you otherwise for this package, it is a true added value to Matplotlib !

**Comment by mwaskom** [comment]
This is tricky because of the two different ways of specifying the style of the lines in matplotlib (xref https://github.com/matplotlib/matplotlib/issues/17483) and the fact that `line.get_linestyle` doesn't actually give you the specific dash parameters (see my comment on that thread).

But actually, the `dashes` parameter never makes its way down to `_LinePlotter.plot`, so the line that pops it off the kwargs never has an effect.

It looks like `dashes` supercedes `linestyle`, so it should be fine to do `plt.plot([0, 1], [0, 1], linestyle=None, dashes=(4, 2))`. But that has the feeling of code that might break in the future if matplotlib adds more input checks...
