### ISSUE TITLE
Wrong legend labels

### ISSUE THREAD

**Issue by bioinfogy** [mwaskom/seaborn#1547]
I'm plotting a lineplot with hue='time_scale'.
time_scale is one of [0.01, 0.1, 1, 2]
The legend shows the values 0.0, 0.4, 0.8, 1.2 with colors that are not part of the plot.

**Comment by mwaskom** [comment]
I can't help you without a reproducible example of the problem, sorry. I'll reopen if you add code that I can run and an example of the output that you get.

**Comment by bioinfogy** [comment]
Hi, a minimal example is:
```
df = pd.DataFrame({'x': [1,2,3]*8, 'y': [4,5,6]*8, 'v': [2,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,8,8,8,9,9,9]})
sns.lineplot(data=df, x='x', y='y', hue='v')
```
For me the legend shows 0,2,5,7,10

I would upload an image but I don't know how or where :/

**Comment by mwaskom** [comment]
From the `lineplot` docstring:

```
legend : "brief", "full", or False, optional
    How to draw the legend. If "brief", numeric ``hue`` and ``size``
    variables will be represented with a sample of evenly spaced values.
    If "full", every group will get an entry in the legend. If ``False``,
    no legend data is added and no legend is drawn.
```

**Comment by bioinfogy** [comment]
ah, it's not a bug, it's feature^^
Still in my opinion the colors in the brief option are wrong. 0 and 2 have the same color, 10 has the color of number 9.
Like this, the brief option does only make sense for continuous data, in which case [feature request] a continuous color scale legend would be nice :)

**Comment by mwaskom** [comment]
> Still in my opinion the colors in the brief option are wrong. 0 and 2 have the same color, 10 has the color of number 9.

Your opinion is wrong in the sense that your data range only from 2 to 9 and, because the default is to norm the colormap to the range of the data, values above or below those should get the same color. Currently the code uses the matplotlib ticking algorithms to choose a reasonable number of "nice" levels, which can end up putting values outside of the range of the data. Those values could probably be clipped, (as happens with ticks on an axes during the rendering pipeline) but it's a hard problem to solve in general and not something where I want to be writing a custom implementation for.
