### ISSUE TITLE
Allow `loc` parameter for Grid.add_legend()

### ISSUE THREAD

**Issue by ply** [mwaskom/seaborn#1561]
I tried to put a legend to `catplot` at some non-default position. I expected `.add_plot()` to pass `loc` parameter to underlying method (as it's documented in docstring), but it throws an exception. 

**Current behaviour:**
```python
>>> import seaborn as sns
>>> g = sns.catplot(
...     data=sns.load_dataset('tips'),
...     x='total_bill',
...     y='tip',
...     hue='size',
...     legend=False
... )
...
>>> g.add_legend(loc="lower center")
Traceback (most recent call last):
  File "<ipython-input-162-321bf238b41f>", line 1, in <module>
    g.add_legend(loc="lower center")
  File "/usr/local/lib/python3.7/site-packages/seaborn/axisgrid.py", line 88, in add_legend
    **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/figure.py", line 1758, in legend
    l = mlegend.Legend(self, handles, labels, *extra_args, **kwargs)
TypeError: __init__() got multiple values for argument 'loc'
```
**Expected behaviour:** `add_legend()` passes `loc` to `Legend` constructor

I'm using python 3.7.0, matplotlib 2.2.3 and seaborn 0.9.0

**Comment by MaozGelbart** [comment]
This exception is thrown for both cases where the catplot (or the grid) was initialized with either ``legend_out==True`` (default) or ``legend_out=False``. However, the behavior is different between the two cases. I have prepared a fix (#1686) for both cases but for the former (which is the one you refer to in your code) will only work nicely for ``loc="lower right"`` or ``loc="upper right"`` arguments, since the underlying code assumes the legend to be aligned to the right. For the ``legend_out=False`` case the behavior is intuitive.
