### ISSUE TITLE
Map_diag(): Also pass column names?

### ISSUE THREAD

**Issue by yannikschaelte** [mwaskom/seaborn#1562]
In 0.9.0, the API for seaborn.PairGrid.map_diag() (https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1352) changed: Now it no longer passes pd.DataFrames to the handling function, but only np.ndarrays. It would be good to have also the information on the column name or the index passed to the function. Maybe it would be possible to pass this as a keyword argument?

In more detail, in our application we have a very simple quadratic plot where every pair of columns is mapped directly to a single subplot. To construct it, we also take information into account which is not contained in x, y, but in another matrix k which has the same columns as the data dataframe.

**Comment by mwaskom** [comment]
I'm not sure what change you're talking about but I don't think DataFrames would ever have been used for a 1D plot. It won't work to inject column names into keyword arguments because it would cause plotting functions that aren't expecting them to crash. Without any more information about what you're trying to do, I can't really help, but I'd remind you that you can pass additional keyword arguments yourself to `map_diag`.

**Comment by yannikschaelte** [comment]
As far as I could see, in the latest version ``np.asarray`` is called explicitly, so that beforehand we could use the information in the dataframe for our purposes, which is now no longer possible. But in our case we now already found a different solution. Thanks for your response though!

**Comment by Gkchandora** [comment]
@joelostblom I am unable to get your comment, can you please fix the given code below to put the dataframe column name in the diagonal of seaborn pairgrid ?
`import matplotlib.pyplot as plt
import seaborn as sns
iris = sns.load_dataset('iris')

def diagfunc(x, **kws):
    ax = plt.gca()
    ax.annotate(x.name, xy=(0.05, 0.9), xycoords=ax.transAxes)

sns.PairGrid(iris).map_diag(diagfunc)`

**Comment by joelostblom** [comment]
@Gkchandora Use the for loop to iterate over the axes in the FaceGrid (`g` = the FacetGrid in my snippet above). You can see a complete example in my second code chunk in [this SO answer](https://stackoverflow.com/questions/48139899/correlation-matrix-plot-with-coefficients-on-one-side-scatterplots-on-another/50690729#50690729).

**Comment by oskar-j** [comment]
I encountered a similar problem, fortunately, I found this: https://datascience.stackexchange.com/questions/57673/how-to-put-the-variable-names-of-pandas-data-frame-on-diagonal-of-seaborn-pairgr and used an `iterator` inside a function for `map_diag`.

So, I defined a method like this:

```
__next_colname = iter(df.columns.tolist()).__next__
```

and used `__next_colname()` instead of `x.name`
