### ISSUE TITLE
catplot (kind='point') does not scale int or float x-axes.

### ISSUE THREAD

**Issue by freekvh** [mwaskom/seaborn#1565]
I have made a catplot (kind='point') from my time range data, like this:

```
sns.catplot(data=e0_60min, x='time (min)', y='green intensity/nucleus', hue='condition', ci='sd', kind='point')
```

Since x is a column with ints I would expect the x axis to scale proportional to the values (I mean the gap between 0 and 1 should be 30 times smaller than the gap between 30 and 60). However, the plot looks like this:

![2018-09-12 14_43_09-clipboard](https://user-images.githubusercontent.com/12241293/45425627-34b07b00-b69a-11e8-99cd-77590c5ac4dd.png)

**Comment by mwaskom** [comment]
https://seaborn.pydata.org/generated/seaborn.catplot.html

> This function always treats one of the variables as categorical and draws data at ordinal positions (0, 1, … n) on the relevant axis, even when the data has a numeric or date type.

**Comment by freekvh** [comment]
I have always learned that it is wrong to draw lines between datapoints that have no connection that is signified by said line. This is what happens here. This type of x-axis makes sense for boxplots and indeed categorical data but not for these type of x-axes. Or perhaps I should say: Is there any type of data where you want the categories connected by a line like this? I think that only happens when the x-axis is not categorical, like in my plot. Any suggestions how I can make such a plot with seaborn?

And, could you consider this a feature request?

**Comment by mwaskom** [comment]
> And, could you consider this a feature request? Perhaps add xaxis_type=non_categorical? I think it would be very nice for this type of data (where indeed I have my time points as categories in my pd.DataFrame).

No, sorry.

**Comment by freekvh** [comment]
Ok, thank you for your swift replies.

**Comment by NougatRillettes** [comment]
Hello,

Sorry to post in a closed issue but could you elaborate your refusal to consider it as a feature request ? Is it a conceptual opposition to having such a feature in seaborn ? If yes is it in any way debatable ? If not would you be open to a pull request implementing it, and maybe helping me attempt to code it ? I am currently working on time series with variation and I find myself re-implementing from scratch plots similar to  seaborn's ones (scatter, box(en), violin,...)  because I can't space my "categories" (i.e. timepoints) in an other way than equidistant.

Best
