### ISSUE TITLE
[discussion] Adding raincloud plot to seaborn?

### ISSUE THREAD

**Issue by cxhernandez** [mwaskom/seaborn#1572]
[Micah Allen's](https://micahallen.org/2018/03/15/introducing-raincloud-plots/) Raincloud plots seem like they might be a nice addition to this package. 

@pog87 has already done some [great work porting it into python](https://github.com/pog87/PtitPrince).

**Comment by mwaskom** [comment]
I think if a package already exists it doesn't need to be in seaborn.

**Comment by mwaskom** [comment]
If you would like to take on responsibility for maintaining that code, you are more than welcome to. But I have minimal interest in doing so.

**Comment by pog87** [comment]
Hi @cxhernandez and thank you for the interest in my package. Ptitprince is written on the top of seaborn and partially rewrites some of its code. I would find it difficult, at the current state to merge it to sns for two main reasons:

1. It adds a `move` parameter to some sns classes in order to "slide" the categorical plot along the categorical axe. This is similar to the move option in R-ggplot2. If sns mantainers are willing to add this feature, this issue is solved.

2. Some choices I made are quite nonstandard. This could be fixed easily.

Also, ptitprince *is* on PyPI now. I will add the setup.py in the next weeks.
