### ISSUE TITLE
How to retrieve cluster membership from clustermap

### ISSUE THREAD

**Issue by deniseduma** [mwaskom/seaborn#1576]
Hi,
I guess this is not an issue but I'm not sure where else I could ask this question and I cannot find any documentation about it: once I use clustermap on my data and visualise the hierarchical clusters, how do I retrieve the cluster membership of the samples? Are these given by clustergrid.dendrogram_col.labels?

Thank you,
Denise

**Comment by mwaskom** [comment]
Hi — Stackoverflow would be the best place to ask this question. But it's best not to think of it as a question about seaborn. The clustering uses scipy functions, and the dendrograms are scipy objects. I bet if you search for scipy rather than seaborn you'll get better existing responses. And you might find that it's best to use the scipy functions directly, rather than accessing them through a plotting interface.
