### ISSUE TITLE
Formatting numerical legend

### ISSUE THREAD

**Issue by stevencollinscn** [mwaskom/seaborn#1584]
I'm looking for a way to format the numerical legend (e.g. using integers) and thought it would be something that is handed by `matplotlib`, but was told not. I haven't received any answer on [StackOverflow ](https://stackoverflow.com/questions/52503899/format-number-in-legend-label-in-matplotlib) for this question either. Thus, I wonder if there is a way to do so with Seaborn right now.  If not, I wonder if this could be a possible feature to add in the future release.

![n5pun](https://user-images.githubusercontent.com/33796896/46644543-ae7b3d80-cb4e-11e8-9298-c2c49f049de0.png)

**Comment by mwaskom** [comment]
Likely you have not received an answer on StackOverflow because without a fully reproducible example it's very difficult to provide any help. However, you're not using seaborn in that example, so I am not sure what assistance I could provide. My suggestion is to edit your StackOverflow question to give people something to work with.
