### ISSUE TITLE
Adding the style keyword to Facetgrid

### ISSUE THREAD

**Issue by KeithWM** [mwaskom/seaborn#1586]
First of all (as I'm new here) hat's off for the good work, I love seaborn. Nevertheless, I have a small feature request.

When using sns.scatterplot, I often use both hue and style keywords during data exploration. I also often use FacetGrid in combination with scatterplot. But it would be nice if FacetGrid also accepted the style keyword, for flexibility. Consider the following:

    g = sns.FacetGrid(tips, col="time",  hue="smoker")
    g = (g.map(plt.scatter, "total_bill", "tip", edgecolor="w")
...       .add_legend())

Imho, it would be nice if we could simply replace col by style to get 

    g = sns.FacetGrid(tips, style="time",  hue="smoker")
    g = (g.map(plt.scatter, "total_bill", "tip", edgecolor="w")
...       .add_legend())

While the result would be identical to

    sns.scatterplot(x="total_bill", y="tip", hue="smoker", style="time", edgecolor="w")

I'd say there's a lot of value to keeping the same syntax as when the "time" was represented by the "col" keyword instead of "style".

I have the suspicion this is deliberately impossible to avoid seaborn being abuse to generate horrific plots with row, column, hue AND style data*. I agree that this is undesirable, but we can trust users not to do this, can't we?

Kind regards,

Keith

*In fact, when preaching the seaborn gospel to my colleagues, I always state "if it's not possible in seaborn, it's something you shouldn't want to do anyway".

**Comment by mwaskom** [comment]
Unfortunately this is not really possible, or at least, not without changing the design principles of `FacetGrid`. Faceting on z with `hue` works because basically all matplotlib and seaborn  functions have a `color` parameter and do something sensible with it. Changing style is much trickier because different kinds of plots would need to be changed differently — e.g. different markers for points vs. different dashes for lines.

By design, `FacetGrid` is almost completely agnostic to what kind of functions can be mapped. There are just a few simple interface requirements. Supporting `style` would mean encoding much more information about supported functions into `FacetGrid` itself, or asking the user to supply it though an external API. Neither is a good path.

> I'd say there's a lot of value to keeping the same syntax as when the "time" was represented by the "col" keyword instead of "style".

I agree. But that's why [`relplot`](https://seaborn.pydata.org/generated/seaborn.relplot.html) exists.
