### ISSUE TITLE
Discussion of flowchart for Seaborn graph choices

### ISSUE THREAD

**Issue by mattharrison** [mwaskom/seaborn#1618]
I do corporate training (for Python and Machine Learning). For my trainings I wanted a flowchart to help decide what plot to use. 

I was told (via Twitter) that @mwaskom would provide feedback/ideas via the issue tracker.

Would love to hear anyone's thoughts

![seaborn](https://user-images.githubusercontent.com/119405/49197391-ef702100-f34b-11e8-87b7-32f60d7215ce.png)

**Comment by mmagnuski** [comment]
I'd move the plot titles above/below each image as currently they are not easy/pleasant to read in some cases. I'd also consider choosing a better image example for lineplot "Use hue, style, markers" and maybe some more exciting distribution for kdeplot/distplot.

**Comment by mwaskom** [comment]
I think many aspects of the overall structure are good. I agree with @mmagnuski's aesthetic comments but will leave that for you to figure out. Here are a few of the main things I would do differently:

- in my mind the first order decision is "examine whole dataset structure" vs "examine targeted relationships". That decision separates `pairplot` (and `{heat,cluster}map`) from the rest of the tools. it's true that those tools are mostly useful for continuous data — though heatmap is arguably a categorical vs. categorical plot — but still in my mind, format of data is secondary to a goal. 
- i wouldn't branch off time series data so early. time series are just a special case of continuous / continuous data, and `lineplot` can be used perfectly well without the `x` variable representing time per se. Also, `relplot` has a `kind=line`.
- i would have expanded the `catplot` option to represent the decision you're faced with after (represent the observations, the distributions, or the central tendencies). that's an important decision point, and the ability to flip through them quickly with the same api is one of the more compelling reasons to use seaborn.
- it's probably not necessary to have separate endpoints for distplot and kdeplot.
- i'm not sure i understand the inclusion of the bottom two options.

The other confusing thing about the flowchart is there's no distinction between [figure- and axes-level functions](http://seaborn.pydata.org/introduction.html#figure-level-and-axes-level-functions). so e.g. you have `relplot` and `lineplot`, when `kind="line"` is an option of `relplot` and you don't have `scatterplot` at all.

Granted, some of this confusion is due to complexity in seaborn itself. but collapsing over that decision point adds confusion, or at least misses an opportunity to alleviate it. Really there is a third dimension at many branch points, which is whether you want a figure or axes level function (generally my suggestion is to use the figure-level option for EDA unless you are drawing into an existing figure).

I'd also suggest cleaning things up by representing the fact that some endpoints can add dimensions by using `hue`, (`hue`/`size`/`style`), or (`hue`,`row`,`col`) in a different way — perhaps with colored outlines and then a legend. That would save some space and make it easier to satisfy some of the points above.
