### ISSUE TITLE
lineplot errorbar clarifications

### ISSUE THREAD

**Issue by drbenvincent** [mwaskom/seaborn#1619]
It would be great to get a bit more clarity in the docs about what, exactly, the shaded region in `lineplot` represents. The documentation here https://seaborn.pydata.org/tutorial/relational.html#aggregation-and-representing-uncertainty says "The default behavior in seaborn is to aggregate the multiple measurements at each x value by plotting the mean and the 95% confidence interval around the mean." But does this mean the 95% CI of bootstrap estimates _of_ the mean is, or the empirical 95% percentiles of the underlying data _around_ the mean?

Along similar lines, the `lineplot` docs here https://seaborn.pydata.org/generated/seaborn.lineplot.html#seaborn.lineplot mention that the argument `ci` can be `Int`, `'sd'` or `None`. What does the `Int` value mean - the percentile as above (with the default of 95)?

Would be very handy to have a brief bit more clear and explicit information. It would make it much easier to write about what the figures are representing in academic papers, for example.

**Comment by mwaskom** [comment]
>  But does this mean the 95% CI of bootstrap estimates of the mean is, or the empirical 95% percentiles of the underlying data around the mean?

I'm not sure what the second option you're describing is, but it doesn't sound like a confidence interval. Really neither of your suggestions are right: the 95 percentile band of the bootstrap estimates gives you the 95% *confidence* interval for the mean.

I guess my general response would be that it's an open source package for a reason and if you really want to know exactly what's happening, you can and should read the code.

**Comment by luk-f-a** [comment]
@mwaskom , reading the `lineplot`documentation I found the description of `ci` was not enough for me to be sure of what was going on (had to go to the code to clarify, which took longer). would you accept a PR expanding the description in the documentation? 
It's not uncommon for papers to include a quantile range around the median, therefore it's easy to think that `ci=25` would calculate the quartiles of the data (instead of the quartiles of the bootstrapped mean).
