### ISSUE TITLE
catplot size arg. colliding with stripplot() arg.

### ISSUE THREAD

**Issue by multicolorist** [mwaskom/seaborn#1635]
Using seaborn 0.9.0, matplotlib 3.0.2

**Current behavior**
```
import seaborn as sns
sns.set(style="ticks")
exercise = sns.load_dataset("exercise")
g = sns.catplot(x="time", y="pulse", hue="kind", data=exercise, kind='strip', size=5)
```

Results in:

> /Users/tralala/anaconda3/envs/ml/lib/python3.6/site-packages/seaborn/categorical.py:3692: UserWarning: The `size` paramter has been renamed to `height`; please update your code.
>   warnings.warn(msg, UserWarning)

**Expected behavior**

That the size argument is passed through to the underlying function `stripplot()` to control the marker size, as it does when calling it directly.

**Workaround**

Use the argument `s`, which can be seen [here](https://github.com/mwaskom/seaborn/blob/fe172c44777f87159e9e2b00e919bbd055d6f696/seaborn/categorical.py#L2783) works. Example:

```
import seaborn as sns
sns.set(style="ticks")
exercise = sns.load_dataset("exercise")
g = sns.catplot(x="time", y="pulse", hue="kind", data=exercise, kind='strip', s=10)
```

**Solution ideas**

One possibility is to remove the [deprecation warning](https://github.com/mwaskom/seaborn/blob/fe172c44777f87159e9e2b00e919bbd055d6f696/seaborn/categorical.py#L3687-L3692) entirely.

Better would be to change the argument name in [the function definition](https://github.com/mwaskom/seaborn/blob/fe172c44777f87159e9e2b00e919bbd055d6f696/seaborn/categorical.py#L2770), since `size` is such a generic term.

This is my first issue submitted on an open-source project, and I'd be willing to write a fix if you think it's a good idea.

**Comment by mwaskom** [comment]
The deprecation warning that you see is one step in the process you are suggesting. The names collided, so one had to be changed (`size` => `height` in `FacetGrid` and derivatives). But that had to happen in a few stages, with a warning, to be polite about existing code.

Eventually (probably next version) the warning will be removed and `size` will control the markers not the facets. I tend to handle deprecations just prior to releases so that the changes are easily accessible in the release notes.

**Comment by kwbln** [comment]
It's still an issue, right?
