### ISSUE TITLE
Oddity in applying custom ticks to y-axis of FacetGrid after log transformation 

### ISSUE THREAD

**Issue by sbarter510** [mwaskom/seaborn#1651]
When attempting to use FacetGrid.set(yscale = ('log'), yticks = ticks, yticklabels = labels) in line the ticks are not re set. You must keep the yscale in one line. Then call .set() again and apply the ticks.

![sb1](https://user-images.githubusercontent.com/31393335/51060759-a7c4f200-15a5-11e9-9f1b-c0057eafc7c1.JPG)
![sb2](https://user-images.githubusercontent.com/31393335/51060760-aabfe280-15a5-11e9-9f4b-791230751507.JPG)

**Comment by sbarter510** [comment]
I guess this isn't unique to FacetGrid. It seems to apply to PairGrid as well. Forgive me if I'm just not understanding the axis over ride process of calling yscale.

**Comment by mwaskom** [comment]
`FacetGrid.set` is just looping over the axes and calling `set` on each one in the plot, so if there is a problem it would be at the matplotlib level.

But my guess is that the kwargs are not being processed in the order you expect, since kwargs are a dictionary and dictionaries are unordered on python < 3.6 (I think). So I think you just need to call it twice: once to set the scale and once to set the ticks on the (now log-scaled axes). But without an example I can copy and paste, I can't help beyond that.
