### ISSUE TITLE
Incorrect legend in lineplot when using numeric values in hue

### ISSUE THREAD

**Issue by bjkomer** [mwaskom/seaborn#1653]
I believe this is related to #1560 but happens even when `style` is not used and gives incorrect behaviour with `lineplot`.

Here's an example. The legend should have two items, 0.2 and 0.3

```
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.DataFrame(
    [
        [0, 0, .2],
        [1, 1, .2],
        [2, 2, .2],
        [0, 0.5, .3],
        [1, 1.5, .3],
        [2, 2.5, .3],
    ],
    columns=['x','y','hue']
)

sns.lineplot(data=df, x='x', y='y', hue='hue')
plt.show()
```
![seaborn_bug_1](https://user-images.githubusercontent.com/1361151/51222511-12f72700-190c-11e9-8c29-c1978740498f.png)

Interestingly it works if the `hue` column contains strings or integers as the categorical value rather than floats. I guess casting that column to a string could be a workaround in the meantime.

**Comment by bjkomer** [comment]
It turns out casting the column to a string doesn't work at all, and produces the following error:

```
Traceback (most recent call last):
  File "seaborn_legend.py", line 55, in <module>
    sns.lineplot(data=df, x='x', y='y', hue='hue')
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/seaborn/relational.py", line 1078, in lineplot
    sort=sort, err_style=err_style, err_kws=err_kws, legend=legend,
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/seaborn/relational.py", line 670, in __init__
    self.parse_hue(plot_data["hue"], palette, hue_order, hue_norm)
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/seaborn/relational.py", line 375, in parse_hue
    data, order, palette, norm
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/seaborn/relational.py", line 260, in numeric_to_palette
    norm(np.asarray(data.dropna()))
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/matplotlib/colors.py", line 942, in __call__
    self.autoscale_None(result)
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/matplotlib/colors.py", line 988, in autoscale_None
    self.vmin = A.min()
  File "/home/user/anaconda3/envs/py3torch/lib/python3.6/site-packages/numpy/ma/core.py", line 5588, in min
    axis=axis, out=out, **kwargs).view(type(self))
AttributeError: 'str' object has no attribute 'view'
```

This is with seaborn version `0.9.0` and python `3.6.7`.
This error occurs when the data is a string that can be interpreted as an integer or float

**Comment by rovyko** [comment]
I'm getting the exact same issue. There seem to be at least two problems occurring here:

1. Seaborn is assuming that the numerical "hue" represents some continuous value and tries to group those values into bins
2. Seaborn interprets strings with numerical values as floats and tries to pass them to numpy as such, resulting in an error

I've found two workarounds, neither of which are optimal:

1. Convert the hue column into a string and concatenate some non-numeric value. This causes the legend entries to be ordered incorrectly, so they should be resupplied in the `hue_order` argument.
2. Supply the hue column into the style argument, which only interprets numerical variable as ordinal.

It's important to note that same thing happens when the column is supplied to the `size` argument. A possible solution could be to add an argument (for both `hue` and `size`) that lets the user chose the data type for the variable: `numerical` (applies groupings), `ordinal` (no groupings but uses numerical order) and `categorical` (continues the current logic applied to non-numeric strings).

**Comment by rovyko** [comment]
Looks to me like the problem is centered around [`parse_hue`](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L339) and [`parse_size`](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L386) in `relational.py`.  They both call on [`_semantic_types`](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L523) to determine whether the data is `categorical` or `numerical`.

Additional arguments `hue_var_type` and `style_var_type` could bypass this check if specified. When the value `ordinal` is supplied, the `var_data` is set as `categorical` with the order being inferred from the numerical values. If unspecified, the original check is performed allowing for backwards compatibility.

I could put together a pull request to apply this solution, but I'm not sure how the maintainers feel about adding arguments to such critical functions.

**Comment by rovyko** [comment]
I think I can put a fix together without breaking anything. The way that [`_semantic_types`](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L523) recognizes string data as numerical is incompatible with the rest of the library.

In the case that `data` is an array of strings that could be converted to floats, there isn't a way for `_semantic_types` to pass a converted `data` array outside of `parse_hue` / `parse_size`. The `AttributeError` seen [here](https://github.com/mwaskom/seaborn/issues/1653#issuecomment-454867198) is caused by `_semantic_types` reporting the variable type as `numeric` but when palette groups are being calculated by `numeric_to_palette`, the data is still as strings. This can be solved by adopting a converted `data` object returned by `_semantic_types`, but then this needs to be set in the `_RelationalPlotter` instance for the graphing functions to use.

An easier way it to simply read the type from the `data` array and make a decision based on that. The types listed in `np.sctypes['int'|'uint'|'float']` can be aggregated and should be `numeric`, while all others should be `categorical`. If the user wants the plotter to interpret the variable as a particular type they can convert the data type manually.

**Comment by arvoelke** [comment]
My current work-around is to convert the hue entries into strings that will not be reinterpreted as something else. e.g.,

```
df["hue"] = ["$%s$" % x for x in df["hue"]]
```

where the `$...$` is a hack (with the side-effect of rendering the number in LaTeX) that prevents:

```
AttributeError: 'str' object has no attribute 'view'
```

Other schemes such as `"= %s" % x` also work.

**Comment by Srj** [comment]
if your dataframe contains numerical value then just add these line before plotting and you are done.
`df['Target'] = df['Target'].astype('category')`

**Comment by alunawat** [comment]
Just set legend='full' in the call to seaborn lineplot

**Comment by JayPalm** [comment]
> Just set legend='full' in the call to seaborn lineplot

This did the trick and was incredibly simple, thank you!

**Comment by adgaudio** [comment]
Adding additional information about the methods above, I found that:

- `df['Target'] = df['Target'].astype('category')`  evenly distributes the colors across categories, regardless of number value
![image](https://user-images.githubusercontent.com/860369/121229742-4264b080-c886-11eb-98a7-7178144e47a8.png)


- `legend="full"`  makes the numeric categorical values very close in color if the numbers were close, and vice versa.  This does not apply if the Target values have dtype "category".  
![image](https://user-images.githubusercontent.com/860369/121229518-f9acf780-c885-11eb-9a45-535aa375d914.png)
