### ISSUE TITLE
Feature request: adding seaborn.kdeplot object as a parameter to seaborn.lineplot

### ISSUE THREAD

**Issue by Pezhvuk** [mwaskom/seaborn#1707]
Hi,

I was wondering if it makes sense and/or would be feasible to add `seaborn.kdeplot` object (or an object attribute) as a parameter to `seaborn.lineplot`?

It would make life so much easier. For instance, currently, I am totally failing at getting any error bands to my kde plot and cannot figure out why this is. In order to get error bands for my kde, I am having to do the kde using the `scipy.stats.kde` and then pass `x = numpy.linespace(data.min, data.max, len(data))` and `kde.evaluate(x)` to lineplot in order to get error bands around the distribution. However, while the shape of the distribution perfectly matches that of `seaborn.kdeplot` product, I get no error bands whatsoever. I realise that I should, and I will, figure out my issue in this specific instance myself (not asking for a whole update just to solve my problem), but I think this solution is most likely very easy and straightforward to add, and with proper warnings, could prevent such silent errors in the future.

Thank you and best wishes,

**Comment by mwaskom** [comment]
I’m not sure I really understand what you’re doing, but lineplot draws error bands by bootstrapping when there are multiple y values for unique x values. That doesn’t sound like what you have. Doing something like accepting a kde object in lineplot would be a complete departure from how the function otherwise works, so I’ll decline that suggestion, thanks.
