### ISSUE TITLE
Colormap centering & norms

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#1740]
There is a beautiful way to center a colormap using seaborn in `heatmap`:
```
ax = sns.heatmap(np.linspace(-2, 5, 100).reshape((10, 10)), cmap='coolwarm', center=0, square=True)
ax.axis('off')
```
![image](https://user-images.githubusercontent.com/2895034/57636027-48511000-75a0-11e9-8883-474f8df66cc9.png)

Unfortunately, there is not tool that does it in `matplotlib` itself. Is there a way to just get a colormap like this with specific vmin, center and vmax to use in `matplotlib` functions?

Also, is there a way to apply e.g. a `LogNorm` to the plot made with `heatmap`?

**Comment by mwaskom** [comment]
You can't really get "just a colormap .. with a specific vmin, center, and vmax" because the limits aren't properties of the colormap, they're properties of the visualization that uses it. But you could use/adapt this: https://gist.github.com/phobson/7916777

To answer your second question, you can use the `norm=` argument from `pcolormesh`, but it will probably interact in unpredictable ways with the centering.
