### ISSUE TITLE
DatetimeArray conversion warning from pandas while plotting against a datetime column

### ISSUE THREAD

**Issue by antoine-gallix** [mwaskom/seaborn#1832]
I have a pandas dataframe with a timezone-aware timestamp column. When trying to plot some data using the timestamps as x-axis, I receive a warning coming from pandas because of an implicit conversion of timezone-aware timestamp into timezone-naive. This is probably not a desired behavior.

```python
> df['timestamp'].dtype
datetime64[ns, UTC]
> seaborne.lineplot(data=df,x='timestamp',y='ph')
/[...]/lib/python3.7/site-packages/seaborn/relational.py:792: FutureWarning: Converting timezone-aware DatetimeArray to timezone-naive ndarray with 'datetime64[ns]' dtype. In the future, this will return an ndarray with 'object' dtype where each element is a 'pandas.Timestamp' with the correct 'tz'.
	To accept the future behavior, pass 'dtype=object'.
	To keep the old behavior, pass 'dtype="datetime64[ns]"'.
  x, y = np.asarray(x), np.asarray(y)

```

`pandas` version: 0.25.1
`seaborn` version: 0.9.0

**Comment by kurt-rhee** [comment]
I have the same issue

**Comment by mwaskom** [comment]
A reproducible example would be especially helpful...

**Comment by mwaskom** [comment]
I actually don't think there's anything for seaborn to do here. Matplotlib seems to handle both options fine, so I don't think the change will be disruptive. seaborn should not always force one or the other dtype, because the function is not limited to only plotting datetimes. It may be possible to isolate the specific case where this warning will be raised (I guess if the `dtype` has a `tz` attribute?) and handle that, but my knowledge of the details is weak enough that I would defer not to potentially introducing issues. The warning is a little annoying, but it's raised only once per session and will go away soon. So, absent a demonstration that there is an actual issue, I'm not going to change anything.
