### ISSUE TITLE
Feature Request: Rotate xticks in pairplot

### ISSUE THREAD

**Issue by renatobellotti** [mwaskom/seaborn#1853]
It would be nice if this was possible.

**Comment by mwaskom** [comment]
It is possible.

**Comment by renatobellotti** [comment]
How?

**Comment by MaozGelbart** [comment]
The convenient way of rotating xtickslabels in seaborn grid plots is by calling ``set_xticklabels(rotation=angle)`` on the ``FacetGrid`` object returned from the grid plotting function. However running the following code:
```python
import seaborn as sns; sns.set(style="ticks")
iris = sns.load_dataset("iris")
g = sns.pairplot(iris)
g.set_xticklabels(rotation=45)
```
raises the following error:
``AttributeError: 'PairGrid' object has no attribute 'set_xticklabels'``

The problem is that ``PairGrid`` inherits from ``Grid`` but ``set_xticklabels()`` is only defined for ``FacetGrid`` and therefore lacking this functionality. 

I think you can rotate xticks labels with the following code:
```python
g = sns.pairplot(iris)
g.fig.draw(
    g.fig.canvas.get_renderer()
)  # required, as matplotlib calculates ticks during draw time
for ax in g.axes.flat: 
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45)
```

**Comment by renatobellotti** [comment]
Thanks for the answer. This seems to be a good workaround, but I'd still like to see this feature implemented. @mwaskom why did you close this issue? It is still unresolved.

**Comment by Travis-Barton** [comment]
This is a feature I would appreciate as well. The work around works... but is in no way convenient or elegant.

**Comment by mwaskom** [comment]
This is the most direct way to accomplish it in matplotlib:

```python
penguins = sns.load_dataset("penguins")
g = sns.pairplot(penguins)
for ax in g.axes.flat:
    ax.tick_params("x", labelrotation=45)
```

`PairGrid.set_xticklabels` doesn't exist because the axes in the `PairGrid` don't represent the same variables and generally don't have the same ticks, so a single interface for setting a vector of ticks doesn't make much sense.
