### ISSUE TITLE
edgecolors keyword does not work when map plt.hexbin to sns.FacetGrid

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [mwaskom/seaborn#1860]
Hello,

I am using seaborn 0.9.0 and matplotlib 3.1.0.

I came across a problem when mapping `plt.hexbin` to `sns.FacetGrid`. Using the `tips` data embedded in seaborn, I can easily plot a hexbin figure like the following.
```
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
tips = sns.load_dataset("tips")
plt.hexbin(tips[tips['time']=='Lunch']['total_bill'],tips[tips['time']=='Lunch']['tip'],mincnt = 1, cmap = 'viridis', gridsize =10, edgecolors = 'face')
```
Output here
![image](https://user-images.githubusercontent.com/43779303/67877987-803e1680-fb32-11e9-8744-d514698cfcae.png)
It can be seen that `edgecolor = 'face'` controls that each hex has similar edgecolor and facecolor. However, when I use `sns.FacetGrid` to map `plt.hexbin`, edgecolor does not seem work anymore.
```
g = sns.FacetGrid(tips, col ='time')
g.map(plt.hexbin, "total_bill", "tip", mincnt = 1, cmap = 'viridis', gridsize =10, edgecolors = 'face')
```
Output here
![image](https://user-images.githubusercontent.com/43779303/67878546-65b86d00-fb33-11e9-9fad-87a2ac240406.png)

My problem is that how to let the hex have identical facecolor and edgecolor.

Thanks in advance!

**Comment by MaozGelbart** [comment]
Hi @FeiYao-Edinburgh ,

[FacetGrid.map()](https://seaborn.pydata.org/generated/seaborn.FacetGrid.map.html#seaborn.FacetGrid.map) documentation states that the plotting function should be a plotting function which takes a ``color`` keyword argument, since ``map()`` injects a ``color`` kwarg to the provided plotting function. The behavior of ``plt.hexbin`` when provided with ``color`` is overriding the ``edgecolor`` argument (depending on kwargs order). You can wrap hexbin and remove the ``color`` kwargs, and then call ``map()`` with the wrapper function:
```python
def myhexbin(*args, **kwargs):
    kwargs.pop("color", None)
    plt.hexbin(*args, **kwargs)

g = sns.FacetGrid(tips, col ='time')
g.map(myhexbin, "total_bill", "tip", mincnt = 1, cmap = 'viridis', gridsize =10, edgecolors = 'face')
```
Alternatively, add this statement before you show/save the plot:
```python
for ax in g.axes.flat:
    for col in ax.collections:
        col.set_edgecolor("face")
```

I hope this helps.

**Comment by mwaskom** [comment]
I would have thought that `linewidths=0` would do the trick but the results look subtly different from  `edgecolors="face"`, since you end up with a pixel or so of margin between the hexagonal patches. That may be good enough for what you want, though.

**Comment by FeiYao-Edinburgh** [comment]
Both @mwaskom and @MaozGelbart answers work greatly! Personally I prefer the alternative method provided by @MaozGelbart since I also need to fine-tune other aspects of each facet.
