### ISSUE TITLE
heatmap mask is applied as the transpose

### ISSUE THREAD

**Issue by nwmoriarty** [mwaskom/seaborn#1863]
The attached python script demonstrates that the mask needs to be transposed to apply as desired. Intuitively, having the first row as 1 would make the heatmap mask out the first row. Instead, it masks the first column.

```
import seaborn as sns
import matplotlib.pyplot as plt

a = [[4,5,6],
     [1,2,1],
     [0,1,0],
    ]

mask = [[1,1,1],
        [0,0,0],
        [0,0,0],
       ]

ax = sns.heatmap(a, mask=mask)
```

**Comment by mwaskom** [comment]
It's not immediately obvious what's happening here, but the issue goes away if you cast the mask to an array.

**Comment by nwmoriarty** [comment]
Or add this line

mask = map(list, zip(*mask))

Don't know enough about numpy to comment.

**Comment by mwaskom** [comment]
Generally speaking seaborn expects inputs to be numpy or pandas data structures. Many functions will accept lists and there is usually not strict type checking (as typically they can be cast to arrays without issue) but I would avoid using them because you may hit weird corner cases, as you appear to have here.

**Comment by nwmoriarty** [comment]
Thanks. Like the pandas data structure so will avoid lists.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov
