### ISSUE TITLE
Custom error bars or CI

### ISSUE THREAD

**Issue by loic001** [mwaskom/seaborn#1887]
Hi,

Let's say we have this dataframe **metrics_df**

![image](https://user-images.githubusercontent.com/9749879/70264291-709c9800-1798-11ea-8781-5a92658f41ec.png)

What I want is a simple barplot with custom err bar (**ci_95** column).

The best I could do (without hacking matplot) is this :

```python
sns.barplot(x='metric_names', y='metric_values', yerr=metrics_df['ci_95'], data=metrics_df, color='grey')
```

It works but the seaborn error bar style is lost.

![image](https://user-images.githubusercontent.com/9749879/70265032-d9d0db00-1799-11ea-8d4d-3518b9bf0c11.png)

Being able to give a column name to **ci** arg or a list (or vector) of values directly would be perfect.

Same problem in [this discussion](https://datascience.stackexchange.com/questions/31736/unable-to-generate-error-bars-with-seaborn). The solution they proposed is just awful...

Thanks !

**Comment by mwaskom** [comment]
This has come up a few times and I'd refer you to previous discussion, e.g. #331. Thanks.

**Comment by Ge0rges** [comment]
Perhaps it keeps coming up because this is a basic functionality people expect Seaborn to fulfill, rather than resorting to using lower level matplotlib functions. Anyone working with serious datasets will be computing errors independently from seaborn. I wonder if the devs could expand on their reasoning no to include a seemingly simple feature that's been request quite a few times.
