### ISSUE TITLE
Installation in Python 3.6

### ISSUE THREAD

**Issue by KC2016** [mwaskom/seaborn#1927]
I have installed it with Python 3.6 and Anaconda.

It appears as installed but in jupyter notebook it is not found.  "ModuleNotFoundError: No module named 'seaborn'  "
 
When I run the test, it appears. What it means and how can I solve it?
![Seaborn](https://user-images.githubusercontent.com/18695019/72363396-1545ba00-36f5-11ea-81b4-67ffec721d11.jpg)

**Comment by KC2016** [comment]
I have uninstalled Numpy 1.17 and installed 1.18. Now, the Anaconda does not open.
![image](https://user-images.githubusercontent.com/18695019/72380036-e0495f80-3714-11ea-9b92-458d0a06106b.png)

**Comment by mwaskom** [comment]
Usually, if it looks like the installation succeeded but it can't be imported to jupyter notebook, it's because your pip/conda commands and your jupyter commands point at different python installations.

I don't understand the other error messages you're showing because they don't include any information about what you did to produce them. But they seem to involve numpy, not seaborn, so you're likely to get more useful help elsewhere.

**Comment by KC2016** [comment]
You were right. I had to remove Python from Appdata manually.
The second image is the error that was coming when I tried to open Anaconda. I had to uninstall Anaconda as well. I installed miniconda instead, which now works well. 
Thanks, mwaskom.
