### ISSUE TITLE
Setting hue on lmplot changes point size

### ISSUE THREAD

**Issue by MatthewJMoreno** [mwaskom/seaborn#1959]
Setting the hue to 'Quiz' makes all points the same size

    import seaborn as sns
    import pandas as pd
    data = {'Quiz': [1, 1, 2, 1, 2, 1],
         'Score': [7.5, 5.0, 10, 10, 10, 10],
         'Day': [2, 5, 5, 5, 11, 11],
         'Size': [115, 115, 115, 115, 115, 355]}

    df = pd.DataFrame.from_dict(data)

    sns.lmplot(x = 'Day', y='Score', data = df, fit_reg=False, x_jitter = True, scatter_kws={'s': df.Size})
    plt.show()

**Comment by mwaskom** [comment]
This won't work in `lmplot` because each level of `hue` is passed independently and the `scatter_kws` are just passed through to each underlying call to `scatter` — it doesn't know how to map that vector to each of the subvectors.

You could likely make this work by using `lmplot` just for the regression line and then adding `seaborn.scatterplot` with both `hue` and `size`.
