### ISSUE TITLE
pointplot linestyles not showing in legend

### ISSUE THREAD

**Issue by jbachh** [mwaskom/seaborn#2005]
As you can see in this example from the documentation [docs](http://seaborn.pydata.org/generated/seaborn.pointplot.html#seaborn.pointplot), there is a linestyles argument, but it doesn't show in the legend. This kind of defies the purpose, printing black/white you still can't tell which is which (except from the markers, but often the markers are hard to read because the line is too wide relatively).

Can you make the legend show the linestyle as well, such as in lineplots?

![image](https://user-images.githubusercontent.com/9306134/77420963-4a444c00-6dcb-11ea-8ad6-9bd652943380.png)

**Comment by MaozGelbart** [comment]
A quick fix involves changing the ``plt.plot()`` command that plots the lines to contain markers, labels and relevant size/color parameters:
![2002b](https://user-images.githubusercontent.com/13831112/78020709-9c9ce400-735a-11ea-9697-fea6a6847eed.png) 
However this fails many tests, since they rely on the collections from the ``scatter`` calls. Also it is a little hard to distinguish between the two linestyles with the default ``plt.plot()`` legend elements. 

Perhaps try using grayscale palette? Something like
```
ax = sns.pointplot(x="time", y="total_bill", hue="smoker",
                   data=tips,
                   markers=["o", "x"],
                   palette=[".2",".5"])
```

**Comment by mwaskom** [comment]
I'm not opposed to including the lines in the legend but, as @MaozGelbart notes, it's often hard to distinguish the line style that way, so the minimal benefit has kept it from being a priority. It would also be a somewhat disruptive change. But I'll leave this open for now.

**Comment by mwaskom** [comment]
Aggregating in #2861 and closing here.
