### ISSUE TITLE
Grid color doesn't change with string variable but changes with categorical variable

### ISSUE THREAD

**Issue by paulrougieux** [mwaskom/seaborn#2028]
When using string (character) variables the colour doesn't change
```
import seaborn
iris = seaborn.load_dataset("iris")
g = seaborn.FacetGrid(iris, col="species")
g.map(seaborn.scatterplot,'petal_length','petal_width','species')
```
![Screenshot from 2020-04-17 16-32-26](https://user-images.githubusercontent.com/5647397/79580463-4e614200-80c9-11ea-836e-dc6d5d51a840.png)

It does change when changing that to a categorical variable
```
iris['species'] = iris['species'].astype('category')
g.map(seaborn.scatterplot,'petal_length','petal_width','species')
```
![Screenshot from 2020-04-17 16-32-50](https://user-images.githubusercontent.com/5647397/79580431-45707080-80c9-11ea-829e-3157f1db4885.png)

The behaviour with string variables can be misleading, especially if the data frame contains  combinations of character variables which appear in one facet and are slightly different in another facet, you end up with colors which are not comparable between facets. and the legend only matches to one of the facet. 

```
iris = seaborn.load_dataset("iris")
iris['petal_length_below_4'] = iris['petal_length'] < 4
g = seaborn.FacetGrid(iris, col="petal_length_below_4")
g.map(seaborn.scatterplot,'petal_length','petal_width','species')
g.add_legend()
```
![Screenshot from 2020-04-17 16-44-18](https://user-images.githubusercontent.com/5647397/79581459-bcf2cf80-80ca-11ea-8252-4b2664c2807a.png)

**Comment by mwaskom** [comment]
Yes, this is an unavoidable consequence of the way that `FacetGrid` works. That's why the docs for `scatterplot` have an example that says:

> Use relplot() to combine scatterplot() and FacetGrid: This allows grouping within additional categorical variables. Using relplot() is safer than using FacetGrid directly, as it ensures synchronization of the semantic mappings across facets.

```python
g = sns.relplot(x="total_bill", y="tip", col="time", hue="day", style="day", 
                kind="scatter", data=tips)
```

**Comment by paulrougieux** [comment]
Thank you, I prefer flowers to tippers (because petals are nicer than smokers), the example then becomes:
```
import seaborn
iris = seaborn.load_dataset("iris")
g = seaborn.relplot(x='petal_length', y='petal_width', col='species', hue='species', data=iris)
```
Shall I close this issue then? Or is there a hope that string variables associated to a hue will at some point share charateristics between facets in a facet grid plot?

**Comment by mwaskom** [comment]
> Or is there a hope that string variables associated to a hue will at some point share characteristics (the same hue) between facets in a facet grid plot?

There are already a number of ways to accomplish this. What `relplot` does is pass a `palette` dictionary in the call to `.map`; you could also pass a list of group names to `hue_order`. Either will ensure that the same mapping is used in each facet. Or define categorical types in your dataframe, as you do here. Alternatively, you could use `hue` layering in the `FacetGrid` constructor, but this plots each hue group in series, and can be misleading for dense scatterplots.

By design, `FacetGrid` is agnostic about what function it's drawing with, and just calls the function on each of the input (sub)vectors. If you don't provide any other way for each facet to know about possible values that might occur in other facets, they won't. It's much easier to handle that logic externally than to try to make `FacetGrid` special-case a variety of functions and add parameters the user didn't ask for internally, which is one of the reasons why `relplot` and `catplot` exist.

Note that this issue can arise elsewhere, e.g. the same would be true if you were passing `plt.scatter` with a `c` variable and not specifying the `vmin` and `vmax` across plots. There's an analogous issue with categorical plots that triggers a warning, but that's because you wouldn't necessarily notice that something is wrong with the plot just by looking at it.

Fortunately, in this case the plot is "obviously" wrong. To the extent that anything should change, maybe the tutorial should emphasize that using `FacetGrid` directly is more "advanced" use case.

**Comment by paulrougieux** [comment]
Thanks, now I see that the documentation of the FacetGrid class already has a warning https://github.com/mwaskom/seaborn/blob/7216552848c83b678481d5bca01a180120b0301e/seaborn/axisgrid.py#L397

>  To the extent that anything should change, maybe the tutorial should
>  emphasize that using FacetGrid directly is more "advanced" use case.

I submitted pull request https://github.com/mwaskom/seaborn/pull/2030 to document the need to ensure the same mapping is used between facets .
