### ISSUE TITLE
Catplot legend handles do not include level name

### ISSUE THREAD

**Issue by soorajachar** [mwaskom/seaborn#2068]
Hello, I ran into a minor bug with catplot recently. In relplot, the legend title shows up in the figure's legend handles, while it does not in catplot. This means I can't modify it afterwards or remake the same legend using the handles. Here is an example (legend labels for each figure are at the tops of the plots): 

> ```python
> import seaborn as sns
> import matplotlib.pyplot as plt
> df = sns.load_dataset('tips')
> g = sns.relplot(data=df,x='total_bill',y='tip',hue='tip',palette='coolwarm')
> handles,labels = g.axes.flat[0].get_legend_handles_labels()
> print(labels)
<img width="423" alt="Screen Shot 2020-05-11 at 12 55 42 AM" src="https://user-images.githubusercontent.com/49458891/81525373-7c315380-9322-11ea-9eeb-305addaaa724.png">

> ```python
> g2 = sns.catplot(data=df,x='sex',y='tip',hue='smoker',kind='bar')
> handles2,labels2 = g2.axes.flat[0].get_legend_handles_labels()
> print(labels2)
<img width="415" alt="Screen Shot 2020-05-11 at 12 55 49 AM" src="https://user-images.githubusercontent.com/49458891/81525385-84898e80-9322-11ea-8f14-9dd125d909f8.png">

I'm using seaborn 0.10.1 and matplotlib 3.2.1. The issue persists regardless of what I set "legend_out" to. Thanks.

**Comment by MaozGelbart** [comment]
HI @soorajachar ,

There are differences in the way catplot and relplot generate their legends. catplot stores the legend title as a matplotlib legend title, while replot stores the titles of the various semantics as legend labels. 
Since catplot produces only one figure-level legend, you could query the figure for its legend and then for its title:
```python
import matplotlib as mpl
[c for c in plt.gcf().get_children() if isinstance(c, mpl.legend.Legend)][0].get_title().get_text()
# 'smoker'
```   
Note that this only works if `legend_out=True`. If `legend_out=False`, you should query the first ax for its legend:
```python
g2.axes.flat[0].get_legend().get_title().get_text()
# 'smoker'
```
I hope this helps.

**Comment by soorajachar** [comment]
Thanks @MaozGelbart this worked for me. I appreciate the help.

**Comment by mwaskom** [comment]
Yes — the inconsistency isn't ideal but it's not a bug in the sense that things are working as intended. Thanks @MaozGelbart.
