### ISSUE TITLE
sharex, sharey, factorplot

### ISSUE THREAD

**Issue by razcore-rad** [mwaskom/seaborn#209]
I found a very small bug when using `factorplot`.

`sharex`, `sharey` don't get propagated to `FacetGrid`, line 835 in `linearmodels.py`.

**Comment by mpschr** [comment]
Is it possible this bug has re-appeared in 0.6.0 ?

**Comment by mwaskom** [comment]
That isn't enough information for me to say.

**Comment by mpschr** [comment]
![factorplot-sharex-bug](https://cloud.githubusercontent.com/assets/1090105/9550271/95421516-4daa-11e5-8cfb-29052f47f25e.png)

**Comment by mpschr** [comment]
Python3.4
seaborn 0.6.0

**Comment by mwaskom** [comment]
That is expected behavior in version 0.6.

**Comment by mpschr** [comment]
Ok, How could I get rid of the superfluous factors ?

**Comment by mmagnuski** [comment]
@mpschr - if you are setting both `x='time'` and `col='time'` the result you are getting is intuitive (at least to me). I'm not sure what is your expected outcome, but getting rid of `col='time'` gives a nice looking plot.

**Comment by mpschr** [comment]
@mmagnuski 

The issue is the `sharex=False`: I would expect for each suplot, only the factors on the x-axis that have data. So, in the `time=1min` plot, `15min` and `30min` should not be expected to show up as there is no data for the for those factors.

The above is just an example (derivated from the tutorial examples) and I know it does not make much sense to produce this particular plot. In my case I have a plot with `x=patient` which belong to 4 `patientgroups`, which I therefore use to for the row argument: `row=patientgropus`. What happens is that on the x-axis, each patient is showing up in each patient group subplot even tough I have set `sharex=False`, just as shown in the example the plot above.

My understanding is that the `sharex=False` is not being applied with factors. Hopefully this can be arranged? Should I open a separate bug report/feature request, @mwaskom ?

**Comment by mwaskom** [comment]
It doesn't really have anything to do with `sharex` but rather that the factor order is enforced to use all levels of the factor, because otherwise the plots will be wrong (or can't be guaranteed to be correct) when subsets are drawn. You could try using `FacetGrid` directly, but you'll have to be very careful to make sure that your data are being plotted correctly.

**Comment by mpschr** [comment]
Hi @mwaskom ,

Let  me say first, that I have not taken a good look at the code, so I don't know how the interior works. In any case, when one specifies a `factor` as `x`-axis, then I guess it can be expected that `sharex` is directly related to the `x` parameter - even tough it being a factor. I don't know if I explained well enough, but I expected the same would happen, as if `x` were numeric: the axis range is adapted to the data represented in the subplot.

I don't know if you agree and think it might be implemented? If not, I'd introduce a warning message saying something the like `sharex=False cannot be applied to a factor-axis`.

I'll go have a try with `FacetGrid`, thanks for the suggestion.

Michael

**Comment by christian-oreilly** [comment]
Same issue here. Using
```
g = sns.factorplot(x="bins", y="density", hue="species2", col="small_mtype", 
                   data=data, 
                   sharex=False, sharey=False,
                   rows="small_mtype",
                   size=5, linewidth=1)
```

I can obtain a nice plot for data which are histogram-like (i.e., normalized count-per-bin; 30 bins with range [0, 200]):

![image](https://user-images.githubusercontent.com/5932954/38739500-63caee98-3f35-11e8-8dae-e9119687377d.png)

However, the range for the left plot should definitely be larger. So I would like to have 30 bins with a range [0, 400] for the left plot and [0, 200] for the right plot. Plotting such a dataset now does not give a nice result:

![image](https://user-images.githubusercontent.com/5932954/38739633-c17b2f58-3f35-11e8-800f-e589e8d0c109.png)

This is because the x-factor is shared between the other grouping factors (e.g., grid column and row factors). I wonder if it would be possible to add a switch that would allow to disable explicitly this sharing of the x/y factors across column/rows.
