### ISSUE TITLE
Publish documentation for older releases at seaborn.pydata.org

### ISSUE THREAD

**Issue by alexhutcheson** [mwaskom/seaborn#2117]
Some users need to use older versions of seaborn, and may not have the authority to upgrade them.

Other Python packages maintain the documentation for older releases on the web. For example:

- [pandas 0.24.2](https://pandas.pydata.org/pandas-docs/version/0.24.2/index.html#)
- [numpy 1.17](https://numpy.org/doc/1.17/)
- [matplotlib 2.2.5](https://matplotlib.org/2.2.5/index.html)

It would be nice to have an archived version of the docs for older releases available on the Seaborn website, for users who need to use older releases.

**Comment by mwaskom** [comment]
I agree this would be "nice" but it would require a substantial amount of work on my end.

Feel free to put the work in yourself and open a pull request.

Note that it's always possible to checkout an old version and build the docs locally.

**Comment by mwaskom** [comment]
I also find that Sphinx websites, or google, or some bad interaction between them, are bad at updating the search index so that queries go to the latest version. I'm constantly finding myself on old versions of other sphinx sites (including those that you have linked to) and needing to figure out how to find that information on the actual current docs.

**Comment by alexhutcheson** [comment]
Totally reasonable. Thanks for the quick response, and thanks for all the work you've put into making seaborn awesome!

Building the docs locally is actually a helpful suggestion - I'll do that.

I'm unlikely to try to tackle this in the near term, so feel free to close as "won't fix" if you'd prefer not to leave it open

**Comment by mwaskom** [comment]
> Building the docs locally is actually a helpful suggestion - I'll do that.

It won't be immediately obvious how to do it .

- You'll want to install the tools in the `requirements.txt` file in the doc directory.

- The build process is a bit more complicated than a normal sphinx site because many of the source files are jupyter notebooks. The command to make the full site is `make notebooks html`.

nbconvert will error out if your system doesn't have a kernel with the same name as what the notebooks were made with. I don't know if there's a better way to solve this within nbconvert itself, but you can set the `NB_KERNEL` environment variable to something that does exist on your system.

The github action workflow that tests the doc build is a good reference: https://github.com/mwaskom/seaborn/blob/master/.github/workflows/ci.yaml

All in all, it's a fun process.

**Comment by mwaskom** [comment]
> substantial amount of work

For reference, the main problem is that because the docs aren't currently versioned, there would need to be a process of setting up a set of redirects so that incoming links point to the current/stable set of docs. Or the stable docs could not be under the versioning system, but then it's harder to figure out what older pages correspond to what newer ones.

But, like I said, I have only ever looked at older docs by accident, when google sends me to the wrong place, so I'm not super enthusiastic about adding it even if someone else solves the practical issues.

**Comment by mwaskom** [comment]
(Also note that for older docs you only need to build the notebooks if you want to look at the intro or tutorial materials. Just running `make html` as normal should build the API docs, which is probably what you want)

**Comment by mwaskom** [comment]
https://seaborn.pydata.org/archive.html

**Comment by mwaskom** [comment]
Put meta tags to hopefully block search engines from indexing the archived versions, and punted on linking from a specific old page to a new one.

**Comment by mwaskom** [comment]
LMK if anyone needs 0.8.
