### ISSUE TITLE
Feature Request: statistical annotations for boxplots or barplots

### ISSUE THREAD

**Issue by normanius** [mwaskom/seaborn#2132]
It is very common to add statistical annotations when comparing boxplots or barplots. See the screenshot for an example.

(A) Are there any plans to include a similar feature or (B) to at least facilitate the addition of such annotations?

![image](https://user-images.githubusercontent.com/11406002/84556825-a2814f00-ad25-11ea-9db9-9a8044e6221f.png)

So far, it's rather difficult to add such annotations because seaborn's `boxplot()` and `barplot()` don't expose the boxes and bars they draw. One could grab the matplotlib artists and try to reverse engineer the plot content, but this is way too difficult.

I've found [statannot](https://github.com/webermarcolivier/statannot), a great attempt to work around this missing feature. But the solution re-implements some of seaborn's code and recreates the plots internally. Also, the annotation logic was not matching my needs perfectly. Before digging into statannot, I thought to check first why seaborn is not offering that feature in first place. 

Thanks!

**Comment by mwaskom** [comment]
There are no plans to add this to seaborn. Personally, I very much dislike these annotations. Why ruin a perfectly nice visualization, which can give you so much information, by adding some stars that will make people think only about an arbitrary p value threshold?

I've never looked at the statannot code, but I don't see why it would need to re-implement seaborn internals. Understanding a plot by parsing the matplotlib artsist data can be cumbersome to do in an interactive context, but it would strike me as the preferred approach for a library. Plus, if you do it that way, then the annotations can go on any matplotlib figure, not just one drawn by seaborn.

**Comment by normanius** [comment]
Thank for your view on this. I agree with you that the p-value receives far too much attention and that the visualization of data is much richer and should be generally encouraged. Still, statistical tests are elemental in many disciplines and are sometimes even enforced by scientific journals. The need to combine the information from tests with the data visualization is quite natural. Moreover, group-aware annotations could be used not just for statistical information.

I think the problem with the artist-level approach is that it is quite difficult to link a particular artist with the information in the input data. No "group" or "label" is assigned to the artists, so one has to infer the content by re-implementing the logic of the drawing facility. This is difficult, error-prone, and in my view just as bad as code duplication.

I think statannot has done a good effort to avoid a lot of duplication by using internally `_BoxPlotter` and `_BarPlotter` which expose some information about the groupings. From what I understand, it still had to duplicate the logic for some missing bits.

Back to my original request: I see that implementing an annotation infrastructure can be quite tricky to work well with all categorical plotters. And I can understand your objections regarding the benefits of such annotations (though I think that should be up to the users to decide how and for what they use seaborn). I'm fine with closing this request.

For those still in need to extend or modify plots, however, it would be very helpful if the artists created by seaborn were grouped and labeled (class [`Artist`](https://matplotlib.org/3.2.1/api/artist_api.html#metadata) offers `gid` and `label`), according to the structure of the input data. (For example: `gid = (hue, cat)` and label being a string referring to the element (such as "box", "whisker", "median", ...) for boxplots). I see that this leads a completely different feature request, which I can surely move to a new issue.

**Comment by mwaskom** [comment]
I understand that some people feel compelled to add them to their plots. (and, for example, I don't tell people to remove them when I review papers). But supporting this would require a lot of big, complicated API decisions. So my general opposition combined with the fact that it would be quite hard to support well yields a quite firm response about it being part of seaborn.

I'm fine with other packages implementing them, and am open to making that easier. I would **strongly** encourage other packages not to try and extend seaborn by using the internal `_Plotter` objects, however. The leading underscore indicates that they are part of the private API and are subject to change in any release without warning or compatibility.

I have long wanted to add some kind of metadata onto the matplotlib axes or artists to facilitate post-seaborn modifications. I had been thinking more along the lines of a data structure that gets added to the matplotlib axes that links seaborn semantics to matplotlib artists, but it could work at the artist level too.

As to your specific suggestions: using `label` won't work because then the artists will end up in the automatic legend. I don't know what matplotlib uses `gid` for, or whether setting it would cause unexpected problems. If it's meant to be a hook for third-party packages to set metadata on, then I'd be open to it.

**Comment by normanius** [comment]
Ah, right. `label` can't work. I'm not proficient enough with matplotlib to make any further suggestions on that level, but a data-structure passed through the API calls and populated by seaborn could also be nice and useful.

```python
handles = {}
sns.boxplot(..., out_handles=handles, ...)
````

But that's for another issue. I'm closing this one.

By the way. Thanks for all the work! Seaborn is fun to use and super useful.
