### ISSUE TITLE
Feature Request: Quantile based intervals in lineplot

### ISSUE THREAD

**Issue by aeftimia** [mwaskom/seaborn#2169]
I often find it easier to interpret a graph that says "95% of the data lies within this interval" over "95% of resampled means lie within this interval". Does this seem like a reasonable feature? Under the hood, I think sorting the `y` data for each sample of `x` and looking at the element at the `len(y) * ci // 200` index and the `len(y) * (1 - ci / 2) // 100` index would suffice to determine interval bounds. Maybe it could be triggered with `n_boot=None`?

**Comment by mwaskom** [comment]
This is a feature I would like to have and plan to add, probably for 0.12. But it is a substantial project because it's going to require a new external API (and refactoring of core code).

In the meantime, I have been firmly opposed to adding hack-ish extensions to the existing API, such as changing the interpretation of `ci` when `n_boot=None`(one illustration of how that's not clear is that someone else has previously submitted a PR that computes analytic confidence intervals with that set of arguments).

I am going to close this issue as I consider https://github.com/mwaskom/seaborn/issues/1501 to be the cannonical issue for tracking this feature request.
