### ISSUE TITLE
Errorbars and labels/legends on JointGrid?

### ISSUE THREAD

**Issue by AlexaVillaume** [mwaskom/seaborn#2175]
Hello, 

I'm trying to make a figure comparing two data sets, similar to what was asked about in this [issue](https://github.com/mwaskom/seaborn/issues/294) which was very helpful and I've been able to make this figure

![image](https://user-images.githubusercontent.com/5116488/88857355-fd261b80-d1aa-11ea-9048-156c82cacc86.png)

with the following code:

```
g = sns.JointGrid(
                  data1['age'], data1['Fe'],
                  space=0, xlim=(-0.5, 15), ylim=(-2.2, 0.4)) 

g.ax_joint.plot(data1['age'], data1['Fe'],
                         ls='None', marker='o', 
                         label='data1')
sns.kdeplot(data1['age'], ax=g.ax_marg_x,
                    legend=False)
sns.kdeplot(data1['Fe'], ax=g.ax_marg_y, vertical=True,
                    legend=False)


g.ax_joint.plot(data2_age, data2_fe,
                        ls='None', marker='*', 
                        label='data2')
sns.kdeplot(data2_age, ax=g.ax_marg_x)
sns.kdeplot(data2_fe, ax=g.ax_marg_y, vertical=True)

```

But I'd really like to 1.) include the uncertainties on the measurements in the scatter plot, 2.) Change the axes labels, and 3.) label the different data sets in the scatter plot. 

Are any of these possible? 

Best,
Alexa

**Comment by mwaskom** [comment]
Generally speaking yes, but since you're using matplotlib functions directly these are really questions about matplotlib. e.g. you could use `errorbar` instead of `plot` and you could call `legend` after giving labels.

You may find that you get quicker and better answers to "how do I do x" questions on StackOverflow, as github issues are meant for bug reports and other development-related matters.
