### ISSUE TITLE
feature request: add arguments "style" and "style_kws" in FacetGrid

### ISSUE THREAD

**Issue by vedal** [mwaskom/seaborn#2176]
To allow for the same flexibility as `sns.relplot(..., kind='line')`, I suggest adding arguments "style" and "style_kws" in FacetGrid. This makes sense if you want to separate the style from the hue parameter, f.ex by adding markers, linestyles etc.

**Comment by mwaskom** [comment]
This isn't really possible because, while all (or nearly all) matplotlib functions accept `color=`, there's not a similar generic "style" parameter. e.g. scatter points take markers, lines take dashes (and maybe markers), fills could use hatches (but the matplotlib hatch API is fairly limited). Abstraction requires consistency.

**Comment by vedal** [comment]
@mwaskom thanks for the swift reply. It makes sense...
what would be your suggested way to pass further styling parameters into FacetGrid.map?? Is there a better way than 
```
def myplot(x, y, style, **kwargs):
	if style.values[0] == 'some_value'


FacetGrid.map(myplot, x, y, ... style)
```

**Comment by mwaskom** [comment]
I’d need to know more about what exactly you hope to do but in general I would say this is a better question for stackoverflow. Make sure you include s clear description of what you’re hoping to achieve.
