### ISSUE TITLE
JointGrid could have axhline/axvline analogues that would plot on joint and marginal axes

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#2249]
Would need to thing about the right name, but probably a good idea.

**Comment by stefmolin** [comment]
Do you mean something like this?

![image](https://user-images.githubusercontent.com/24376333/123520903-4152c200-d681-11eb-8228-34498c9bf666.png)


I added a `plot_refline()` method to prototype this on [my fork](https://github.com/stefmolin/seaborn/blob/jointgrid-reflines/seaborn/axisgrid.py#L1800-L1834). It would be called like this:
```python
import seaborn as sns

penguins = sns.load_dataset('penguins')
g = sns.jointplot(data=penguins, x='bill_length_mm', y='bill_depth_mm')

# by default plot on both the marginal and joint axes
g.plot_refline(value=16, orient='h', linestyle='dashed', color='gray')

# only on joint
g.plot_refline(value=45, orient='v', marginal=False, linestyle='dotted', color='red')

# only on marginal
g.plot_refline(value=55, orient='v', joint=False, linestyle='dashed', color='blue')
```

**Comment by mwaskom** [comment]
Yes, basically. But I think I would prefer the following API:

```python
JointGrid.refline(self, x: float | None = None, y: float | None = None, **line_kws)
```

I'm ambivalent about having `joint` and `marginal` parameters as booleans defaulting to `True`. It feels like one could just call the underlying matplotlib function if you only want a line on one subplot.

**Comment by stefmolin** [comment]
Sure, I'll update the API to what you mentioned.

With regards to the `joint` and `marginal` parameters, I agree that matplotlib could just be used to plot a single line. However, the caller needs to know how to access the individual plots in the `JointGrid`. I just took a quick look at the [seaborn docs](https://seaborn.pydata.org/generated/seaborn.JointGrid.html), and while they do state that, for example `ax_marg_x` is the way to access one of the marginal plots, you have to know what you are looking for to find it (since there is no attributes section in the docs and the example is halfway through the page). So perhaps having these parameters does indeed add value? Also, the `JointGrid` class does have a method for saving the plot, which can also be done via matplotlib directly &ndash; I think it comes down to defining where the line between seaborn and matplotlib is/should be, and I'll defer to you on that one :smiley:
