### ISSUE TITLE
pairplot y_vars bug

### ISSUE THREAD

**Issue by Delleter** [mwaskom/seaborn#2260]
Just updated to seaborn 0.11.0 and matplotlib 3.3.1. 

Run this code:
```python
iris = sns.load_dataset("iris")
sns.pairplot(data=iris, hue="species", y_vars='sepal_width');
sns.pairplot(data=iris, hue="species", y_vars='sepal_width', x_vars=['sepal_length', 'petal_length']);
```

And saw it:
![screen](https://user-images.githubusercontent.com/24957288/92593736-438e9000-f2aa-11ea-93ac-3fb7b2c94a68.PNG)

And this problem appeared in all previously created pairplots, that have parameter y_vars

**Comment by Delleter** [comment]
If I add parameter diag_kind=None - everything works well:
![screen](https://user-images.githubusercontent.com/24957288/92620101-f1aa3200-f2ca-11ea-9dc1-c7fb92b4587c.PNG)

**Comment by mwaskom** [comment]
Thanks for reporting. I think I've tracked this down.

The underlying issue here is actually not new in 0.11. It was introduced in https://github.com/mwaskom/seaborn/pull/1824 (the second component), which uses the wrong indices for the off-diagonal plots when the grid is set up such that matched x/y vars do not actually fall on the diagonal. (The plots that actually end up in the figure do all seem correct, but not all of the axes are used). This should be fixed, although it will take a little thinking to determine the correct way.

The reason it turned up in 0.11 is that `pairplot` changed to actually use this logic, i.e. to show a marginal plot on the "diagonal" axes even when the overall grid is not square. As you've found, setting `diag_kind=None` disables that and just shows a bivariate plot on all axes, which uses `PairGrid.map` and skips the broken logic altogether.

**Comment by RobRomijnders** [comment]
Using `diag_kind=None` resolved the issue for me as well.
