### ISSUE TITLE
Axis on barplot is reversed

### ISSUE THREAD

**Issue by JulianWgs** [mwaskom/seaborn#2268]
Hello,

sorry I currently do not have the time to create a minimal code snippet, but I will provide one, when I find time.

When using a vertical barplot the order is reversed compared to a matplotlib bar plot. This not only is an issue, when switching in between the two libraries, but also when using tikzplotlib to export the plot to a LaTex document. Here the axis arrow points in the wrong direction.

My fix for tikzplotlib was to use `plt.gca().invert_yaxis()` to invert the axis, but I think this can also allign the behavior of both libraries.

I'm using seaborn 0.10.1.

- Is this behavior of seaborn on purpose?

Best regards,
Julian

**Comment by mwaskom** [comment]
As best as I can tell from a description without code or an image, you're describing expected behavior.

In the future, please wait until you have time to create a reproducible example before asking your question. I appreciate that you may be busy, but the people who will be answering your questions are busy too, and making it harder for them to understand what you are asking means that they need to devote more time to your problem. Some may consider this rude.

**Comment by JulianWgs** [comment]
I've provided a pastable example. Please reopen the issue :)

**Comment by JulianWgs** [comment]
Is this going to be reopened? :)

**Comment by mwaskom** [comment]
No, because the behavior is expected and working properly.
