### ISSUE TITLE
FR: define center point in diverging_palette

### ISSUE THREAD

**Issue by StevenLi-DS** [mwaskom/seaborn#2289]
I found myself really enjoying using seaborn's palette functions. I use seaborn-generated cmap in other pkgs. Please consider add a new param to define the center point in `diverging_palette` function, like the `center` arg in `heatmap` function.

**Comment by mwaskom** [comment]
I'm not sure if this makes sense, because it seems you would need knowledge of the data limits to use properly.

You could perhaps also use a [matplotlib norm](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.colors.TwoSlopeNorm.html).

Feature requests will generally receive more serious consideration if you put some effort into articulating why it's a good idea, what specific API you are proposing, etc.

**Comment by StevenLi-DS** [comment]
@mwaskom Could you take a look at this [issue](https://gis.stackexchange.com/a/330175/114581) here and I think this might be a good example why this would be helpful if you can create a center point in a cmap directly without using matplotlib norm.

**Comment by mwaskom** [comment]
But what units would the center point be? In `heatmap`, it is in data units, because you also pass the data to `heatmap`. But you don't pass data to a colormap function. And indeed, colormap objects should be data independent, with the mapping between data units to colormap intensity handled by a `Norm` object.

**Comment by StevenLi-DS** [comment]
@mwaskom I see. Indeed.
