### ISSUE TITLE
displot vs distplot in seaborn

### ISSUE THREAD

**Issue by shahmoradi** [mwaskom/seaborn#2300]
I recently noticed that seaborn throws a warning with the use of `distplot()` and recommends `displot()`. I wonder what the underlying reason is for such rapid, subtle, and hard-to-notice changes. If you grab a FORTRAN-1966 code, you can still pass it to a modern Fortran 2018 compiler, such as Intel, and it will compile and run just fine after half a century and more. But the Python-seaborn code that I wrote in my summer class just two months ago does not work anymore, because of such minor syntax changes. These frequent renamings will only kill the popularity of the seaborn package and the Python language in the long-run.

**Comment by mwaskom** [comment]
> These frequent renamings will only kill the popularity of the seaborn package and the Python language in the long-run.

One can only hope!

**Comment by shahmoradi** [comment]
That's not a professional response to a valid question.

**Comment by mwaskom** [comment]
I put substantial work into documenting the rationale for the change. It’s fine if you can’t be bothered to read release notes for the software that you use, and if you’d asked politely, I would have directed you to them. But your issue was quite rude, so you’ll have to find them yourself. Good luck with FORTRAN!
