### ISSUE TITLE
Inconsistent tick marks in clustermap

### ISSUE THREAD

**Issue by smitchell556** [mwaskom/seaborn#2305]
There's two sources of inconsistencies:

1. There aren't tick marks for the label associated with `row_colors`, but there is for the label of `col_colors`.
1. The actual data points have tick marks for the rows, but not the columns.

If 2. is by design, then it's a moot point, but I think for consistency's sake, 1. should be addressed. Either they should both have tick marks or neither should have tick marks. I can make a PR with the necessary changes for both/neither to have tick marks if you'd like.

Attached is an image showing what I mean.

![clustermap_row_ticks_only](https://user-images.githubusercontent.com/14005263/94578744-13516600-0246-11eb-97de-eeeef8ffa4b6.png)

**Comment by mwaskom** [comment]
Please supply a reproducible example (i.e. code that can be copied and pasted to produce your image).

**Comment by mwaskom** [comment]
Please also note the versions of matplotlib and seaborn that you are using (as requested [here](http://seaborn.pydata.org/installing.html#getting-help)).

I cannot reproduce what you are seeing with seaborn 0.11.0 and matplotlib 3.3.1:

```
import seaborn as sns
import pandas as pd
sns.clustermap(pd.DataFrame([[1, 2], [3, 4]]),
               col_colors=pd.Series(["r", "b"], name="a"),
               row_colors=pd.Series(["g", "y"], name="b"))
```

![image](https://user-images.githubusercontent.com/315810/94582028-c96a7f00-0249-11eb-800f-9e45494fcafe.png)

**Comment by smitchell556** [comment]
Since you can't reproduce, I did a little more digging and the problem doesn't lie with seaborn or matplotlib. This inconsistency only shows up when I generate plots from a Jupyter notebook and not a regular Python REPL. Sorry for the bother.

**Comment by mwaskom** [comment]
Still weird though as I made my plot in a notebook (using the inline backend).

**Comment by smitchell556** [comment]
It only happens after calling `sns.set()`. Both `color_codes=True` and `color_codes=False` or with no arguments causes the tick marks to behave differently based on the axis. I can step through the debugger on this one, but won't be able to set time aside until tomorrow at the earliest. My initlal thought was to just modify the tick marks in `ClusterGrid.plot_colors()`, but it seems there's some underlying issue caused by setting the theme, or is that expected behavior?

Version info:
matplotlib: 3.3.2
seaborn: 0.11.0

```python
import matplotlib
import pandas as pd
import seaborn as sns
%matplotlib inline
sns.set()  # This causes the change in tick marks
g = sns.clustermap(pd.DataFrame([[1.0, 0.5], [0.5, 1.0]]),
                   row_colors=pd.DataFrame([['r'], ['r']], columns=['Red']),
                   col_colors=pd.DataFrame([['g'], ['g']], columns=['Green']))
g
```

**Comment by mwaskom** [comment]
The default theme does not have visible tick marks, so the problem is not in the absence of x tick marks but in the presence of y tick marks.

It looks like matplotlib is adding them back when moving the ticks to the right side of the axes:

```
f, ax = plt.subplots()
ax.yaxis.tick_right()
```
![image](https://user-images.githubusercontent.com/315810/94601258-39383400-0261-11eb-8292-53485f4ec956.png)

**Comment by mwaskom** [comment]
I think the relevant matplotlib issue would be here: https://github.com/matplotlib/matplotlib/issues/3921

**Comment by smitchell556** [comment]
Ok, so my thoughts are to either wait for matplotlib to sort this out or to explicitly set the y tick marks formatting to be the same as the x tick marks in `_HeatMapper` and `ClusterGrid`. That is an old issue, so I'm not confident it will be fixed in matplotlib any time soon.

**Comment by mwaskom** [comment]
I looked into this a bit yesterday and while I'd be opening to working around it in seaborn, it's not clear that it would be possible to do so in a straightforward way. The problem is that while you can set the tick params via `ax.tick_params`, e.g.: 

```
sns.set()
f, ax = plt.subplots()
ax.yaxis.tick_right()
ax.tick_params(length=0)
```

there is not a corresponding API for reading out the parameters that an axis is using. As far as I can tell (and I could be wrong here), one would need to dig into the properties of the actual `Line2D` objects that matplotlib is using the represent the tick marks.

This would be a complicated and messy workaround within seaborn. In contrast, there are two pretty easy workarounds in userspace:

- use a theme with ticks present
- set the ticks with `tick_params` to how you want them to look after plotting.

So I am somewhat inclined to say that this is an upstream bug and not change anything in seaborn itself. I agree that prospects don't seem great for it getting fixed in matplotlib, but the effort involved in doing so probably isn't much more than the effort involved in implementing a workaround in seaborn...

**Comment by smitchell556** [comment]
Ah that's unfortunate, I just assumed there was some method that would return the existing tick params of an axis. It's definitely easy enough to do from the user side and looks like a high cost, low reward fix for seaborn. Thank you for digging into it.
