### ISSUE TITLE
map_* methods of PairGrid broken in 0.11.0

### ISSUE THREAD

**Issue by astrophysaxist** [mwaskom/seaborn#2307]
Hi,

I discovered that the map_* methods of PairGrid seem to be broken in version 0.11.0 for user defined functions. See reproducible example below with a corrfunc defined to plot the pearson correlation value on the lower plots. The function doesn't seem to get evaluated in version 0.11.0. When I pip install seaborn==0.10.1, I get the desired result. Plots from both cases also attached.

```import numpy as np
from scipy import stats
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="white")

mean = np.zeros(3)
cov = np.random.uniform(.2, .4, (3, 3))
cov += cov.T
cov[np.diag_indices(3)] = 1
data = np.random.multivariate_normal(mean, cov, 100)
df = pd.DataFrame(data, columns=["X", "Y", "Z"])

def corrfunc(x, y,**kws):
    r, _ = stats.pearsonr(x, y)
    ax = plt.gca()
    ax.annotate("r = {:.2f}".format(r),
                xy=(.1, .9), xycoords=ax.transAxes)

g = sns.PairGrid(df, palette=["red"])
g.map_upper(plt.scatter, s=10)
g.map_diag(sns.distplot, kde=False)
g.map_lower(sns.kdeplot, cmap="Blues_d")
g.map_lower(corrfunc)
plt.show()

```

![seaborn-0-11-0](https://user-images.githubusercontent.com/3239171/94969718-380d3e00-04d1-11eb-821b-9aad80ec696e.png)

![seaborn-0-10-1](https://user-images.githubusercontent.com/3239171/94969722-3a6f9800-04d1-11eb-8ef1-861d9beb1f26.png)

**Comment by mwaskom** [comment]
Seems related to the fact that `PairGrid` now takes different paths depending on whether the function has a `hue` parameter  or not.

For now, you can workaround by adding `hue=None` to the function signature.

Will take some effort to figure out exactly what's going wrong.

**Comment by loftusa** [comment]
@mwaskom I tracked this down a bit in in the debugger when I was trying to figure out #2349. As far as I can tell, the difference is in `PairGrid._plot_bivariate`. Because `hue` is not in `signature(func).parameters`, `self._plot_bivariate_iter_hue` runs instead of the rest of the function. That's as far as I got, though.

**Comment by loftusa** [comment]
tracking this a bit more now cause I'm still curious.

For my case (using the code in #2349), looks like it's the fact that `self.hue_names` and `self.hue_vals` have different types, line 1491 of `axisgrid.py`. 

`self.hue_names` returns ['0', '1'], a list of strings
`self.hue_vals` returns 0, an int64

So `hue_grouped.get_group(label_k)` attempts to iterate through a list of strings, whereas `get_group` needs to eat an int in this case.

**Comment by mwaskom** [comment]
Yes, good sleuthing. So the specific conditions for the problem are:

- non-string column names in the dataframe
- a call to `map*` with a function that supports `hue` followed by a call to `map*` with a function that doesn't

Interestingly, commenting out that line is mostly innocuous. It doesn't fail any tests and simple example plots seem to run fine. I don't remember exactly what it's there for, but I believe its purpose is to allow hue parametrization as handled by the axes-level function update the tracking that `PairGrid` does and then uses when it creates a legend. e.g., this plot is semi-wrong:

```python
g = sns.PairGrid(df, hue="A")
g.map(sns.scatterplot, hue_order=[1, 0])
g.add_legend()
```

![image](https://user-images.githubusercontent.com/315810/99107326-a60a5200-25b3-11eb-8110-7d22ae4bf03e.png)

The data are represented/mapped correctly and the legend is technically correct but the order of the entries in the legend is not what you would otherwise expect.
