### ISSUE TITLE
Shared clim between two kdeplots.

### ISSUE THREAD

**Issue by sergeyf** [mwaskom/seaborn#2376]
Hello,

Thanks for this awesome package! Is there a way to have a shared clim between two KDE plots?

I'm doing something like this:

```python
    f, axes = plt.subplots(1, 2, figsize=(15, 6), sharex=True, sharey=True)
    for ax, s in zip(axes.flat, ['a', 'b']):
        df_sub = df[df['variant'] == s]
        kdeplot = sns.kdeplot(x=df_sub['x'], y=df_sub['y'], fill=True, levels=100, cmap="cividis", cbar=True, ax=ax)
```

The two figures have different colormap ranges. What's the right approach to have them share the exact same colormap?

**Comment by mwaskom** [comment]
In theory this should work if you use `displot`, something like

```python
sns.displot(data=df, x="x", y="y", col="variant", kind="kde", ...)
```

but I just discovered a bug (#2377) that prevents this from working exactly.

You could work around it in the meantime by adding `hue="variant", legend=False`, but it will be a bit annoying because you'll lose the ability to provide your own colormap and will have to live with using the color-seeded colormap (you can pass 
`palette=[color, color]` to share the colormap across the facets).

Probably the best workaround for now.

FWIW raw density values are IMO not that meaningful and if you pass specific iso-proportion levels the contours will have the same meaning across the two subplots, even if they map to different density levels. Worth thinking about.

Closing here as the bug is tracked in a separate issue.

**Comment by sergeyf** [comment]
Thanks! I tried passing in `palette=[color, color]` to `distplot` in various forms, but none of them worked. I tried passing in strings of color names, cmaps, etc. Am I missing something obvious here?

**Comment by mwaskom** [comment]
I'd need to know exactly what you did and exactly what happened to say.

**Comment by sergeyf** [comment]
Ah I'll figure it out. I appreciate both your time, and the extremely useful package!
