### ISSUE TITLE
Prevent Overlapping Plots Without Invoking Matplotlib?

### ISSUE THREAD

**Issue by dhern023** [mwaskom/seaborn#2395]
Importing matplotlib.pyplot is not the best software engineering practice as it exposes the underlying library. Having to write plt.figure() before each instance of seabon relies on the matplotlib state machine interface rather than fully embracing the object-oriented interface.

Is there any way to prevent or stop seaborn from plotting multiple figures on top of one another from within its catplot and histplot API?

**Comment by mwaskom** [comment]
The [seaborn docs](http://seaborn.pydata.org/introduction.html#relationship-to-matplotlib) are very clear that it does not aim to fully encapsulate matplotlib. But if you look through the (many) examples there, you will see a mixture of plots that can be made without direct use of matplotlib and others that require it.

I'm going to close here because you don't provide a specific issue that you're having.

**Comment by dhern023** [comment]
Since the very docs you cited state I should "[know] when dropping down to the matplotlib layer is necessary to achieve a particular customization," I'll interpret the answer to my question as a "No, you should just invoke matplotlib," which is understandable.

Also, the majority of examples listed show at most one plot, or intentionally overlap. That's also understandable.

If you would like a general question posted on stackoverflow, then you can (probably) provide an answer to this question [here](https://stackoverflow.com/questions/36018681/stop-seaborn-plotting-multiple-figures-on-top-of-one-another)

**Comment by mwaskom** [comment]
> If you would like a general question posted on stackoverflow, then you can (probably) provide an answer to this question here


... i did, in March 2016.
