### ISSUE TITLE
[BUG] map_dataframe removes axis labels

### ISSUE THREAD

**Issue by YannDubs** [mwaskom/seaborn#2456]
Calling `map_dataframe` on a facetgrid removes the axis labels. Reproducible example:

<img width="561" alt="Screen Shot 2021-01-30 at 00 13 07" src="https://user-images.githubusercontent.com/24327668/106336944-435e5380-6290-11eb-9cd6-f3c9e453e5f0.png">

what I assume would happen:

<img width="558" alt="Screen Shot 2021-01-30 at 00 13 02" src="https://user-images.githubusercontent.com/24327668/106336929-3b9eaf00-6290-11eb-8451-6e76e2eefe3c.png">

Code:
```python
import seaborn as sns
tips = sns.load_dataset("tips")
g = sns.relplot(data=tips, x="total_bill", y="tip", hue="day")
g.map_dataframe(lambda *args, **kwargs: 1)
```

Version: 0.11.1

**Comment by mwaskom** [comment]
This isn't exactly [unexpected](https://github.com/mwaskom/seaborn/blob/master/seaborn/axisgrid.py#L1794) but it is annoying and I think it would be reasonable for this function to have defaults that preserve existing labels rather than overwriting them with blank strings.

`map_dataframe` also doesn't try to pull `x` and `y` out of its kwargs and use them to label the axes. Getting this right all of the time is a little bit trickier but probably 95% of the time it's what one wants to happen.
