### ISSUE TITLE
bus error 

### ISSUE THREAD

**Issue by kwijik** [mwaskom/seaborn#2479]
Hi, 
I have a problem with Seaborn package. 
When I run python scripts with it, it gives a bus error. 
It was installed with pip. I tried to uninstall it and install again, but the error rests the same. 
Also I made several tests to be sure that it's exactly the Seaborn package that gives this error. 
macOs BigSur
Name: seaborn
Version: 0.11.1
Summary: seaborn: statistical data visualization

Any ideas how can I fix it?

**Comment by mwaskom** [comment]
Are you on Apple Silicon? https://github.com/mwaskom/seaborn/issues/2463

**Comment by kwijik** [comment]
@mwaskom 
Yes. 
It's the same issue, importing scipy.stats gives bus error.

**Comment by mwaskom** [comment]
I think this is the canonical scipy issue to track https://github.com/scipy/scipy/issues/13409

It seems that support for scipy on apple silicon is coming online gradually across environments. There are comments on that thread with recipes that may work for you. I don't have insight beyond that because I don't have one of those machines :)

scipy will become an optional dependency in the next major release of seaborn, but that probably won't help with the roughest part of the transition.

Going to close as upstream issue.

**Comment by kwijik** [comment]
thank you
