### ISSUE TITLE
Missing attribute lines in sns.kdeplot, but not in sns.distplot

### ISSUE THREAD

**Issue by neltacigreb** [mwaskom/seaborn#2501]
Reproducible example : 

`sns.distplot([10, 12, 13], hist=False).get_lines()[0]` --> works

`sns.kdeplot([10, 12, 13], hist=False).get_lines()[0]` --> bug

seaborn version : '0.11.0'

**Comment by mwaskom** [comment]
`kdeplot` does not have a parameter called `hist`.

**Comment by neltacigreb** [comment]
Indeed ! Thank you

**Comment by mwaskom** [comment]
Great. The explanation for the otherwise confusing error message is that `kdeplot` passes additional keyword arguments through to matplotlib's `plot` function (which in turn passes *its* keyword arguments down to the constructor of the `Line2D` artist. So by the time an error actually gets raised, there has been a loss of some context

BTW in the future, when filing a bug report, please be sure to provide the full text of the error you get (more guidelines [here](https://github.com/mwaskom/seaborn/blob/master/.github/CONTRIBUTING.md#reporting-bugs)). I had to open up a terminal and run your code to diagnose the problem, when it would have been obvious (to me) from reading the error traceback.
