### ISSUE TITLE
Please allow categorical values in `alpha`

### ISSUE THREAD

**Issue by integzz** [mwaskom/seaborn#2514]
Please allow categorical values to be mapped to the `alpha` of `scatterplot()`, in this way we can get a plot in different transparency levels for each level of a categorical feature.

**Comment by jhncls** [comment]
The use case seems a bit narrow for this to enter in seaborn soon, with a high probability of undesired side effects.  Meanwhile, you can set a palette with colors which contain alpha, as in [this stackoverflow post](https://stackoverflow.com/questions/66667334/python-seaborn-alpha-by-hue/66671457#66671457).

**Comment by integzz** [comment]
> The use case seems a bit narrow for this to enter in seaborn soon, with a high probability of undesired side effects. Meanwhile, you can set a palette with colors which contain alpha, as in [this stackoverflow post](https://stackoverflow.com/questions/66667334/python-seaborn-alpha-by-hue/66671457#66671457).

It is a very reasonable suggestion, and the post is really helpful. I have solved this problem. 

Here I post my solution as an end to this issue.

```python
import seaborn as sns
from matplotlib.colors import to_rgb

def set_color_with_alpha(color, alpha):
    r, g, b = to_rgb(color)
    return (r, g, b, alpha)

cat_list = mpg['class'].unique()
cat_num = len(cat_list)

color_dict = {}

for i in range(cat_num):
    color_dict[cat_list[i]] = set_color_with_alpha('cornflowerblue', i/10)

_, axes = plt.subplots(1, 2, figsize=(16, 8))

sns.scatterplot(data=mpg, x='displ', y='hwy', hue='class', palette=color_dict, ax=axes[0])

sns.scatterplot(data=mpg, x='displ', y='hwy', style='class', ax=axes[1])
```

**Comment by mwaskom** [comment]
I think something like this would be nice to have, but it's a very big ask: it would need to be implemented in most functions, not just scatterplot, and it would need a lot of thinking about the API (unlike ggplot, seaborn uses different parameter names for mapping variables and attributes defined by matplotlib).

Note that @jhncls's suggestion can be made even simpler, because you can import `matplotlib.colors.to_rgba` to replace the custom `set_color_with_alpha` function.

Since your specific problem is addressed and this change is not on the near–medium term roadmap, I'm going to close the issue, but that's not to say it will never get added.

**Comment by integzz** [comment]
Thank you for your reply. I agree that my problem is very specific, and it needs a lot of thinking about the API  when implementing a new feature.  Thanks for your work. Sorry for the delayed response, GitHub was blocked in my area.
