### ISSUE TITLE
[possible new feature] wide data with hue

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2519]
For casual users, long form data might seem awkward and not straightforward to generate.  Seaborn already allows some forms of wide data, for example:
```
iris = sns.load_dataset('iris')
sns.violinplot(data=iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']])
``` 
To use `hue`, a  long form is needed:
```
sns.violinplot(data=iris.melt(id_vars='species'), x='variable', y='value', hue='species')
```
But if `hue`  would be interpreted as removing that column from the dataframe and use the wide form for the remaining columns, things seem workable. (Something similar could apply to `col` and `row` in a FacetGrid).
So, the following could work in the future and be equivalent to the melted version:
```
sns.violinplot(data=iris, hue='species')
```
Probably there are consequences that I didn't see yet.

**Comment by mwaskom** [comment]
This has been discussed previously, and the core code is basically written so that this would be relatively easy to implement, but I explicitly decided against it in 0.11. The main reason is that there is a very large space of "untidy" data, and making the promise that "seaborn will tidy your data for you" feels like it is asking for trouble.

And I don't think this would consistently work for all seaborn functions. The categorical functions redundantly map the columns of a wide-form input to `hue` and `x`, so it's clear what should happen if `hue` is assigned another variable. But `lineplot` maps the columnar dimension to `hue`. What should `lineplot` do when `hue` is defined with wide-form data?

It feels important to note that I don't contrast "tidy" and "wide-form", as a lot of people do. Rather, I view the wide-form structures that seaborn accepts as [tidy with dimensional, not columnar semantics](http://seaborn.pydata.org/tutorial/data_structure.html#long-form-vs-wide-form-data). It's might be possible to define a similar systemic perspective that allows the case you mention, but I'm not sure what that would look like. I think that's the ground on which the argument would need to be made, though, rather than that casual users should be saved from needing to learn how to reshape their data.

**Comment by jhncls** [comment]
Thank you for your rigorous response.

Your logic makes sense. The only wide form data seaborn accepts is what could be considered a 2D type of dataframe, such as the result of `df.pivot()` or `df.corr()`.   If the iris example had additional columns of different types, it would be quite hard to tell seaborn what to do, except if seaborn would mimic some kind of melt operation.  Accepting a list of columns as `x` doesn't look promising either, as it would lead to confusion as to when a list would be just a list of values versus a list of column names.

`df.melt` might look unfamiliar to beginners, but that is something that can be solved by example usages. And maybe pandas comes up with related functions in the future.
