### ISSUE TITLE
[BUG]: Weirdness with `center` when using non-default colormaps

### ISSUE THREAD

**Issue by loftusa** [mwaskom/seaborn#2527]
I have code that looks like this:
```
import matplotlib
import seaborn as sns

A = np.eye(2)

fig, ax = plt.subplots(figsize=(10,10))
cmap = matplotlib.colors.ListedColormap(["white", "black"])
ax = sns.heatmap(A, cmap=cmap, ax=ax, center=0, cbar=False)
```

This code produces a heatmap that looks like this:
<img width="647" alt="Screen Shot 2021-03-27 at 11 44 35 AM" src="https://user-images.githubusercontent.com/12386450/112726069-dbc02f80-8ef1-11eb-902b-e036b3f4be28.png">

However, when I change `center` to `None`, I correctly get the heatmap that I want:
<img width="647" alt="Screen Shot 2021-03-27 at 11 45 12 AM" src="https://user-images.githubusercontent.com/12386450/112726087-e8448800-8ef1-11eb-9421-bc67ceecc42a.png">

And, interestingly, when `center` is `0` and `cmap = matplotlib.colors.ListedColormap(["white", "white", "black"])`, I get the correct heatmap again.

I'm not familiar enough with the heatmap API to know whether this is a bug, but it seems like it might be?

**Comment by jhncls** [comment]
To start, this type of questions would be much more suitable for [stackoverflow](https://stackoverflow.com/questions/tagged/seaborn).  Next, you don't explain how your data looks like, while it would be highly appreciated having a minimal reproducible example.

Let's assume your data is a very large 2D array of 0's and 1's. In that case, matplotlib will calculate `vmin` as 0 (the minimum of the data) and `vmax` as 1.  Setting `center=0`, all elements between `vmin` and `center` will be colored white and elements between `center` and `vmax` will be black.  Note that "between" here is calculated with floats, with no guarantees of what happens when a value is exactly equal to a boundary.  Therefore, it seems more sensitive to set `center=0.5`, or even better let it be None allowing matplotlib to take care.  If you want more control, you can explicitly set `vmin` , `vmax` and `center` to specific values, with `vmin < center < vmax`.

**Comment by mwaskom** [comment]
This may be a bug, so it's fine to post it here, but I agree it's impossible to say anything useful without knowing what is in your `A` array.

I'm also not sure what I would expect to happen with `center` and a `ListedColormap` with two colors, since the centering logic depends on the ability to interpolate the colormap values. Usually `center` is used when you have a continuous diverging/bipolar colormap and want the center color (i.e., white in a blue-white-red colormap) to be a value other than midway between vmin and vmax.

It might be that `center` *can't* work for, or maybe you've identified an edge case that would be good to handle better. But can't say for sure without a reproducible example and a little bit more information about what you expected to happen.

**Comment by loftusa** [comment]
@mwaskom @jhncls Updated the original post, sorry for the lack of reproducible code originally! I simplified it so that the extraneous `cbar` code is gone, and now `A = np.eye(2)`. 

I guess I'd say that when you're using something a `ListedColormap` with two colors, it'd make sense for `center` to be ignored? Or potentially just raise a `warning` that says something about how `center` doesn't really make sense to use in that case.

If you decide you want this case to be handled that way, I can make a PR!

**Comment by mwaskom** [comment]
Thanks for updating the issue!

I am still curious about what you are expecting to happen, though. I think `center` is doing the "right thing" here, it just doesn't make sense for your usecase. (And the behavior with `center` at its default value seems to produce the plot you want?)

I generally think it would add too much complexity to try and guess every degenerate usecase for the optional parameters, unless it's a case where the user is doing something that seems reasonable without detailed knowledge of the implementation.

The docs say:

> The value at which to center the colormap when plotting divergant data. Using this parameter will change the default cmap if none is specified.

The meaning of "divergent" might not be obvious if you haven't read the [color palette tutorial](https://seaborn.pydata.org/tutorial/color_palettes.html) (and, uh, it appears to be spelled incorrectly), but I'm not sure this example crosses that threshold.

**Comment by loftusa** [comment]
Close issue then?

**Comment by jhncls** [comment]
Here is some example code showing how `center` works.  It can work perfectly with a bicolored colormap, although if can be harder to understand. 
```python
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

x = np.linspace(-np.pi / 2, np.pi / 2, 100)
y = np.linspace(-np.pi / 2, np.pi / 2, 100)
x, y = np.meshgrid(x, y)
A = np.sin(x ** 2 + y ** 2) ** 2
# cmap = ListedColormap(['white', 'black'])
cmap = 'coolwarm'

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
for ax, center in zip(axes.flat, [0, 0.2, 0.5, 0.9]):
    sns.heatmap(A, cmap=cmap, ax=ax, center=center, cbar=True, cbar_kws={'ticks': np.arange(0, 1, 0.1)})
    ax.axis('off')
    ax.set_title(f'center={center:g}')
plt.tight_layout()
plt.show()
```
![image](https://user-images.githubusercontent.com/19649483/112736616-6f2a4c80-8f54-11eb-8235-f2465008fa47.png)

With only two colors:

![image](https://user-images.githubusercontent.com/19649483/112736643-9aad3700-8f54-11eb-95d1-7849e9679a1f.png)

So, setting `center=0` gets what you asked for.

**Comment by mwaskom** [comment]
Good to know. So I was wrong, there isn't a problem interpolating a discrete colormap (good!) and the "weirdness" arises from using `center` with binary (i.e. 0, and 1) data.

I think we can consider this resolved, but @loftusa if you think better documentation of the `center` parameter would have avoided this confusion I'd be happy to consider them.
