### ISSUE TITLE
Aspect ratio of axes made with FacetGrid are not consistent between multi-row and single row figures

### ISSUE THREAD

**Issue by sfailor** [mwaskom/seaborn#2529]
Seaborn version 0.12.0.dev0
Matplotlib version 3.3.4

When making figures with FacetGrid, the aspect ratio of axes changes depending on whether there are one or multiple rows. 

```
df = pd.DataFrame({'x' : np.random.random(1000),
                   'y' : np.random.random(1000),
                   'c' : np.ceil(np.random.random(1000)*2),
                   'r' : np.ceil(np.random.random(1000)*2)})

fg = sns.FacetGrid(data = df, col = 'c', row = 'r', height = 2, aspect = 1)

fg.map(sns.scatterplot, 'x', 'y')
```

Two rows

![image](https://user-images.githubusercontent.com/15325939/112770109-ecb98f80-901c-11eb-8df8-46eec615ba5a.png)

```
fg = sns.FacetGrid(data = df, col = 'c', height = 2, aspect = 1)

fg.map(sns.scatterplot, 'x', 'y')
```

One row

![image](https://user-images.githubusercontent.com/15325939/112770137-238fa580-901d-11eb-8eab-b52108923c7b.png)

The aspect ratio also appears to be incorrect in the single-row figure.

**Comment by mwaskom** [comment]
`height`/`aspect` determine the figure size and if you do `print(fg.fig.get_size_inches())` you will see that they are working properly (you get `(4, 4)` in the first case and `(4, 2)` in the second case.

But the titles/axis labels/ticklabels steal the space around the axes and, especially when the figure is small (or when the ratio of text size to figure size is large), that can distort the shape of the axes relative to the parameter you set.

This is a hard problem in general because matplotlib does not offer a way to parameterize the axes size irrespective of their decorations, and the size the figure would need to be to achieve that can't be known until after the plot has been made. See https://github.com/mwaskom/seaborn/issues/2051 for lots more thoughts (which mentions making this work better as a primary objective).

As there's not a technical bug here and the feature request is tracked in https://github.com/mwaskom/seaborn/issues/2051, i'm going to close. Feel free to continue the discussion there if you have ideas.

PS in most cases it's both easier and safer to use `sns.relplot` rather than manually combining `sns.scatterplot` and `sns.FacetGrid`.
