### ISSUE TITLE
Catplot mistaken UserWarning: Setting `sharex=False` with `color=None`

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2536]
Tested with a recent development version.

The UserWarning: "Setting `sharex=False` with `color=None` may cause different levels of the `x` variable to share colors." also comes up when the colors are assigned via a palette with a dictionary.  When there is no hue set, the dictionary gets applied to the x categories (indeed, seaborn keeps amazing).  In that case the warning should not be issued.

Example:
```
import seaborn as sns
import pandas as pd

df = pd.DataFrame({'sub': ['p1', 'p1', 'p2', 'p2', 'p3', 'p3'],
                   'bar': ['blue', 'red', 'red', 'green', 'green', 'blue'],
                   'val': [1, 2, 3, 4, 5, 6]})
palette = {'blue': "skyblue", 'red': "tomato", 'green': "limegreen"}
g = sns.catplot(kind='bar', data=df, col='sub', y='val', x='bar',
                palette=palette, sharex=False, sharey=True)
```
This generates the hoped-for plot, but with a mistaken user warning.

![image](https://user-images.githubusercontent.com/19649483/113345220-737aaf00-9332-11eb-96e3-72895604e83f.png)

(The same warning also happens when `palette=` contains a list with just one color.)

**Comment by mwaskom** [comment]
I'm pretty sure I recall that when this change went in there was a discussion that the warning was likely too have some false positives, but that avoiding them completely would be a pain and because the warning only says "may cause" it wasn't technically wrong.

In any case, the warning (and the possibility of sharing colors by default) will go away in 0.12 when categorical plots stop showing multiple colors without an explicit hue assignment.

**Comment by jhncls** [comment]
Will this example keep working in 0.12? Or will it need `hue='bar', dodge=False`?

**Comment by mwaskom** [comment]
In general it will become necessary to specify `hue` if you want multiple colors, although I think there are some situations where it can be inferred from other parameters that implicit hue mapping was being used and there will be a deprecation warning and preservation of the previous behavior. I think passing a `palette` is one of those situations. The default for `dodge` in 0.12 will become "auto" which will not dodge bars by default in the presence of `hue` if they would not otherwise overlap.
