### ISSUE TITLE
let scatterplot x and y default to 0 to make it more similar to stripplot and swarmplot

### ISSUE THREAD

**Issue by jhncls** [mwaskom/seaborn#2541]
(tested with recent dev version)

Scatterplot can be used to add extra points (e.g. outliers) to categorical plots such as violinplot and boxplot. When such a categorical plot is generated from a single x array, the y needs to be explicitly set to zero.  Without `y=0` no warning appears, but nothing is plotted.  However, swarmplot and stripplot create a compatible  plot. (x and y can be interchanged for vertical plots).

Example code:
```
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

fig, (ax1, ax2) = plt.subplots(ncols=2)
data = np.arange(10)
sns.boxplot(x=data, ax=ax1)
sns.scatterplot(x=data, ax=ax1, color='r')
# sns.scatterplot(x=data, y=0, ax=ax1, color='r')
sns.boxplot(x=data, ax=ax2)
sns.swarmplot(x=data, ax=ax2, color='r')
```

**Comment by mwaskom** [comment]
I think I'm -1 on this. Most seaborn functions (following matplotlib's convention) also return with no warning or plot when neither x or y are specified. Actually what's happening here is that the scatter is being initialized, but all points are masked. This may be useful e.g for animations. The categorical plots have a notion of a "default category", but that makes less sense for the relational plots. Also, because you could combine one of the categorical scatter plots with a box or violinplot, there is less need for `scatterplot` to work that way by default.
