### ISSUE TITLE
Feature request: Add an a second categorical variable to allow for proper three-way ANOVA plotting

### ISSUE THREAD

**Issue by MicTott** [mwaskom/seaborn#2588]
Hi, I'm a big fan of this package so first and foremost - thank you for all this hard work! 

I'm Neuroscience PhD student and Three-way ANOVAs with one repeated measure (Time) and two between-subjects variables (e.g., Virus X Sex) are very common within my field. Unfortunately, I can't find any easy way to visualize this data with Seaborn, or even across all Python packages. 

Currently you can plot a two-way ANOVA-design very easily using `pointplot()` or `catplot()`, but the only solution I can find for plotting a three-way ANOVA is [this post](https://seaborn.pydata.org/examples/pointplot_anova.html) which uses the `col= " desired variable"'. This unfortunately is not overly useful for making comparisons as one of the variables gets split into two separate plots and is not at all how we would actually visualize the data for publications. 

The ideal way to plot this data (IMO) is to have one between-subject variable differ by `hue` and the other differ by some new parameter, such as `pointshape` or `linestyle` (I would vote for point shape as the separate lines are pretty easy to distinguish).   

I know this would be a massive improvement to data visualization for a lot of people so I hope you all consider it. Thanks!

**Comment by mwaskom** [comment]
> This unfortunately is not overly useful for making comparisons as one of the variables gets split into two separate plots and is not at all how we would actually visualize the data for publications.

I strongly disagree here. I think that faceting can be *much* more effective than trying to pack too many variables into one plot. Consider this faceted 3-way interaction plot:

```python
titanic = sns.load_dataset("titanic").assign(adult=lambda x: x.age > 18)
sns.catplot(
    data=titanic, kind="point",
    y="survived", x="sex", hue="adult", col="class",
    aspect=.6,
)
```
![image](https://user-images.githubusercontent.com/315810/118527729-90ffae80-b70f-11eb-9a2a-3435c06536d4.png)

I think this pretty clearly shows how the interaction between sex and age depends on class.

It's actually currently possible to make a three-way interaction plot on a single axes, you just need to use lineplot:

```python
g = sns.relplot(
    data=titanic, kind="line",
    y="survived", x="sex", hue="adult", style="class",
    err_style="bars", err_kws=dict(lw=2.5),
    markers=True, ms=15, lw=2.5,
)
g.set(xlim=(-.3, 1.3))
g.ax.xaxis.grid(False)
```
![image](https://user-images.githubusercontent.com/315810/118528023-dc19c180-b70f-11eb-8224-dc1dfdb4d4ca.png)

I do not feel that I can make much sense of this plot. Partly that's because the points get bunched up on each other; with a different dataset, it might be easier to resolve the different trends. But shape and line style are [much harder to resolve](https://socviz.co/lookatdata.html#visual-tasks-and-decoding-graphs) than color and position. Plots like these are often going to end up as puzzles. If someone spends a lot of time poring over them, going back and forth between the plot and the legend, they'll probably get the answer they're seeking. But it's not going to jump out at them the way it will an effective visualization.

So anyway, `style` might get added to the categorical plots at some point, but I would generally caution against trying to pack too much information into one space.

**Comment by MicTott** [comment]
Of course trying to pack too much onto one plot obfuscates things, but there many use-cases here. For example, we often want to look at the slope of the lines rather than the points, and it's much easier to compare line slopes when it's all in one plot. It's also much more common that we are plotting a 2x2 rather an 3x2, which is very easy to interpret when overlaid. 

Regardless of what appears easier to you, breaking variables across separate plots is not how anyone I know prefers to visualize data such as this - especially not for publication, which is the one of the main reasons to use a pretty plotting service such as Seaborn. 

The `sns.replot()` here should be useful and I appreciate you sharing it. Perhaps it would be worth adding this to the "Three-way ANOVA" example as varying data by shape and/or line style is very often a preferred way to visualize such data. Thanks
