### ISSUE TITLE
Introduce weighted violin plots

### ISSUE THREAD

**Issue by bkmi** [mwaskom/seaborn#2589]
I have some weighted samples which could be plotted using a violin plot. There is a hacky solution for matplotlib available [here](https://gist.github.com/jquacinella/1a6341f0f1446973714c).

My impression is that I merely need to add the weights parameter when this kde estimate gets called. Is that correct? Is there a stumbling block I'm missing?
https://github.com/mwaskom/seaborn/blob/e04b07eb3df135511e71e556c2bd34ef59ba08ba/seaborn/categorical.py#L927

One thing that comes to mind: If the samples themselves are plotted on the violin plot, they will not represent the KDE since they do not show their weight. I suppose I could raise an error when the user attempts to show the samples on the plot itself.

**Comment by mwaskom** [comment]
> My impression is that I merely need to add the weights parameter when this kde estimate gets called.

scipy (as of relatively recently) supports weighted KDE estimation, so this is possible. But I think you are underestimating what would be required to achieve it, because you'll need to thread the weights vector through all of the logic that groups the subsets of rows by the categorical variable (and, optionally, the hue variable). You'd also need to modify the code that parses the input arguments so that `weights` could be supplied as the name of a column in an input dataframe or as a vector. The categorical plots were not written in a way that anticipates other variables coming "along for the ride", so that will be fairly difficult.

Nevertheless, it will become possible at some point, as part of the work in #2429 and  #2112.

Note that is is currently possible with `kdeplot`/`displot(..., kind="kde")`.

> One thing that comes to mind: If the samples themselves are plotted on the violin plot, they will not represent the KDE since they do not show their weight. I suppose I could raise an error when the user attempts to show the samples on the plot itself.

Yes, each new feature raises a number of questions. Should there be an error? I'm not sure. Maybe it's reasonable to show the position of the datapoints where the density was derived from, even if they don't correspond to "observations". Maybe someone will ask to modify the size of the points or the width of the lines to reflect the weights. Things are rarely as simple as they seem :)

**Comment by bkmi** [comment]
Hmm, yes I see. Perhaps it makes more sense to include this feature only after the issues you mentioned are implemented. (If that indeed makes implementation easier.)

**Comment by mwaskom** [comment]
Yes, definitely not going in before then, but it's part of the roadmap. Going to close as it's tracked by those issues.
