### ISSUE TITLE
scaling in split violin plots - scale by count and area together

### ISSUE THREAD

**Issue by CompRhys** [mwaskom/seaborn#2602]
seaborn currently gives us the option to scale by area or scale by count on split violin plots. Scaling by count lets us compare the sizes of the different distributions between groups but this throws off the density comparisons within the split violin. Ideally, we would be able to scale by area within a group and by counts between groups giving the best of both worlds for split violin plots.

**Comment by CompRhys** [comment]
maybe related to #962

**Comment by mwaskom** [comment]
Do you have an example of a plot that you find unsatisfactory?

My initial reaction is that designing a sane API to allow this will prove challenging.

**Comment by CompRhys** [comment]
![image](https://user-images.githubusercontent.com/26601751/122760179-bc3b6780-d292-11eb-8676-7deb7a372045.png)

In this plot I find the comparison in batch 3 jarring as the density comparison within the groups is hard to make but I also want to convey the sizes of the different batches

**Comment by CompRhys** [comment]
![image](https://user-images.githubusercontent.com/26601751/122760795-6c10d500-d293-11eb-9f5b-b17f1337b1e9.png)

This is the equivalent plot scaled by area which is visually clearer within groups but no longer indicates the relative size of groups

**Comment by mwaskom** [comment]
I think you can make the plot you want by doing, basically:

- compute the relative proportion of each x variable
- loop over the x variables and plot each separately, passing `order` so they go in the right place
- set the `width=` parameter by `relative_prop * .8` and otherwise scale by area.

I still don't really see a good way to parameterize this in `violinplot`.

Additionally, as a meta-point, I think it's wise to avoid cramming too much information into one plot when you can make multiple plots. What about a (potentially shorter) subplot under this one with a histogram/countplot showing the number of observations in each violin?
