### ISSUE TITLE
get_lines() seems to have stopped working on certain versions of seaborn

### ISSUE THREAD

**Issue by bakermoran** [mwaskom/seaborn#2612]
Using this code, we should get a list of one line. I've tried with both `.get_lines()` and `.lines`, which return `<a list of 0 Line2D objects>` and an empty array respectively. I found that it correctly returns the line on version `0.10.1` (and potentially earlier) and it does not return correctly on _at least_ `0.11.0` and `0.11.1`.

```import seaborn as sns
from scipy import stats
lift = stats.beta.rvs(70, 30, size=1000)
ax = sns.kdeplot(lift, shade=True)
lines = ax.get_lines()
print(lines)```

**Comment by mwaskom** [comment]
`.get_lines` is a method on a matplotlib axes object, i wouldn't think of it as "stopped working" but rather there are no lines to return when drawing a `kdeplot` with `shade=True` on 0.11+. It will do what you expect with `shade=False`. Please note that the specific artists that seaborn adds are not considered part of the formal API and are subject to change without warning (simply because there's no non-intrusive way to provide a warning), although there is a higher bar for changing them than for other non-public changes, because they can be disruptive.
