### ISSUE TITLE
Feature request: add generalized pairs plot

### ISSUE THREAD

**Issue by Abdelgha-4** [mwaskom/seaborn#2653]
It would be super useful to have a pair plot that support both categorical and numeric variables and offer the appropriate type of plots to each combination of variables.
Basically, it should mimic **[GGally::ggpairs](https://ggobi.github.io/ggally/reference/ggpairs.html)** function from R.
Here is a simple example of what it can do:
![image](https://user-images.githubusercontent.com/72174073/131769006-05e9921d-d39c-41fe-955c-db0ebb880094.png)
Please refer to the link for more examples of use cases.

**Comment by mwaskom** [comment]
Hi, thanks for the suggestion. I think this is out of scope for seaborn currently, but (much like how ggpairs is not actually part of ggplot) I don't think there's anything restricting a third-party package from building it on top of `PairGrid`.

**Comment by mwaskom** [comment]
I do think it's possible that features similar to this could be added once #2429 is wrapped up and "categorical" plots can be more easily mixed with other plots. Probably that would take the form of using `stripplot` to represent categorical/numeric pairings.

Personally I think the full generalized pair plot that is shown above violates the principle of "small multiples" which is that you should use the same visualization in each subplot so that your eye can easily detect patterns or violations of patterns. But I do think this is something that could be built on top of seaborn if they are interested in developing a good API and maintaining it.
