### ISSUE TITLE
Error when trying to visualize diverging palette

### ISSUE THREAD

**Issue by Gonzalo933** [mwaskom/seaborn#2654]
When trying to visualize a custom diverging palette, the following error is raised:

```
import seaborn as sns
sns.palplot(sns.diverging_palette(220, 20, as_cmap=True))
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-16057584e5f1> in <module>
      1 import seaborn as sns
----> 2 sns.palplot(sns.diverging_palette(220, 20, as_cmap=True))

~/anaconda3/lib/python3.7/site-packages/seaborn/miscplot.py in palplot(pal, size)
     18 
     19     """
---> 20     n = len(pal)
     21     f, ax = plt.subplots(1, 1, figsize=(n * size, size))
     22     ax.imshow(np.arange(n).reshape(1, n),

TypeError: object of type 'LinearSegmentedColormap' has no len()

```
Other palettes work just fine:

```
sns.palplot(sns.color_palette("husl", 8))
```

works without any errors and the palette is plotted.

Using seaborn `0.11.1` and `0.11.2` and I tried inside jupyter notebook and in the terminal and the behaviour is the same

**Comment by mwaskom** [comment]
You're seeing that because you have `as_cmap=True`, so the function is returning a matplotlib colormap object rather than the list(-like object) of colors that `palplot` expects. It could probably give a more helpful error message. Although these days it's not especially necessary to use `palplot`, since if you're in a jupyter notebook, simply returning either a seaborn "color palette" list or a matplotlib colormap object will show a rich view in the cell output:

![image](https://user-images.githubusercontent.com/315810/132071001-86a6acab-4aad-41db-8f01-b967c496ae0f.png)

**Comment by mwaskom** [comment]
I'm going to close as this is working as expected and as documented:

>    Parameters
> >   pal : sequence of matplotlib colors

The error message could be more helpful, but it is the correct exception class.

I would be open to a PR improving the error message for this specific case, and perhaps enhancing `palplot` to render a continuous gradient when passed a matplotlib colormap. But given the existing rich display functionality demonstrated above, it's not a priority for ongoing work.
