### ISSUE TITLE
ValueError: The palette list has the wrong number of colors.

### ISSUE THREAD

**Issue by moi90** [mwaskom/seaborn#2662]
Given a DataFrame with two categories:

```python
df = pd.DataFrame({"a": [1,2,3,4,5,6,7,8,9,10], "b": ["a", "b", "a", "b", "a", "b", "a", "b", "a", "b", ]})
```

When I provide a palette with `lineplot`, I get an error:

```python
sns.lineplot(data=df, x="a", y="a", hue="b", palette=sns.color_palette())

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-4e6a1a2e63cf> in <module>
----> 1 sns.lineplot(data=df, x="a", y="a", hue="b", palette=sns.color_palette())

/data1/mschroeder/miniconda3/envs/20-assdc/lib/python3.7/site-packages/seaborn/_decorators.py in inner_f(*args, **kwargs)
     44             )
     45         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 46         return f(**kwargs)
     47     return inner_f
     48 

/data1/mschroeder/miniconda3/envs/20-assdc/lib/python3.7/site-packages/seaborn/relational.py in lineplot(x, y, hue, size, style, data, palette, hue_order, hue_norm, sizes, size_order, size_norm, dashes, markers, style_order, units, estimator, ci, n_boot, seed, sort, err_style, err_kws, legend, ax, **kwargs)
    696     )
    697 
--> 698     p.map_hue(palette=palette, order=hue_order, norm=hue_norm)
    699     p.map_size(sizes=sizes, order=size_order, norm=size_norm)
    700     p.map_style(markers=markers, dashes=dashes, order=style_order)

/data1/mschroeder/miniconda3/envs/20-assdc/lib/python3.7/site-packages/seaborn/_core.py in map(cls, plotter, *args, **kwargs)
     51         # This method is assigned the __init__ docstring
     52         method_name = "_{}_map".format(cls.__name__[:-7].lower())
---> 53         setattr(plotter, method_name, cls(plotter, *args, **kwargs))
     54         return plotter
     55 

/data1/mschroeder/miniconda3/envs/20-assdc/lib/python3.7/site-packages/seaborn/_core.py in __init__(self, plotter, palette, order, norm)
    117                 cmap = norm = None
    118                 levels, lookup_table = self.categorical_mapping(
--> 119                     data, palette, order,
    120                 )
    121 

/data1/mschroeder/miniconda3/envs/20-assdc/lib/python3.7/site-packages/seaborn/_core.py in categorical_mapping(self, data, palette, order)
    202                 if len(palette) != n_colors:
    203                     err = "The palette list has the wrong number of colors."
--> 204                     raise ValueError(err)
    205                 colors = palette
    206             else:

ValueError: The palette list has the wrong number of colors.
```

With `pointplot`, this works fine (it uses the first two colors of the provided palette):

```python
sns.pointplot(data=df, x="a", y="a", hue="b", palette=sns.color_palette())
```

I think the behavior of `pointplot` is the correct one.

**Comment by mwaskom** [comment]
> I think the behavior of pointplot is the correct one.

I'm open to the conclusion that the exception is more obtrusive than useful (and would like to move towards more consistency across functions) but is there a reason you think it's *incorrect*? Calling `sns.color_palette()` with no arguments will (in most cases) produce 6 colors, and as you say your `hue` variable has 2 categories.

Also this example (which is simple and reproducible — thanks!) may not be what you're actually doing, but generally there's no reason to do `palette=sns.color_palette(...)`. Just provide `palette=arg` and it will internally pass it to `color_palette` with the correct number of colors specified.

**Comment by moi90** [comment]
My use case is that I want to use one distinct color for the first category and the colors of a palette for the remaining. Therefore I do `palette = ["k"] + list(sns.color_palette())`.

I think the behavior of `lineplot` is in fact incorrect. I would expect that when `palette` parameter receives a list, these colors are *available* for free use (like in `pointplot`), not bound 1:1 to the categories in the data (then, I would use a mapping).

The other way around, the behavior of `pointplot` is not incorrect and much more flexible.

**Comment by mwaskom** [comment]
But again why is that *incorrect*?

**Comment by moi90** [comment]
> You are in fact passing a different number of colors than you have categories, no?

Yes, I am. OK, so maybe it is not *incorrect*, but it is certainly an annoyance. But why argue? As you said, it is helpful in itself to have consistent behavior between functions. And here, the the palette behavior of `pointplot` is a superset of the behavior of `lineplot`, but much more flexible.

**Comment by mwaskom** [comment]
> But why argue?  

Because there is always more to do in open source than there is time to do it, so it is important to be clear for the purposes of prioritization. Also, because issues that confuse "this is incorrect because it does not work as intended" and "this is incorrect because it does not work as i would prefer" are an irritation that, over time, drains one's interest in working on any of them.

In any case,

> And here, the the palette behavior of pointplot is a superset of the behavior of lineplot, but much more flexible.

I don't agree. First, I think you're overstating the apparent limitation. You're already making a custom list, all you need to do is add one parameter so that it has the correct number of colors.

Second, the error is strict but also prevents you from making unintended mistakes. In *your particular case* it appears that you are not at risk of problems but if you were passing a color list that had *fewer* distinct values than you needed, it would have to cycle and you'd get a plot that can't be clearly deciphered. And if you were using a gradient color palette, taking the first few colors would give you less contrast than you'd get if you generated the palette with the right length to begin with:

```python
f, axs = plt.subplots(1, 2)
pal = "viridis"
sns.lineplot(data=tips, x="day", y="total_bill", hue="smoker", palette=sns.color_palette(pal)[:2], ax=axs[0])
sns.lineplot(data=tips, x="day", y="total_bill", hue="smoker", palette=pal, ax=axs[1])
f.tight_layout()
```
![image](https://user-images.githubusercontent.com/315810/133771352-3f87f190-f4de-4787-b945-9d1051888271.png)

Again I am *open* to the idea that the error is too constraining and that this should be at most a warning. But there are considerations that you might not have thought of because they don't bear on your very specific usecase.

**Comment by moi90** [comment]
OK, thank you for looking into this! You are probably right that the current behavior prevents mistakes. Indeed, I now set up my palette with the correct number of colors from the beginning. Initially, this was thought as a work-around, but reading your arguments, I think this is actually the correct thing to do, especially when using a gradient palette.

So: Should `pointplot` maybe adopt the palette behavior of `lineplot` instead, to increase consistency and to prevent unwanted cycling and reduced contrast?

**Comment by mwaskom** [comment]
I definitely agree that it would be ideal if all functions used the same rules for handling (and error-checking) their inputs. Currently `lineplot` and `pointplot` don't go through the same code path, and the path forward there is to refactor the internals of the categorical plots so that they can (#2429).

As for how to handle cases like these, I think I am currently leaning towards saying that there should be an informative warning when a `len(palette) != len(hue_levels)`, rather than an error. That will need to be the case anyway for the categorical plots, at least temporarily, because we can't just flip a switch and make inputs that used to be happily accepted error (unless a strong case could be made that that behavior was buggy).

**Comment by Ebony-Watson** [comment]
Currently experiencing this same scenario. The work-around you created assumes that we are always aware of the number of hue levels present within a dataframe. In my case, I was hoping to creating line plots for dozens of dataframes at a time, where I know the maximum number of potential hue_levels, but each dataframe is filtered to only include significant levels. As such the number present within each dataframe is not consistant. Not expecting a fix or solution here, just wanted to bring up another case where lineplot having the same functionality as pointplot would be conveniant.

**Comment by mwaskom** [comment]
I don’t understand … at the time you are calling lineplot you have access to the specific dataframe you are feeding it … why can’t you get the number of unique hue levels at that point?

Alternatively, pass a dictionary with all possible mappings your want to use (it will error if a level is missing from a dictionary palette but not if the dictionary has entries that don’t appear in the data, I am pretty sure. 

Or set whatever custom palette you want to use as the default and then don’t worry about passing one for each plot.
