### ISSUE TITLE
Jointplot doesn't return handles and labels

### ISSUE THREAD

**Issue by ISipi** [mwaskom/seaborn#2677]
I noticed that when using 

`g = sns.jointplot(data=data, x="X", y="Y", hue="Group", kind="kde")`

we don't get handles or labels when using
`print(g.ax_joint.get_legend_handles_labels())` 

However, removing the "kind" keyword does print handles and labels - it doesn't matter what you insert as the input to "kind", but it always seems to override the handles and labels from "hue". Is there an easy fix for this?

**Comment by mwaskom** [comment]
I assume you want this data because you want to move the legend. (It can be helpful when opening an issue to provide context about what you're trying to do beyond the specific operation that isn't working). If that's the case I'd refer you to [this issue](https://github.com/mwaskom/seaborn/issues/2280).

Otherwise, this is not a bug from my perspective (nor does it have anything to do with `jointplot`, really): `kdeplot` does not add labeled artists to the axes, and that's what gets used when you specify `kind="kde"`.

If you're trying to do some customization other than moving the legend it may be better to ask on stackoverflow.
