### ISSUE TITLE
catplot with points throws error when more than one categorie is skipped

### ISSUE THREAD

**Issue by marcschulze** [mwaskom/seaborn#2682]
this is minimal working sample
```
import seaborn as sns
import pandas as pd

tmp = pd.DataFrame(data={
    'timestamp': [pd.to_datetime('1.1.2019'), pd.to_datetime('1.1.2020'), pd.to_datetime('1.1.2021'), pd.to_datetime('1.1.2021')],
    'scene': ['s1', 's1', 's1', 's1'],
    'algo': ['a1', 'a2', 'a3', 'a4'],
    'std': [0.1, 0.2, 0.3, 0.4],
})
sns.catplot(x="timestamp", y='std', hue="algo", col="scene", kind="point", data=tmp)
```

so when i change the year 2019 to 2020 its working, otherwise it throws an RGBA error:
```
ValueError: Invalid RGBA argument: 0.12156862745098039
```

**Comment by mwaskom** [comment]
Thank you for sharing a reproducible example — though I am able to run it without issues on my setup:

![image](https://user-images.githubusercontent.com/315810/138191175-63eefb52-4357-4869-8f72-89771beeaab9.png)

(That said, it doesn't look great because `catplot` doesn't understand date objects — you'll want to format those into nice strings before passing to `catplot`).

Could you please share the versions of seaborn and matplotlib that you are using?

**Comment by marcschulze** [comment]
Thanks for your quick reply and you are right.
With:
```
g = sns.catplot(x="timestamp", y='std', hue="algo", col="scene", kind="point", data=tmp)
for ax in g.axes.flat:
    ax.set_xticklabels([pd.to_datetime(pd.to_datetime(tm.get_text()), unit='ms').strftime(
                '%Y-%m-%d\n %H:%M:%S') for tm in ax.get_xticklabels()], rotation=45)
```
it looks much better ;)
Anyway, my versions are:
pandas => 0.11.2
matplotlib => 3.3.4
and I'm working with Python 3.6.8

**Comment by marcschulze** [comment]
thanks for this useful tip.
