### ISSUE TITLE
Update boxplot documentation

### ISSUE THREAD

**Issue by byersiiasa** [mwaskom/seaborn#2697]
Matplotlib boxplot now accepts a tuple of percentiles to `whis` - and this needs to be updated in the boxplot documentation. 

I couldn't find where this is done in the repo - hence a little message for you here.

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html
https://seaborn.pydata.org/generated/seaborn.boxplot.html

**Comment by mwaskom** [comment]
Sorry what is the issue? Why does a change in matplotlib require a change in the seaborn documentation? Did something break?

**Comment by byersiiasa** [comment]
if I understand correctly seaborn boxplot uses matplotlib boxplot in the backend?

If yes - matplotlib boxplot now accepts "a pair of floats, they indicate the percentiles at which to draw the whiskers (e.g., (5, 95)). In particular, setting this to (0, 100) results in whiskers covering the whole range of the data." It sees this also works on seaborn boxplot too.

If so - would be useful to update the seabon docs so that users are aware of this functionality...?

**Comment by mwaskom** [comment]
If this is a recent change in matplotlib then seaborn should not advertise it to everyone, because it will not work for people using older versions of matplotlib. Better to be minimal and correct than expansive and wrong. But please, it would be more helpful when raising this sort of issue to provide as much detail as possible so that maintainers don't have to spend time trying to understand what you are talking about. i.e. if matplotlib "now" accepts it, what version did it change in? If you can't locate the source, at least copy exactly what it says rather than linking to a long web page, etc.

----

In general seaborn, doesn't document parameters that are just passed through to matplotlib, precisely because you can end up in situations like this. I think `whis` is a special case because the parameterization is confusing/non-obvious and it felt helpful to explain it in a salient place. If there's going to be any change, it should probably be to revert that and to explain the whisker rules somewhere else (i.e. a "notes" section).
