### ISSUE TITLE
Boxenplot fliersize ?

### ISSUE THREAD

**Issue by agamemnonc** [mwaskom/seaborn#2701]
Hi, is it possible to change `fliersize` in `boxenplot`, as in `boxplot`?

**Comment by mwaskom** [comment]
Unfortunately not; unlike with `boxplot` there's no single underlying matplotlib function to pass `kwargs` for; they're passed to the patches as those make up the main part of the plot.

You could either:
- Temporarily modify the default marker size (`with plt.rc_context({"lines.markersize": 2}): ...`)
- Modify the artist properties after plotting `plt.setp(ax.collections[::2], sizes=[2 ** 2])`

I think this would be a good feature if you want to add it. It should probably be a `flier_kws` option rather than `fliersize` because people might want to change other parameters (shape, etc.)  too.

**Comment by agamemnonc** [comment]
Thanks @mwaskom. Sure, I would be happy to work on a PR on this (and might need some guidance along the way).

Am I right in assuming the second approach would be preferable for supporting this feature?

**Comment by mwaskom** [comment]
> Am I right in assuming the second approach would be preferable for supporting this feature?

Not sure what you mean by "second approach"?

**Comment by agamemnonc** [comment]
I mean using `plt.setp(ax.collections[::2], sizes=[2 ** fliersize])` as opposed to `with plt.rc_context({"lines.markersize": fliersize}):`

Or did I perhaps misunderstand and these two approaches are just suggested as temporary workarounds, and you had sth else in mind for properly addressing this issue? Please let me know.

**Comment by mwaskom** [comment]
Right, those are both workarounds for users who can only interact with the matplotlib figure object that seaborn creates. Inside the function, you can pass the dictionary of `flier_kws` to the `scatter` call that draws the outliers.

Actually looking at the code a little bit, the situation with `kws` is messier than I thought, because `kws` is passed to both `plot` (to draw the medians) and `scatter` to draw the outliers, with no ability to tweak the appearance of the boxes externally.

So ideally, there would be three new parameters:
- `box_kws`
- `line_kws`
- `flier_kws`

And they would each be dispatched to the right place.

Two other pieces of guidance for how to make this change:

- You should add the plotting parameters that are currently passed to each function (like the flier shape) to the kws dictionary using `.setdefault` so that users can override the defaults if desired.
- You don't want to mutate the user's dictionary when you do that, so you need to copy the kwargs dicts first.

**Comment by EitanHemed** [comment]
@mwaskom and @agamemnonc, i see that this issue is still open. Would you mind if i took a stab at this?

**Comment by agamemnonc** [comment]
@EitanHemed pls go ahead, I haven't managed to find time to work on this unfortunately.

**Comment by mwaskom** [comment]
Closed with #2909

**Comment by ianrinehart** [comment]
Hey, it looks like the flier_kws dictionary cannot be passed to sns.catplot with kind='boxen'. It seems like this was the goal for this issue, but it looks like this isn't working. I've been trying to figure this out for a while. Am I missing something?

`    g = sns.catplot(data=df,
                    x = "category",
                    y = "observed",
                    aspect=2.2,
                    orient='v',
                    kind='boxen',
                    palette=['#6929c4',
                                '#005d5d',
                                '#fa4d56',
                                '#198038',
                                '#ee538b',
                                '#009d9a',
                                '#8a3800',
                                '#1192e8',
                                '#9f1853',
                                '#570408',
                                '#002d9c',
                                '#b28600',
                                '#012749',
                                '#a56eff'],
                    flier_kws={
                        's':5,
                        'marker':'o',
                        'alpha' : 0.75
                    }
                    )`

produces the error:

`AttributeError: Line2D.set() got an unexpected keyword argument 'flier_kws'`

Am I using this wrong?
