### ISSUE TITLE
Feature request: sns.pairplot(style=...)

### ISSUE THREAD

**Issue by sorenwacker** [mwaskom/seaborn#2703]
I would love to have a style argument similar to to relplot that changes the style for the markers in the scatter plot. I know I can change that by providing markers.

    sns.pairplot(penguins, hue="species", markers=["o", "s", "D"])

However, that assumes I know how many groups I have in my dataframe and that I know the palette of marker symbols available. 

While `sns.relpot(..., style='my-favorite-column'`, is much more convenient.

**Comment by mwaskom** [comment]
This can't work because the plots used for the diagonal don't currently support `style`. But as long as you don't care about also conditioning the diagonal marginals on the style variables (or are using the same column for hue and style), you could do

```python
sns.pairplot(df, hue="species", plot_kws=dict(style=df["sex"]))
```
![image](https://user-images.githubusercontent.com/315810/143587126-7df590a0-ded0-41f8-af80-81d4192761f1.png)

**Comment by sorenwacker** [comment]
Oh, that should work. I tried the style argument in `plot_kws`, but did only provide a string, i.e. the name of the columns. That did not work.
Thank you!
