### ISSUE TITLE
[Bug] Line not showing in pointplot when using palette argument

### ISSUE THREAD

**Issue by harmbuisman** [mwaskom/seaborn#2706]
Seaborn, matplotlib versions: ('0.11.2', '3.4.3')

```
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
data = pd.DataFrame({'x': {0: 2000, 1: 2001}, 'y': {0: 1, 1: 2}})
sns.pointplot(x='x', y='y', data=data,  palette=['blue'], title='color via palette')

plt.show()
sns.pointplot(x='x', y='y', data=data,  color='blue'); 
```

The code above outputs the following two plots. My expectation is that they would be the same, but in the case where the color is specified by the palette argument, there is no line:
![image](https://user-images.githubusercontent.com/7702207/143836083-7b3c2bef-7eeb-4c0e-96ca-deaa5c37f0ee.png)
![image](https://user-images.githubusercontent.com/7702207/143836096-7092e68c-f5e3-4ec4-89c6-d8e3210d5f29.png)

**Comment by mwaskom** [comment]
This is by design. Normally you would pass a `palette` because you want to show each category in _different_ colors, so they can't be (or wouldn't be, given the way `pointplot` works — they're entirely separate underlying plots)  joined. There's no special check for whether the palette contains a single unique color, because that's redundant with passing `color=`. Is a reason you want to to it the first way, when the second way works?

FWIW the implicit hue mapping in the categorical plots is a little confusing and in 0.12+ it will be necessary to explicitly assign `hue=` to get multiple colors (although there will be backwards compatibility that preserves this particular behavior for a release cycle, because you are "asking for" multiple colors in a (semi-)explicit way).

**Comment by harmbuisman** [comment]
hi Michael, thanks for the quick response. I have a general purpose plot function that wraps around the pointplot method where I pass the palette such that it always uses the same colors. In the case where hue is not specified it passes both color and palette. So the call becomes:

sns.pointplot(x='x', y='y', data=data, palette=['blue'], color='blue'); 

I just noticed that this call also goes 'wrong' and plots without the line. 

It seems that there is some logic that uses palette to determine whether the data is categorical rather than hue.  Judging from your remark this would lead to a warning in future if you have a palette but no hue? 

To me the current behaviour was unexpected as I would have expected a palette to be just a source of colors, not a definition of what the data looks like. So I thought it was a bug. 

Thanks to your comment I can workaround by forcing palette to None if hue is None.

**Comment by mwaskom** [comment]
> I just noticed that this call also goes 'wrong' and plots without the line.

`palette` supersedes `color` to support using it in a `FacetGrid` (which always passes `color`).

> It seems that there is some logic that uses palette to determine whether the data is categorical rather than hue. 

I'm not sure what you mean here. The `x` (or `y` for a horizontal plot) variable is _always_ treated as categorical. But if you're passing a `palette`, it assumes you wanted distinct plots. The relevant code is [here](https://github.com/mwaskom/seaborn/blob/v0.11.2/seaborn/categorical.py#L1664-L1666).

> Judging from your remark this would lead to a warning in future if you have a palette but no hue?

Correct, and then in a subsequent release it will stop working (it will start just ignoring `palette`, like other functions do without `hue` assigned).
