### ISSUE TITLE
Rotating xticks with get_xticklabels doesn't work in scatterplot

### ISSUE THREAD

**Issue by jankaWIS** [mwaskom/seaborn#2717]
Why does the following snippet not work, why is the `get_xticklables()` empty in scatterplot but works in other plots, eg. barplot?

```python
import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

g = sns.scatterplot(data=tips, x="day", y="tip")

g.set_xticklabels(g.get_xticklabels(), rotation=40, ha="right")

print(g.get_xticklabels())
#[Text(0, 0, ''), Text(1, 0, ''), Text(2, 0, ''), Text(3, 0, '')]
```
![image](https://user-images.githubusercontent.com/54404810/147469705-2d1cd115-a61a-4b3a-904a-3393a35ba798.png)

It also produces this warning:
```
/var/folders/bx/tb4883l53hdd3zp2y0nyy_4m0000gp/T/ipykernel_82932/119844259.py:9: UserWarning: FixedFormatter should only be used together with FixedLocator
  g.set_xticklabels(g.get_xticklabels(), rotation=40, ha="right")
```

As I said, this works fine:
```python
g = sns.barplot(x="day", y="total_bill", data=tips)

g.set_xticklabels(g.get_xticklabels(), rotation=40, ha="right")
```

![image](https://user-images.githubusercontent.com/54404810/147469714-cf6dfede-f9c6-47da-abbd-7f705584f8d1.png)

Having:
```
seaborn 0.11.2
pandas  1.2.4
numpy   1.19.1
matplotlib 3.4.2
```

**Comment by mwaskom** [comment]
This is a matplotlib thing; the tick labels are populated lazily and might not be available when you call `ax.get_{x,y}ticklabels`. If you search on their github there's an open issue discussing whether they should force a draw when you call it so that you don't get this surprising result.

Also if you read the docstring for `set_{x,y}ticklabels`, it says:

``` 
.. warning::
    This method should only be used after fixing the tick positions
    using `.Axes.set_xticks`. Otherwise, the labels may end up in
    unexpected positions
```

But because `get_{x,y}ticklabels` returns tick objects, not strings, you can still modify the properties before the actual labels are assigned:

```
ax = sns.scatterplot(data=tips, x="day", y="tip")
plt.setp(ax.get_xticklabels(), rotation=40, ha="right")
```

should work.

**Comment by jankaWIS** [comment]
Thanks :)
