### ISSUE TITLE
 [suggestion] Accept custom regression models

### ISSUE THREAD

**Issue by c-torre** [mwaskom/seaborn#2734]
Hi! I've spent a lot of time using `lmplot` and `regplot`, and I wonder if it's possible to give customized fitted models as an argument at all. I'm not sure if there's a technical reason that makes it impossible, but here it goes the proposal:

## Why?

1. While intended for prototyping, the regression functions are quite powerful. Still, they can only be used with very few models, meaning that prototyping itself is limited.
2. Moreover, while I greatly appreciate the effort that went to it, it's still weird to me that Seaborn handles model fitting logic and adds effort to maintainers to make sure every model works. Also, this effort probably means that less models finally go into Seaborn.
3. [Extra] The question about getting model parameters back from Seaborn's trained models pop ups frequently (I even had it myself before checking other issues). The reason why this is impossible makes a lot of sense but it's not intuitive a priori. However, if the user can/must provide the model, this issue could be mitigated/eliminated.

## What?

1. [Primary] Add a "model" argument to `lmplot` and `regplot` which accepts an object that implements a `predict` method, called internally.
2. [Secondary] Remove all model-fitting logic from Seaborn. As a result, also remove all `lmplot` and `regplot` arguments that specify the model (e.g., `logistic`).

## Example

User:

```
model = TweedieRegressor().fit(X, y)
g = sns.lmplot(x="X", y="y", data=data_df, model=model)
```

Seaborn:

```
... model.predict(grid)
```

Thanks!

**Comment by mwaskom** [comment]
Say you have
```
sns.lmplot(data=df, x="x", y="y", hue="cond_a", col="cond_b")
```
What do you pass to `model`? One model? Dictionary of models keyed by the cartesian product of unique `cond_a` and `cond_b` values? The latter is closer to how `lmplot` works but is probably not how you have set up the model, i.e. you might have done something like 
```
y ~ x + cond_a + cond_b
```
or even 
```
y ~ x * cond + cond_b
```

So it is not as simple as 
```
model.predict(grid)
```
because seaborn is going to need to know how to construct the design matrix for your model, including proper dummy-coding etc, appropriately substituting the evaluation grid for the variable that ends up as `x` in the plot.

That might be possible if you used the formula interface (which is not what you are doing in your example), but by the time seaborn gets to the statistical transformation, the columns of the internal dataframe are named with the plot variables (`x`, `y`, etc.) rather than the external names that the model object would know about, so that mapping would need to be inverted, something there's no existing infra for.

And what happens if your model has additional terms that aren't included in the plot spec?

Those are just some initial thoughts about the complications that come to mind with the proposal.

---

Basically, the role of models in exploratory data visualization is very different from the role of visualization in model evaluation, and I don't think one function can serve both purposes. It's not impossible to design tools for generating visualization of predictions from arbitrary models that implement some sort of `predict` interface, but I am sure that both the API and internals would look different from seaborn.

---

> While intended for prototyping, the regression functions are quite powerful. Still, they can only be used with very few models, meaning that prototyping itself is limited ... Also, this effort probably means that less models finally go into Seaborn.

That's quite fine with me. Offering a comprehensive library of statistical models is not a design objective of seaborn; seaborn is primarily oriented towards supporting exploratory data analysis and hypothesis generation.

And IMO once you get down to serious model evaluation, the kind of plots that `regplot`/`lmplot` create are not that helpful anyway; you should be doing things like looking at marginal distribution / autocorrelation of residuals, comparing goodness-of-fit and parameter estimates from different models, and other things that seaborn is pretty good at.

**Comment by mwaskom** [comment]
That said, you may be aware that there is some [new functionality](http://seaborn.pydata.org/nextgen/) in development, which should make the minimum-helpful response to this kind of question "define your own `Stat` plugin to what you want" and, uh, apparently that won't be very hard:

![image](https://user-images.githubusercontent.com/315810/151375592-2c8f2c01-8850-4372-af03-eccf9c0336f3.png)

Closing for now, though, as simply adding a pre-fitted `model=` parameter to `lmplot` is very likely not going to be possible/desirable.

**Comment by c-torre** [comment]
Thanks for the long reply. Indeed, there seem to be many problems that would difficult the proposal. Moreover, I don't have enough knowledge of seaborn internals to argue against most key points. It still feels counter-intuitive why a) regression model parameters cannot be returned, b) only a few models are available, and c) why seaborn implements model fitting in the first place. 

Perhaps proposal could be re-thought to improve the docs, even if to only...

1.  ...add a sentence or two to https://seaborn.pydata.org/tutorial/regression.html
2. ...and perhaps a sentence or a warning to the three https://seaborn.pydata.org/api.html#regression-plots
3. A longer explanation in the FAQ.

(I was still typing my reply when this issue was closed)

Cheers, new functionality also looks promising.

**Comment by mwaskom** [comment]
> ...add a sentence or two to https://seaborn.pydata.org/tutorial/regression.html

I am pretty sure that the second paragraph of this tutorial makes exactly these points?

**Comment by c-torre** [comment]
True for the tutorial. Still, adding "See why parameters are not returned and model selection is limited in the [FAQ](https://github.com/mwaskom/seaborn/wiki/Frequently-Asked-Questions-(FAQs))" (#2672)  -- or similar -- as my 2nd previous point would perhaps help.
