### ISSUE TITLE
Connected dots on box plot

### ISSUE THREAD

**Issue by AdrienTassou** [mwaskom/seaborn#2747]
![image](https://user-images.githubusercontent.com/97636189/155352952-a371142b-7d65-49f0-9703-93439610e4ad.png)

Hello,

I am having issues in trying to connect dots together in a boxplot. As you can see on the table, there are mice in the 'bsl' condition that correspond to mice in the '30min' condition (same mouse number). Is there a way I could connect these dots together? 
This is what I have been trying so far but I was not able to make the lines aligned to the dots. 

I hope you can answer my first issue on github! 
Thank you,
Adrien

**Comment by mwaskom** [comment]
I don't think there's an easy way to accomplish this ... `pointplot` can dodge like a categorical plot but does not have a `units` parameter. You could define the x positions of the lineplot for each observation manually (i.e [0, 1] +/- 0.2). That said, my advice is that the resulting plot is going to be very busy and hard to process. I think you'd have more success making a faceted plot by mapping the genotype variable to `col` rather than `hue`. Just a suggestion, though.
