### ISSUE TITLE
kdeplot raising LinAlgError("singular matrix") instead of warning

### ISSUE THREAD

**Issue by Proch92** [mwaskom/seaborn#2762]
Example code:
```
import pandas as pd
import seaborn as sns

df = pd.DataFrame({'a': [1929245168.06679]*18})
sns.kdeplot(data=df, x='a')
```

seaborn version 0.11.2
python version 3.8.12

Error: `numpy.linalg.LinAlgError: singular matrix`

Expected:  `UserWarning: Dataset has 0 variance; skipping density estimate. Pass 'warn_singular=False' to disable this warning.`

I tried other types of singular matrixes and the singular warning implemented in 0.11.2 work as expected. (for example: `pd.DataFrame({'a': [0]*10})` or `pd.DataFrame({'a': [0]})`)
The problem seem to arise for particular floats. I tried other big floats and changed the value slightly resulting in different outcome.

Another interesting sequence:
`pd.DataFrame({'a': [1929245168.06679]*18})` -> error
`pd.DataFrame({'a': [1929245160.06679]*18})` -> error
`pd.DataFrame({'a': [1929245100.06679]*18})` -> no error and no warning (singular_warn is True)

**Comment by mwaskom** [comment]
Here is what seaborn is doing 

```python
import math
print(observation_variance := df["a"].var(ddof=1))
print(math.isclose(observation_variance, 0) )
```
```
5.48132967586363e-13
False
```

**Comment by mwaskom** [comment]
I don’t recall if there’s a reason this does a proactive check rather than catching the error, but that may be easier.

**Comment by mswue** [comment]
> Here is what seaborn is doing
> 
> ```python
> import math
> print(observation_variance := df["a"].var(ddof=1))
> print(math.isclose(observation_variance, 0) )
> ```
> 
> ```
> 5.48132967586363e-13
> False
> ```

Hi,
I didn't know where to best put this question, so please let me know if it is misplaced here. Sorry if this has been discussed elsewhere already.

I was wondering if like it is defined here, `math.isclose(observation_variance, 0)` will give `False` even for very small `observation_variance` because it uses relative tolerance by default. The documentation suggests using abs_tol for comparisons near zero [https://docs.python.org/3/library/math.html#math.isclose](url). Was this considered? On the other hand I guess deciding on an abs_tol value is not a straight forward choice either.


I stumbled upon this for the following example:
`sns.pairplot(pd.DataFrame([0] * 7), diag_kind="kde", diag_kws=dict(warn_singular=True))` --> no error, but warning
`sns.pairplot(pd.DataFrame([0.34] * 7), diag_kind="kde", diag_kws=dict(warn_singular=True))` --> error, no warning
`sns.pairplot(pd.DataFrame([0.341] * 7), diag_kind="kde", diag_kws=dict(warn_singular=True))` --> no error, no warning

I am using 
Python 3.7.13
seaborn 0.11.2
