### ISSUE TITLE
`kdeplot` raises `LinAlgError singular matrix` for time lag plot

### ISSUE THREAD

**Issue by MarcelRobitaille** [mwaskom/seaborn#2764]
Similar to #1502

I am trying to create a time-lag plot of a series of data. This plots the data series unshifted on the x axis, and the same data series shifted by one place on the y axis. Basically, I want the KDE/contour equivalent to this:

```python
series = sns.load_dataset('taxis').fare.dropna()
ax.hist2d(series[:-1], series[1:])
```

Why I try to do this with `sns.kdeplot`, I get `LinAlgError singular matrix`:
```python
series = sns.load_dataset('taxis').fare.dropna()
sns.kdeplot(x=series[:-1], y=series[1:])
```

I am opening a new issue because I thought this was supposed to be fixed in #1823. I am using version `0.11.2`.

**Comment by mwaskom** [comment]
#1823 handles univariate data with 0 variance or bivariate data with 0 variance in one or more marginal distribution. Your case of perfect correlation is different but basically the same issue as https://github.com/mwaskom/seaborn/issues/2716 where the decision was not to do anything about the error. It is harder to test for, more clearly a degenerate case, and bivariate kdeplots are not used by default in `pairplot` so robustness is less important.

That said, see #2762 which demonstrates a univariate case that slips through the check. It may be easier to handle that by changing the logic to catch a `LinAlgError`, which would implicitly handle this case. Otherwise I don't think there's any action to take here as seaborn doesn't make a general guarantee of not raising when you ask it to do something that statistically doesn't make sense.

**Comment by MarcelRobitaille** [comment]
@mwaskom Thanks for your answer. The action I wanted wasn't to change the error, just to make the plot I wanted. I did not know it was impossible. I suspected it would be, but then I saw such figures in papers.

**Comment by mwaskom** [comment]
Oh, I just realized what you're trying to do.

When you multiple pandas objects, seaborn (like pandas) generally aligns them using their indices, so the effect in your case is plot `x_t vs x_t` rather than `x_t vs x_{t-1}`.

This is demonstrated in the scatterplot (always best to start with a scatterplot):

```python
sns.scatterplot(x=series[:-1], y=series[1:])
```

**Comment by MarcelRobitaille** [comment]
Oh that makes total sense. I always forget that slicing keeps the old index. Thank you so much!
