### ISSUE TITLE
Non-Deterministic "Upsidedown" Bug in PDF Export of Barplot

### ISSUE THREAD

**Issue by SigmaX** [mwaskom/seaborn#2765]
### Issue

When using `sns.barplot()` with `plt.yscale('log')` to visualize very small error bars, the bars sometimes print "upside-down," but non-deterministically, and only when exporting to PDF.

- `seaborn==0.11.2`
- `matplotlib==3.5.1`
- `python==3.10.2`

### Expected Behavior

Barplots should always plot right-side-up, and there should be no non-determinism.

### MWE

```python
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns

# Create some test data
x = np.random.uniform(1000, 1001, 100)
y = np.random.uniform(1000, 1001, 100)
df = pd.concat([
    pd.DataFrame({'Condition': 'A', 'Score': x}),
    pd.DataFrame({'Condition': 'B', 'Score': y})
])

# Plot five PDFs of the data
for i in range(5):
    sns.barplot(x='Condition', y='Score', ci=95, data=df)
    plt.yscale('log')
    plt.savefig(f"./figures/{i}.pdf", format='pdf')
```

When I run this, some plots look correct:

![image](https://user-images.githubusercontent.com/313154/159179352-9bd3a19e-ff98-4e16-bf29-93c557be3135.png)

Others look upside-down: 

![image](https://user-images.githubusercontent.com/313154/159179373-c746d1af-70a5-4467-ad0f-9dde561be70e.png)

### Ideas

To try and isolate the problem, I experimented to see if the non-derminism is coming from `plt.savefig()` (
There is some [old chatter over at `matplotlib` about non-determinism in PDF generation](https://github.com/matplotlib/matplotlib/issues/6317/), so I thought maybe that could be the issue).

But modifying the MWE like so:

```python
sns.barplot(x='Condition', y='Score', ci=95, data=df)
plt.yscale('log')

# Plot five PDFs of the data
for i in range(5):
    plt.savefig(f"./figures/{i}.pdf", format='pdf')
```

Produces 5 copies of the image, all of which look the same.

The non-determinism, then, **seems to be coming from `sns.barplot()`,** not from `plt.savefig()`.

My second observation is that this bug only seems to occur with **small relative variances in the data**.  If I change my data

```python
x = np.random.uniform(0, 1, 100)
y = np.random.uniform(0, 1, 100)
```

then the bug no longer occurs.

**Comment by mwaskom** [comment]
Do you have any evidence that this is a seaborn issue per se? The bootstrapping seaborn uses to compute the errorbars is (by default, without using the `seed` a parameter) non-deterministic, so if you're up against some edge case I guess it would not surprise me that you would see slightly different behavior from run to run of the plotting function but not the figure saving. But matplotlib handles all the drawing. I would bet that this can be reproduced using `ax.bar` directly.

I don't actually know off the top of my head how matplotlib draws bar plots on log-scale axes, but if you think about it, bars normally start at 0, so I expect they're doing some tweak to the baseline so that their lower coordinates are finite. Maybe you're ending up with the "adjusted" baseline above your values for some reason?

But, FWIW, I ran your MWE a few times and was unable to get an upside down plot. Sometimes PDF bugs are on the *viewer* side, which is even more annoying...

**Comment by SigmaX** [comment]
@mwaskom Thanks!

On further investigation it _does_ appear to be a viewer issue.  Only one of 3 viewers I tried shows the issue (namely Evince—I've opened [an issue over there](https://gitlab.gnome.org/GNOME/evince/-/issues/1771)).

There is still some surprising non-determinism *somewhere* in the matplotlib-and-or-sns tool-chain here.  But perhaps it can be ignored.

**Comment by nbenitez** [comment]
According to a Cairo developer the bug is not on the pdf viewer, but on Matplotlib caused by an out-of-range y coordinate in the PDF drawing operations. I paste below [his comment](https://gitlab.freedesktop.org/poppler/poppler/-/issues/1250#note_1384186) on the issue:

This is the PDF operations that draw the rectangle.
```
q 601.0524023438 44.8 468.1475976563 359.4 re W n /A1 gs 0.8004901961
0.3534313725 0.2857843137 rg 0 j 0 w 0 G 0.8004901961 0.3534313725
0.2857843137 rg

624.459782 -109098066.144149 m
811.718821 -109098066.144149 l
811.718821 223.553682 l
624.459782 223.553682 l
h

f
Q
```
The y coordinate, -109098066.144149, is out of range. It still works in other viewers because of the rectangle clip before it. In cairo the coordinates are converted to an internal fixed point type with 24 bits integer and 8 bits fraction. Out of range values will wrap around to some other value which is why the rectangle is upside down.
I've proposed a work around for cairo in [cairo/cairo!325](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/325) but the real bug is in matplotlib.
