### ISSUE TITLE
Is the units parameter currently functional?

### ISSUE THREAD

**Issue by dhalpern** [mwaskom/seaborn#2769]
First, thank you so much @mwaskom for this amazing package -- I use it constantly in my own work. I recently noticed that categorical plots have a `units` parameter that is supposed to control the level of bootstrapping. If I am understanding the purpose of this correctly, using this parameter should result in error bars that reflect only within-unit variation (in the style of [Loftus and Masson, 1994](https://link.springer.com/article/10.3758/BF03210951)). This would be incredibly useful but I so far have not been able to get it to work. Using this parameter seems to result in plots that look essentially the same as without it specified. E.g.

> exercise = sns.load_dataset("exercise")
> g = sns.catplot(x="time", y="pulse", hue="kind", units="id", data=exercise, kind="point")
> g = sns.catplot(x="time", y="pulse", hue="kind", data=exercise, kind="point")

both result in the same figure (as far as I can tell). I can post a reprex where I know what the within-subject plot is supposed to look like but figured I'd first check whether I was using this correctly or perhaps this hadn't been implemented yet. Thanks so much for the help! 

I am using seaboard version 0.11.2 and python version
3.7.9 (default, Aug 31 2020, 12:42:55)

**Comment by mwaskom** [comment]
Hi, yes I believe it is functional, but its function is somewhat different than you expect. It's not designed to compute a "within subject" confidence interval, but rather to correct for the fact that if you have repeated measurements (per each condition), a naive bootstrap will underestimate the sampling variability because samples are not independent. So the approach is (1) resample _units_ (2) resample observations within unit.

The `exercise` dataset only has one observation at each time / pulse / kind crossing, so you see no difference there. But it is perhaps more clear with the `fmri` dataset:

```python
fmri = sns.load_dataset("fmri")
kws = dict(data=fmri, x="event", y="signal", hue="region", capsize=.2, dodge=True, seed=0)
sns.pointplot(**kws, units="subject", palette="muted", errwidth=6, scale=2)
sns.pointplot(**kws, palette="dark", errwidth=3)
```
![image](https://user-images.githubusercontent.com/315810/159588838-59cd9043-9425-46c9-acd1-a733bf8f6eba.png)

(N.b. the within-subject observations in the fMRI dataset are also not independent so this isn't statistically correct either, but it demonstrates the point. Also somehow I've never noticed that crossover interaction before. Huh.)

**Comment by dhalpern** [comment]
I apologize for the delayed response but thank you for this clear description/example! That makes much more sense now.
