### ISSUE TITLE
New feature: Function to plot horizontal lines at the Pythagorean mean

### ISSUE THREAD

**Issue by csamuel11** [mwaskom/seaborn#2787]
I think it would be nice if seaborn had a function to plot horizontal lines at the [Pythagorean mean](https://en.wikipedia.org/wiki/Pythagorean_means) for categorical data. I realize that one can plot the arithmetic mean using the `boxplot()` function and setting `showmeans=True`, as described [previously](https://stackoverflow.com/questions/67481900/how-to-add-a-mean-line-to-a-seaborn-stripplot-or-swarmplot). However, I often want to plot the geometric mean on top of a swarmplot and need to do a bit of extra work.

Here is an example:
```python
# load libraries
import pandas as pd
import seaborn as sns
from scipy import stats

# create a dataframe to use for plotting
## sample dataset
pen = sns.load_dataset('penguins')
pen = pen[(pen.species=='Adelie') & (pen.sex=='Male')].sort_values(by=['island'])

## get data by island. I often use datasets with very few values in each group, so I did that here, too.
biscoe = pen[pen.island=='Biscoe'].head(3)
dream = pen[pen.island=='Dream'].head(3)
torgersen = pen[pen.island=='Torgersen'].head(3)

## concatenate the data into a dataframe
df = pd.DataFrame(columns=biscoe.columns)
for island in [biscoe, dream, torgersen]:
    df = pd.concat([df, island]).reset_index(drop=True)

## make the body mass data numeric   
df['body_mass_g'] = pd.to_numeric(df['body_mass_g'])

# create the desired plot
## make a swarm plot
ax = sns.swarmplot(data=df, x='island', y='body_mass_g');

## Plot horizontal lines at the geometric means of the body mass values.
pivot = pd.pivot(df, values='body_mass_g', columns='island')
geo_biscoe = stats.gmean(pivot['Biscoe'].dropna())
geo_dream = stats.gmean(pivot['Dream'].dropna())
geo_torgersen = stats.gmean(pivot['Torgersen'].dropna())
ax.hlines(geo_biscoe, xmin=-0.2, xmax=0.2, color='black', linewidth=3, capstyle='projecting');
ax.hlines(geo_dream, xmin=0.8, xmax=1.2, color='black', linewidth=3, capstyle='projecting');
ax.hlines(geo_torgersen, xmin=1.8, xmax=2.2, color='black', linewidth=3, capstyle='projecting');
```

Here is the desired plot:
![horizontal_line](https://user-images.githubusercontent.com/81661212/166112089-14f62b5e-7ab0-4992-bf7a-6260ae1749c7.png)

Ideally, there would be a `mean_line()` function to do the same thing that I did above but more easily.

```python
ax = sns.swarmplot(data=df, x='island', y='body_mass_g');
ax = sns.mean_line(data=df, x='island', y='body_mass_g', type='geo', color='black', linewidth=3, capstyle='projecting');
```

Thanks for considering.

**Comment by mwaskom** [comment]
There are two separate requests here:

1. aggregate with geometric mean
2. represent individual data points with a horizontal line

Request (1) is satisfied by the existing seaborn functions that accept a generic `estimator` function, including `pointplot`, `barplot` and `lineplot`.

Request (2) is slightly trickier, there is no existing function that uses that visual representation "out of the box". But it is not impossible to accomplish:

```python
ax = sns.lineplot(
    data=df, x="island", y="body_mass_g",
    estimator=stats.gmean, ci=None,
    ls="", marker="_", mec=".2", ms=40, mew=2,
)
sns.swarmplot(data=df, x='island', y='body_mass_g')
```
![image](https://user-images.githubusercontent.com/315810/166113466-6be8998b-bee2-4d8b-9ae1-ea4a22eb5f0e.png)

Is this ideal? Nah. The "width" of the lines ends up parameterized in point units rather than the data units that would be more intuitive. And mixing categorical functions (`swarmplot`) with more generic functions (`lineplot`) can be tricky — ideally you would force a consistent order by setting a categorical dtype. If your data are often very sparse and real-valued, you may not need the swam plot and could just use `scatterplot` and `lineplot` together, which would simplify that part of it. But if you have discrete data values I could see how the swarming would help.

I do like this style of plot and wish it were a little easier to make but it's not obvious to me that it needs entirely a separate function, or whether it could be accomplished with some additional parameters to `pointplot`.

**Comment by mwaskom** [comment]
btw, free pandas tip:

replace
```python
## get data by island. I often use datasets with very few values in each group, so I did that here, too.
biscoe = pen[pen.island=='Biscoe'].head(3)
dream = pen[pen.island=='Dream'].head(3)
torgersen = pen[pen.island=='Torgersen'].head(3)

## concatenate the data into a dataframe
df = pd.DataFrame(columns=biscoe.columns)
for island in [biscoe, dream, torgersen]:
    df = pd.concat([df, island]).reset_index(drop=True)
```

with
```python
pen.groupby("island").head(3)
```

**Comment by csamuel11** [comment]
Thanks for the super quick response! I did not realize that one could use `estimator=stats.gmean` but will use that in the future. Also, for the horizontal lines, I'll use `lineplot` or `pointplot` (if it gets some additional parameters like you mention so the points could be horizontal lines).

I also appreciate the pandas tip. I'm still learning!
