### ISSUE TITLE
Calling `sns.heatmap()` changes matplotlib rcParams 

### ISSUE THREAD

**Issue by tomicapretto** [mwaskom/seaborn#2821]
See the following example

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns


mpl.rcParams["figure.dpi"] = 120
mpl.rcParams["figure.facecolor"] = "white"
mpl.rcParams["figure.figsize"] = (9, 6)

data = sns.load_dataset("iris")

print(mpl.rcParams["figure.dpi"])
print(mpl.rcParams["figure.facecolor"])
print(mpl.rcParams["figure.figsize"])
#120.0
#white
#[9.0, 6.0]

fig, ax = plt.subplots()
sns.heatmap(data.corr(), vmin=-1, vmax=1, center=0, annot=True, linewidths=4, ax=ax);

print(mpl.rcParams["figure.dpi"])
print(mpl.rcParams["figure.facecolor"])
print(mpl.rcParams["figure.figsize"])
#72.0
#(1, 1, 1, 0)
#[6.0, 4.0]
```

If I call again

```python
mpl.rcParams["figure.dpi"] = 120
mpl.rcParams["figure.facecolor"] = "white"
mpl.rcParams["figure.figsize"] = (9, 6)
```

then it works fine, but I don't know why it changes the rcParams.

**Edit** These are the versions being used

```
Last updated: Wed May 25 2022

Python implementation: CPython
Python version       : 3.9.12
IPython version      : 8.3.0

matplotlib: 3.5.2
seaborn   : 0.11.2
sys       : 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
[GCC 10.3.0]

Watermark: 2.3.0
```

**Comment by mwaskom** [comment]
Thanks for the super-thorough report! I don't think seaborn is the culprit here, though. I get the same result if I comment out the `sns.heatmap` call (or all the seaborn lines), so the only thing that happens is the creation of a new figure.

What's going on? The clue is the change to a 72 DPI. That's what is set by the inline backend (which is actually part of IPython, not matplotlib) and differs from the matplotlib default. I can't say exactly what's happening, but I know that a jupyter notebook will default to the inline backend, and I have to imagine that that happens in a lazy way, presumably triggering it the first time `pyplot` is used.

I can get the result you want by explicitly declaring `%matplotlib inline` before making the plot.

**Comment by tomicapretto** [comment]
@mwaskom thanks for the quick response! You're right, it's not a seaborn problem. The solution that worked for me is

```python
%matplotlib inline
sns.set_theme(style="darkgrid")
mpl.rcParams["figure.dpi"] = 120
mpl.rcParams["figure.facecolor"] = "white"
mpl.rcParams["figure.figsize"] = (9, 6)
```

Notice I'm calling `%matplotlib inline` **before** setting rcParams. If I do it after, it does not work.

Thanks again!
