### ISSUE TITLE
Keep distplot around as permanently depricated?

### ISSUE THREAD

**Issue by bcov77** [mwaskom/seaborn#2844]
Hi,

First let me say that I love seaborn and I use it quite literally every day. I'm part of a large academic lab and seaborn plotting really underlies a lot of our data visualization.

The distplot default parameters produce beautifully useful graphs. The KDEs, the transparency, stacking multiple graphs, all from sns.distplot(data). Heck, I've published scientific figures using distplot with near-default parameters. distplot has got to be my #1 all-time most used seaborn function.

With all that said, would it be difficult to simply *not delete* distplot? Surely if the new plotting functions work with it in place, the underlying functions could just keep working that way? (Or just dup them into some "distplot_legacy" file?). 

I know you can emulate distplot using the new functions, but, the number of arguments and extra code to do so become quite cumbersome. I love distplot for teaching new students how to plot distributions, because right off the bat, they produce a very useful graph without needing to use special functions or arguments.

Anyways, the day distplot gets deleted will be the day the world comes crashing down for me. I really hope you could consider just leaving it there.

Best,
Brian

**Comment by mwaskom** [comment]
>I know you can emulate distplot using the new functions, but, the number of arguments and extra code to do so become quite cumbersome.

I am a little confused by this statement. Perhaps you could give examples?

The only real difference between `histplot` and `distplot` defaults is the density curve. But that is intentional, and, I think, principled. While a while a histogram + density is useful for a continuous, unbounded distribution, it is not always appropriate and can in fact mislead, i.e., with discrete or bounded data,  or distributions with many repeated observations of a single value (usually 0). So I don't think its best for a histogram function to add a density by default, but with `histplot` it's just a `kde=True` away, and as a bonus you get to keep the counts on the y axis, something that isn't really possible to add with `distplot`.

In any case, the code is open source, so if it's so central to your workflows, feel free to copy it into a personal library (I appreciate that this doesn't solve the teaching usecase that you mention).

**Comment by bcov77** [comment]
I've googled the depreciation warning a few times and this stackoverflow answer is always the one that pops up.

https://stackoverflow.com/questions/67638590/emulating-deprecated-seaborn-distplots/67638591#67638591

The answer is a bit complex, but it ends up with these two "equivalent" calls:
```
sns.distplot( df['X'] )

# the bins= thing is probably redundant
sns.histplot(data=df, x="X", ax=ax_hist, bins=bin_nr, stat="density", alpha=0.4, kde=True, kde_kws={"cut": 3})
```

Here's an example of 3 graphs I made just now as part of today's work. This is a for-loop that calls each function with a plt.show() outside the loop:

```sns.distplot(data)```
![distplot](https://user-images.githubusercontent.com/21205950/173134355-2a3ee724-0ccd-4af7-a8e1-d03e44c55332.png)


```sns.histplot(data, kde=True)```
![kdetrue](https://user-images.githubusercontent.com/21205950/173134520-589a582c-773b-43e6-9163-0e062866a4a3.png)

```sns.histplot(data, kde=True, stat='density')```
![stat_density](https://user-images.githubusercontent.com/21205950/173134680-1a038b59-577c-4915-a49f-d4d3bc96617f.png)


Presumably there's some combination of arguments that will make them look equivalent. However, that stackoverflow answer didn't completely get it right either.

I'm certainly on-board with all the changes you made, this will certainly help a lot of people. distplot's defaults just happen to work perfectly for my type of data.

I'll definitely find a way to preserve distplot within my local environment. But, hopping enviromnments/systems/laptops/web-sessions it would be nice if distplot was just ready to go.

**Comment by mwaskom** [comment]
> this stackoverflow answer is always the one that pops up.

You could also check [here](https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751).

That answer shows how to _exactly_ replicate `distplot` output, but I don't think that's representative of using either function in most cases, and especially not in a teaching context. And while reasonable people can disagree, I think the new defaults are all defensible (e.g., yes it's a little fussy to have to pass `kde_kws={"cut": 3}`, but do you really _want_ the kde curve extending past your data?)

As for your practical example, it would be easier to weigh in with a reproducible example, but I think that taking a little time to learn more about the new functions could make you more productive. First, I think `histplot` not following the color cycle is a bug that was fixed at some point because I can't replicate it on the development version:

```python
for key in penguins.filter(like="bill"):
    sns.histplot(penguins[key])
```
![image](https://user-images.githubusercontent.com/315810/173144279-217d7ca1-8b0f-490e-8c8a-00b8c527ccef.png)

But if you upgrade, you won't need to write your own for loops (set `common_bins=False` to more directly reproduce the iterative approach:

```python
sns.histplot(penguins.filter(like="bill"))
```
![image](https://user-images.githubusercontent.com/315810/173144354-9af7e34b-6b29-4da9-b6a3-1a0394c3dc8c.png)

**Comment by bcov77** [comment]
The reason for the for-loop is that often times, what I'm plotting is some subset or transformation of the data that can't be easily encoded into the dataframe.

Anyways, thanks for your consideration. I knew someday the function would disappear and I wanted to do everything I could to keep it around.

Thanks for you time, consideration, and all the work you put into seaborn!

**Comment by mwaskom** [comment]
> what I'm plotting is some subset or transformation of the data that can't be easily encoded into the dataframe.

it also accepts lists of arrays/series, or a dict, or whatever. it's quite flexible.

**Comment by mwaskom** [comment]
The docs currently say that distplot will be fully removed in 0.14. I'm sure we'll all be using javascript by then ;)

**Comment by bcov77** [comment]
Javascript is pretty good, but python (especially seaborn) is still pretty popular ;)

<img width="666" alt="Screen Shot 2022-06-10 at 4 59 38 PM" src="https://user-images.githubusercontent.com/21205950/173160751-14973883-4978-442f-9e51-b51f189cef30.png">
