### ISSUE TITLE
Matplotlib warns on simple pandas scatter plot with seaborn color palette

### ISSUE THREAD

**Issue by mdruiter** [mwaskom/seaborn#2901]
All I do is this:

```
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme()
pd.DataFrame([[0, 1], [1, 0]]).plot.scatter(0, 1)
plt.show()
```

I get this warning:

> `*c*` argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with `*x*` & `*y*`.  Please use the `*color*` keyword-argument or provide a 2D array with a single row if you intend to specify the same RGB or RGBA value for all points.

I would not expect Seaborn to trigger any warning as I do not actively use it, apart from `sns.set_theme()`.

I use up-to-date versions: seaborn 0.11.2 and matplotlib 3.5.2.

**Comment by mwaskom** [comment]
This is really a pandas problem. The reason you see different behavior after setting the seaborn theme is that seaborn defines the color cycle using rgb tuples, whereas the default matplotlib cycle currently (it didn't used to be) uses hex strings.

RGB tuples are a valid representation of color in matplotlib (in fact, it's what you'd get from any of the colormap objects). The problem is that it's ambiguous when a single RGB tuple is passed to the `c` argument of scatter, which also accepts an array of scalars. But the solution there is for pandas to use the `color=` kwarg, not `c`. This is a rough edge in matplotlib (that we've encountered several times here), but not an example of seaborn doing anything wrong.

**Comment by mdruiter** [comment]
Ah, thanks! Interesting coincidence. I'll take it to the pandas forum/github then.

**Comment by mwaskom** [comment]
Incidentally, it's not actually necessary to set the default patch facecolor directly in this function anymore, since matplotlib's default changed to `"C0"` which will always point at the first color cycle value even if it changes through other means.

This should also fix your issue, since that was the actual source of the pandas problem (they are sourcing the default scatter color from that rc param, as I mentioned on the other issue).

They should probably still handle single rgb colors better in scatter.
