### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute

### ISSUE THREAD

**Issue by gretadog90** [mwaskom/seaborn#2972]
I have seaborn version 11.2 installed in my environment yet get this error for any call to the package. I've uninstalled and reinstalled multiple times, restarted Spyder and the kernel, and I still get this error 

example code from installation guide:
import seaborn as sns
df = sns.load_dataset("penguins")
sns.pairplot(df, hue="species")

output:
<img width="456" alt="Screen Shot 2022-08-23 at 5 52 47 PM" src="https://user-images.githubusercontent.com/106687311/186273124-dff2b2bf-75bd-49c0-bd00-849a0f944e1b.png">

matplot lib version 3.5.1
seaborn version 11.2

**Comment by mwaskom** [comment]
What happens when you do `print(sns.__file__)`?  What do the contents of that directory look like?

**Comment by gretadog90** [comment]
hmm it says "None"
<img width="486" alt="Screen Shot 2022-08-23 at 6 52 01 PM" src="https://user-images.githubusercontent.com/106687311/186279891-d644447a-4d1f-4ef1-8cc3-53012fd1ee9d.png">

**Comment by mwaskom** [comment]
I don't know what to make of that. Google suggests that `__file__` can be `None` if the module is not properly imported but something catches the relevant import errors. I don't know much about what spyder gets up to. What if you try in a simple Python interpreter?

Usually "why is seaborn missing this function" will be caused by people having a local `seaborn.py` file that they are accidentally importing but that should be evidence from `__file__`.

**Comment by gretadog90** [comment]
I get the same error...
<img width="705" alt="Screen Shot 2022-08-23 at 8 34 15 PM" src="https://user-images.githubusercontent.com/106687311/186289473-8e70e912-10ba-4048-829d-970815a3d97a.png">

**Comment by mwaskom** [comment]
I'm afraid there's not much else I can do to help here; this is an idiosyncratic issue with your system.
