### ISSUE TITLE
Seaborn Objects Bar plots with log y scale

### ISSUE THREAD

**Issue by antunderwood** [mwaskom/seaborn#3032]
When specifying a log y scale for a Bar plot the bars are not drawn correctly.
Example code:
```
df = pd.DataFrame.from_dict(
    {
        'x_values': [1,2,3,20],
        'frequency': [10000,100,10,1]
    }
)
plot = (
        so.Plot(df, x="x_values", y = "frequency")
        .add(so.Bars(edgecolor="C0", edgewidth=2))
        .scale(y="log")
    )

plot.show()
```
result:  
![image](https://user-images.githubusercontent.com/423/190866050-b78c367a-47e0-46f1-adb3-cc64bf64fbba.png)

**Comment by mwaskom** [comment]
This isn't too surprising, since the `Bar` mark is drawn from 0 and that obviously can't happen on a log scale. I believe that matplotlib has some kind of hack to change the bar baseline. I'm not certain that's my preferred solution. Here are two things that can be done in user-space:

1. Set a non-zero baseline for the bar mark (e.g. `so.Bars(edgecolor="C0", edgewidth=2, baseline=0.001)`). The downside is that the bars kind of hang in the air unless you also set the y limit.
2. Use a `symlog` scale instead of a `log` scale.

**Comment by antunderwood** [comment]
Thanks for a quick reply. The symlog scale is a very workable solution for my use case.

**Comment by mwaskom** [comment]
Ps it may not be clearly documented yet but you can parametrize the symlog string, like `symlog2` or `symlog.1` to control the amount of compression near 0.

**Comment by thuiop** [comment]
For people ending up there, here is another easy solution :
```python
import pandas as pd
import seaborn.objects as so
import matplotlib.pyplot as plt


df = pd.DataFrame.from_dict(
    {
        'x_values': [1,2,3,20],
        'frequency': [10000,100,10,1]
    }
)
fig,ax = plt.subplots()
plot = (
        so.Plot(df, x="x_values", y = "frequency")
        .add(so.Bars(edgecolor="C0", edgewidth=2))
    )
plot.on(ax).plot()
ax.set_yscale("log")
plt.show()
```
