### ISSUE TITLE
ModuleNotFoundError in Python 3.8.10

### ISSUE THREAD

**Issue by amdjedbens** [mwaskom/seaborn#3033]
I have installed seaborn using: `pip install seaborn`.

When running codes on `Python 3.7.12` (seaborn installed using pip version: `22.1.2`), it runs successfully.

However, when I install it with same method in my current environment (`Python 3.8.10`) & import it, it shows error:

      ModuleNotFoundError                       Traceback (most recent call last)
      Input In [38], in <cell line: 2>()
            1 # import seaborn as sns
      ----> 2 import seaborn

      ModuleNotFoundError: No module named 'seaborn'

My current python version is `3.8.10` (seaborn installed using pip version: `22.2.2`).

I tried: `!python3 -m pip install -U seaborn`, and it didn't work as well.

**Comment by mwaskom** [comment]
Hi, unfortunately it's possible to get into this situation with Python. There's some additional context in the [seaborn FAQ](https://seaborn.pydata.org/faq.html#i-ve-installed-seaborn-why-can-t-i-import-it).

Unfortunately I cannot really provide any help: there's nothing specifically having to do with seaborn that makes it more likely to encounter this problem, and there are no unique solutions. It really depends on how your personal machine is set up.

That said, it looks like you're working in a notebook, so you might try `%pip install` (note `%` instead of `!`).
