### ISSUE TITLE
How to change the color of legend (visualization of pointsize, fill, alpha and others) in the object interface.

### ISSUE THREAD

**Issue by liuzj039** [mwaskom/seaborn#3043]
Here I would like to be able to show the meaning of pointsize in legend in black instead of blue. But I didn't find where I can change this setting.

```python
(
    so.Plot(
        penguins, x="bill_length_mm", y="bill_depth_mm",
        color="species", pointsize="body_mass_g",
    )
    .add(so.Dot())
)
```
![image](https://user-images.githubusercontent.com/55271666/191910946-b549284d-571b-4e1a-9420-b072603ced3c.png)

Please forgive me if I missed something.

**Comment by mwaskom** [comment]
Once again, you have missed nothing, you're just very good at finding the configuration behaviors that didn't have an obvious solution and so got pushed from the initial release :)

However there is a workaround here because that value is not hardcoded, it's sourced from the first color of the default palette in the theme. So we could set a theme with a different palette (and then request the original one from the color scale) to get what you want:

```python
sns.set_theme(palette=[".2"])

(
    so.Plot(
        penguins, x="bill_length_mm", y="bill_depth_mm",
        color="species", pointsize="body_mass_g",
    )
    .scale(color="deep")
    .theme(mpl.rcParams)
    .add(so.Dot())
)
```
![image](https://user-images.githubusercontent.com/315810/191958713-c2afbea1-e186-435f-a665-f1783784720b.png)

**Comment by liuzj039** [comment]
Very cool solution. I will keep exploring new interfaces and recommending them to my colleagues.
