### ISSUE TITLE
[Feature-request] displot, facet-wise common_bins?

### ISSUE THREAD

**Issue by exhumea** [mwaskom/seaborn#3112]
# Current behavior

In `displot`, we can either set:
- `common_bins=True`: to use same bins for all facets and all hues
- `common_bins=False`: to use unique bins for a given facet and a given hue

# Requested behavior

It would be really nice to have an _intermediate_ setting for `common_bins`: that is to say common bins per facet, but for all hues of this facet.

_I managed to get it done by tweaking lower-levels `FacetGrid` and `histplot`, but I feel this would be great to have it directly implemented in `displot`, as I feel this may be useful in many cases._

# Reproducible example

We consider a dataset having:
1. a few categorical variables (e.g. `species` below)
2. several continuous features to explore (e.g. `feature` below) whole scales:
   - are different between features (e.g. lengths in mm, weights in g, ...)
   - are about the same between categories (to be explored)

```python
import seaborn as sns
penguins = (
    sns.load_dataset("penguins")
    .drop(columns=['sex', 'island'])
    .set_index('species')
    .rename_axis(columns='feature')
    .stack()
    .rename('value')
)
g = sns.displot(
    data=penguins.reset_index(),
    x='value', hue='species',
    col='feature', col_wrap=2,
    stat='density', common_norm=False, 
    edgecolor='white', linewidth=1,
    facet_kws=dict(sharey=False, sharex=False),
    common_bins=False, # if True: common bins for all facets, if False: no common bins at all, if ???: common bins per facet
);
```

# Output
![out](https://user-images.githubusercontent.com/31568095/198002379-88f85b07-4a53-48be-ac18-f6f02bf7a808.jpg)

### Versions
- seaborn: 0.12.1
- matplotlib: 3.6.0
- pandas: 1.5.1

**Comment by mwaskom** [comment]
This is something that would be pretty tricky to implement given the way that the `histplot` internals are written. But it is actually already built into the new objects interface. Although in cooking up an example, I realized there's a small bug at moment. I think I have a fix, with which we can get this:

```python
(
    so.Plot(penguins_long, x="value", color="species")
    .facet("feature", wrap=2)
    .add(so.Bars(), so.Hist(common_bins=["col"]))
    .share(x=False)
)
```
<img width=600 src="https://user-images.githubusercontent.com/315810/198174255-2663b78f-0fc8-46e4-8bf5-902a7f4f532d.png" />

But actually this sort of fiddly dataframe reshaping isn't necessary with the objects interface because of the `Plot.pair` method:

```python
(
    so.Plot(penguins, color="species")
    .pair(x=["bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g"], wrap=2)
    .add(so.Bars(), so.Hist())
)
```
<img width=600 src="https://user-images.githubusercontent.com/315810/198174354-3b76ed28-039b-4c4d-b436-709103e81278.png" />

**Comment by exhumea** [comment]
Thank you for your comprehensive answer @mwaskom, I'll switch to the new objects interface then!
