### ISSUE TITLE
Weights in `pairplot`

### ISSUE THREAD

**Issue by romanovzky** [mwaskom/seaborn#3121]
Hi there,

`histplot` accepts `weights`, but `pairplot` with `hist` as diagonal type doesn't seem to like it. The following

```python
sns.pairplot(
    data=all_data.query("split=='train'"),
    vars=["gjm_pt", "gjm_pt_gav", "rz", "tau1"],
    corner=False,
    hue="sample",
    diag_kind="hist",
    diag_kws=dict(fill=False,common_bins=True, common_norm=False, stat="density", bins=25, weights="jetwt"),
    grid_kws=dict(diag_sharey=False),
)
```
returns the error
```
ValueError: Could not interpret value `jetwt` for parameter `weights`
```
whereas the following does not
```python
sns.histplot(
    data=all_data.query("split=='train'"),
    x="gjm_pt",
    weights="jetwt",
    hue="sample",
    common_bins=True,
    common_norm=False,
    stat="density",
)
```
Thank you!

**Comment by mwaskom** [comment]
`PairGrid` passes a vector of data directly to the `x` parameter of the diagonal function rather than passing a dataframe and a column name. It does this because it used to use `plt.hist` internally which doesn't (didn't?) have a concept of referencing a dataframe column.

That said I think you can make this work by passing your vector of weights rather than the name of the column you want in `diag_kws`. (It would be easier to say for sure if your example were runnable).

**Comment by romanovzky** [comment]
Yes, that's exactly what happens, it works fine if I pass the array of weights. I was just finding the API to be less obvious then, as the parameters of the main functions accept the keyword for the DataFrame.

**Comment by mwaskom** [comment]
> as the parameters of the main functions accept the keyword for the DataFrame.

I think that's not quite right, e.g. this doesn't work either:

```python
sns.pairplot(tips, plot_kws=dict(hue="size"))
```

`PairGrid` predates most of seaborn's plotting functions and was originally designed to mostly be used with matplotlib functions. So, internally, it passes through vectors rather than dataframes and column names. I appreciate that's not super obvious, but also, changing how this works has the potential for breaking backwards compatibility. Tricky!

**Comment by romanovzky** [comment]
I can imagine. Thanks for the extra detail!
