### ISSUE TITLE
Wishlist for sns.scatterplot

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#315]
Open comment thread for functionality that would be good to have in a `sns.scatterplot` function. Some things that have been mentioned are:
- Scaling point size off a continuous variable that isn't directly interpretable as a point size (cf. #310)
- Better default colors (although #293 would also fix this)
- A better interface for handling continuous point coloring in a `FacetGrid` context, this currently requires a bit of a hack as color is the fourth positional argument so you would need to pass in a dummy argument for size.
- Jittering x and y points (currently build into regplot)

What else?

**Comment by philipp-germann** [comment]
What about some interactivity? Printing the `index` or the `Series` upon klicking the point is very useful when you need to check the raw data underlying a certain point. Such functionality is readily available in `matplotlib`.
This would maybe even be more suitable for `sns.pairplot`, as this function is particularly handy for quick data exploration.

**Comment by BrenBarn** [comment]
One thing I often wish for is the ability to specify a label for each point, that would be shown as text next to the point.  This is very useful for scatterplots with a relatively small number of points which you want to identify individually (e.g., countries, company names, specific products), and it's currently a pain with matplotlib because you can't pass a vector of strings to a single `text` call.  Ideally the point labels could then be turned on and off with a quick command.

**Comment by mwaskom** [comment]
It would be possible for a seaborn function to accept a vector of strings and draw them, but it would be bound by the same limitations as when you are using matplotlib directly. So each point would have to be a separate object "behind the scenes" and I don't think it would be possilbe to do what you describe in terms of turning the labels on and off.

**Comment by dansondergaard** [comment]
In general, it'd be great to be able to change marker size/style depending on the data. E.g.

```python
sns.scatterplot(data, x='PC1', y='PC2', hue='Disease', marker='Sex', size='SampleQuality')
```

It's currently a drag to do this with `sns.lmplot`.
