### ISSUE TITLE
pandas plotting backend?

### ISSUE THREAD

**Issue by MarcoGorelli** [mwaskom/seaborn#3176]
Plotly has toplevel `.plot` function which allows for a [pandas plotting backend](https://github.com/pandas-dev/pandas/blob/d95bf9a04f10590fff41e75de94c321a8743af72/pandas/plotting/_core.py#L1848-L1861) to exist:

https://github.com/plotly/plotly.py/blob/4363c51448cda178463277ff3c12becf35dbd3b8/packages/python/plotly/plotly/__init__.py

Like this, if people have `plotly` installed, they can do:
```
pd.set_option('plotting.backend', 'plotly')
```
and then `df.plot.line(x=x, y=y)` will defer to `plotly.express.line(data_frame=df, x=x, y=y)`:

![image](https://user-images.githubusercontent.com/33491632/205591364-e64bc5c9-21a9-475c-9bb3-1a2071e5a740.png)

It'd be nice to be able to do
```
pd.set_option('plotting.backend', 'seaborn')
```
and then have `df.plot.line(x=x, y=y)` defer to `seaborn.line(data=df, x=x, y=y)`

Would you be open to these ~150 lines of code or so to allow `seaborn` to be set as a plotting backend in pandas? Check the link above to see what it looks like in `plotly`. I'd be happy to implement this, just checking if it'd be welcome

**Comment by mwaskom** [comment]
I think I'd like to understand the proposal better.

The idea of having a "seaborn backend for pandas plotting" sounds somewhat strange since both seaborn and pandas plotting are APIs for rending a plot using a matplotlib or (in pandas case) other backend. Seaborn does not add anything in terms of plot rendering beyond matplotlib the way that plotly does.

So what is accomplished by putting seaborn in the middle that currently isn't accomplished with pandas default matplotlib backend? And how will you resolve the differences between the seaborn and pandas API?

Take this line plot example. In seaborn, if you do `sns.lineplot(df, x="date", y="price", color="stock")`, you'll get a `ValueError`. In seaborn (specifically in the classic interface), there are different parameter names for arguments that set properties directly (like `color`) and those that map a column name to them (i.e., `hue`). Which would be used in the "seaborn backend"?

Likewise for making faceted plots — seaborn and pandas handle this rather differently. Is the proposal that you'd gain access to seaborn's faceting API through `DataFrame.plot`? Would you dispatch pandas faceting parameters (e.g. `subplots=True`) to seaborn faceting functionality (i.e. `col=`/`row=`)? Or would pandas continue to own all the faceting logic, simply using seaborn to produce each subplot independently?

And how do you propose handling "wide-form" data? (i.e. when no `x` or `y` are explicitly assigned?) Most seaborn plots will map the dataframe dimensions to plot properties in a similar way to pandas (e.g., `sns.lineplot(data)` maps the index to `x`, the values to `y` and the columns to `hue` and `style`), but not always (e..g, `sns.barplot(data)` is not equivalent to `data.plot.bar()`).

**Comment by mwaskom** [comment]
In that case, I think this proposal is a lot more complicated than "just adding 150 lines"...

**Comment by mwaskom** [comment]
Is this a fair summary of the ask here?

- seaborn owns the implementation for translating between the existing `DataFrame.plot` API and matplotlib calls
- seaborn adds a _new_ layer complexity for going pandas -> seaborn -> matplotlib and handling all of the edge cases where the current seaborn and pandas APIs differ (like in the `color=`) example above
- because the pandas API is poorly tested, there's no way to automatically verify that the refactor has been successful, and seaborn will likely have to deal with a long tail of user-surfaced issues

Additionally, seaborn does not currently support all of the same plot kinds as pandas (namely, `pie`, `area`, and `hexbin` are missing), so we'd need to add those.

**Comment by MarcoGorelli** [comment]
I wouldn't ask seaborn to add any new plots (like `pie)` - if it's not in seaborn, I'd argue that it probably shouldn't be in pandas either

For anything that requires more than just a few lines of code for compatibility, I'd like to aim to deprecate the current pandas behaviour.

The layer in seaborn should really be very light, just like it is in plotly

**Comment by mwaskom** [comment]
> I wouldn't ask seaborn to add any new plots (like pie) - if it's not in seaborn, I'd argue that it probably shouldn't be in pandas either

That's tricky because sometimes things aren't in seaborn _because_ they're in pandas, e.g. "area plots" https://github.com/mwaskom/seaborn/issues/2410. In cases where a "seaborn version" of a plot type wouldn't add anything beyond what an existing pandas (or matplotlib) implementation can do, I'm usually reluctant to add it, especially if it doesn't fit nicely into seaborn's existing plot taxonomy. It's hard to see a case for pandas fully deprecating area and (alas) pie charts — they're fundamental for the kinds of applications that many people use pandas for.

> The layer in seaborn should really be very light, just like it is in plotly

In fairness, though, the plotly layer is light in part because a lot of stuff just doesn't work. e.g. for a few quick things i tried, both wide data and subplots raise. And in the example you linked to above, the `by` and `bins` (bins!!) parameters for histograms are simply ignored, as with `s` and `c` for scatter. I suppose it's fine for the plotly backend to not be feature-complete with the matplotlib backend, but you'd be talking about deprecation of major functionality if you took the same approach and didn't include anything in the "seaborn" backend that wasn't a simple parameter name translation.

**Comment by nicolaskruchten** [comment]
> In fairness, though, the plotly layer is light in part because a lot of stuff just doesn't work.

Oh yes, the `plotly` backend deliberately does not aim to be arg-compatible with the builtin backend! This is [what I put in the docs](https://plotly.com/python/pandas-backend/):

<img width="958" alt="image" src="https://user-images.githubusercontent.com/203523/205990048-cbca7b47-f336-47de-a027-7ba38eddb470.png">

**Comment by MarcoGorelli** [comment]
Thanks for both sharing your thoughts, much appreciated

Closing for now then
