### ISSUE TITLE
How to merge two sns.clustermap object?

### ISSUE THREAD

**Issue by liujilei156231** [mwaskom/seaborn#3212]
Hello seaborn team,
This is my code.  I want to merge 2 clustermaps into one PNG,but it does not work.
```
plt.figure()
plt.subplot(121)
sns.clustermap(w1)
plt.subplot(122)
sns.clustermap(w2)
plt.savefig("test.png")
```
How to repair it ? 
Thanks!

**Comment by thuiop** [comment]
This won't work because clustermap is a figure-level function, which creates and manages its own figure. I don't think it is currently possible in seaborn to have the two in the same figure, at least not without a lot of effort. Merging them afterward with an image processing software is probably the way to go (you could do it in an automated way using ImageMagick for instance https://imagemagick.org/script/montage.php)

**Comment by mwaskom** [comment]
Yes that's right; see also the [tutorial](https://seaborn.pydata.org/tutorial/function_overview.html#figure-level-vs-axes-level-functions) and [FAQ](https://seaborn.pydata.org/tutorial/function_overview.html#figure-level-vs-axes-level-functions). If you search on stackoverflow, some people have developed hacks for working around this, although they have mixed results.
