### ISSUE TITLE
histplot dropping data unexpectedly

### ISSUE THREAD

**Issue by martinobertoni** [mwaskom/seaborn#3220]
Hi there!
thanks for the greatest package ever!
Minor concern about the `histplot` function, that apparently drops some values, without warning.
Apparently the `binrange` is treated differently when specifying `bins` or `binwidth`
```
vals = [1.0,0.9]
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(7, 2), sharey=True, dpi=100)
sns.histplot(vals, binrange=(-1,1), bins=20, ax=ax1)
ax1.set_title('using bins')
sns.histplot(vals, binrange=(-1,1), binwidth=0.1, ax=ax2)
ax2.set_title('using binwidth')
```

![image](https://user-images.githubusercontent.com/5373219/211836417-e8697ba5-61e4-4a85-96f0-e54e2882c9d4.png)

**Comment by mwaskom** [comment]
I think this is a floating point thing. The code that generates the bins is roughly

```python
binwidth = 0.1
start, stop = -1, 1
bin_edges = np.arange(start, stop + binwidth, binwidth)
```

and

```python
print(bin_edges.max())
print(bin_edges.max() > max(vals)
```
```
0.9999999999999996
False
```

**Comment by jhncls** [comment]
I've been looking into this some time ago, and got quite confused.  `binwidth` seems a simple concept in natural language, but rather deceptive when working with floating point. Sometimes the `stop` value falls outside the last bin. And sometimes, it can even fall in the next to last bin (with an ugly empty last bin). An example is `np.arange(1.8, 2.7+0.1, 0.1)` which gives `[1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8]` or one superfluous edge, when running on my laptop.

Also, there is a problem when the start and stop values are equal (then `np.arange` gives a single value).

I tried working around the problem by replacing `np.arange` (which accumulates errors) with `np.linspace`. But ultimately that gave similar errors. (I.e. `num_bins = np.ceil((stop - start) / binwidth).astype(int)` and `bin_edges = np.linspace(start, start + binwidth * num_bins, num_bins + 1)` also has its own rounding problems)

Here is a possible approach to tackle these problems:
```python
if stop <= start:
    bin_edges = np.array([start, start + binwidth])  # at least 2 edges are needed
else:
    bin_edges = np.arange(start, stop + binwidth, binwidth)
    bin_edges[-1] = max(stop, bin_edges[-1])  # due to float approximation, stop might fall outside the last bin
    if len(bin_edges) > 2 and stop < bin_edges[-2]:
        bin_edges = bin_edges[:-1]  # workaround for empty last bin
```
PS: Looking somewhat deeper into the source code, there seems to be a function `_define_bin_edges` in `class Hist` (_stats/counting.py) and one in `class Histogram` (_statistics.py).  Only the function in `class Histogram` adds an extra bin edge when either `start==stop` or `stop` would be larger than `bin_edges.max()`. Probably this is related to some refactoring in progress.

**Comment by mwaskom** [comment]
Agreed, even without roundoff issues, the data range or `binrange` may not be evenly divisible by `binwidth` in which case you end up ignoring one of them. And then roundoff error complicates things, as demonstrated here where you risk dropping the right-most datapoint.

I'm think I'm inclined to say that we should swap the order of precedence and always respect the data range/`binrange`, compromising `binwidth` when necessary. In other words, switch to `np.linspace(start, stop, num_bins)` where `num_bins` is chosen to make bin widths as close to the requested `binwidth` as possible.

Otherwise, I don't know a good way to eliminate the possibility of accidentally dropping data, while still allowing `binrange` to be used to clip data (if that is for some reason desired).
