### ISSUE TITLE
How to enable SVG as the default format for Jupyter inline using the objects API

### ISSUE THREAD

**Issue by aeturrell** [mwaskom/seaborn#3229]
Hello,

I'm converting the CORE Econ Textbook to Python and want to ensure high-quality vector images appear in the markdown files that will be used to build the website. Using regular seaborn or matplotlib, it's possible to set the jupyter inline backend to SVG so that markdown files created by jupyter nbconvert end up being bundled with SVG files. Having beautiful, clean charts will encourage more budding economists to learn analytical tools.

I'm trying to get jupyter inline to produce SVG charts when using the seaborn objects API. I've tried the jupyter notebook below, but it produces pixelated PDF files. (However, regular seaborn and matplotlib charts do produce SVG files.)

I realise this is VERY new in the API, or may not yet be implemented at all, or I may just be doing it wrong...

Very grateful for your help, and for the seaborn objects API, which is genuinely phenomenal.

The first cell is:

```python
import seaborn.objects as so
import matplotlib as mpl
import seaborn as sns
import matplotlib_inline.backend_inline

# Make output charts in 'svg' format
matplotlib_inline.backend_inline.set_matplotlib_formats("svg")
# Make seaborn work consistently with this
so.Plot.config.theme.update(mpl.rcParams)

penguins = sns.load_dataset("penguins")
```

then the chart is given by

```python
(
    so.Plot(penguins, x="bill_length_mm", y="bill_depth_mm")
    .add(so.Dot())
)
```

The Jupyter reprex is:

```text
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import seaborn.objects as so\n",
    "import matplotlib as mpl\n",
    "import seaborn as sns\n",
    "import matplotlib_inline.backend_inline\n",
    "\n",
    "# Make output charts in 'svg' format\n",
    "matplotlib_inline.backend_inline.set_matplotlib_formats(\"svg\")\n",
    "# Make seaborn work consistently with this\n",
    "so.Plot.config.theme.update(mpl.rcParams)\n",
    "\n",
    "penguins = sns.load_dataset(\"penguins\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "mpl.rcParams[\"backend\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "(\n",
    "    so.Plot(penguins, x=\"bill_length_mm\", y=\"bill_depth_mm\")\n",
    "    .add(so.Dot())\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%load_ext watermark\n",
    "%watermark --iversions\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "vscode": {
   "interpreter": {
    "hash": "26c4b888616894cf8360ee3d370b6a41732ef00c8f1d61e869c42a8428cf1ac1"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

with the watermark producing:

```text
matplotlib       : 3.6.0
matplotlib_inline: 0.1.6
sys              : 3.8.8 (default, Apr 13 2021, 12:59:45) [Clang 10.0.0 ]
seaborn          : 0.13.0.dev0
```

**Comment by jcmkk3** [comment]
I believe that this PR will provide what you're looking for once it is merged. https://github.com/mwaskom/seaborn/pull/3225

**Comment by aeturrell** [comment]
Fantastic! As ever, the amazing @mwaskom is a step ahead. 

Look forward to trying this out.

**Comment by mwaskom** [comment]
Quite right that #3225 will let you configure `Plot` to emit SVGs but to explain a little further:

- the default inline display that you see when a `Plot` is returned from a cell in a notebook is actually not using the inline backend — or pyplot at all — but rather IPython's rich object display system
- you _can_ hook into pyplot by calling `Plot.show()`, and if you've set the inline backend to render SVGs, you'll see SVGs when you do so
- I wouldn't recommend adding `Plot.show` by default in pedagogical material because it's not necessary and the normal `Plot` display system is more powerful, e.g. it produces high-resolution ("retina") mode png images by default
- As much as I love crisp vector graphics, I'd be careful defaulting all plots in a notebook to SVG, especially in a pedagogical context. SVG size will scale with the density of data in a plot and having complex plots, or even just a bunch of simple ones, can really degrade browser performance. Anyway I'm sure you know that, just something to keep in mind as it's not obvious (or easy to diagnose) for a lot of students
