### ISSUE TITLE
Discrepancy accessing facet_data between relplot and FacetGrid

### ISSUE THREAD

**Issue by ChemicalSailor** [mwaskom/seaborn#3238]
`relplot` uses `FacetGrid` under the hood, so I would expect the FacetGrid methods to work the same way. However using `facet_data` after calling `relplot` returns the full data set, using `facet_data` on a directly instantiated `FacetGrid` returns data subsets, the expected behaviour:
```
tips = sns.load_dataset('tips')

fg = sns.relplot( tips, x='total_bill', y='tip', hue='smoker' )
[ d.shape for ijk, d in fg.facet_data() ]
```
Returns `[(244, 7)]`

```
fg = sns.FacetGrid( tips, hue='smoker' ).map( sns.scatterplot, 'total_bill', 'tip' )
[ d.shape for ijk, d in fg.facet_data() ]
```
Returns `[(93, 7), (151, 7)]`

This behaviour affects being able to use `map` to build more complex plots on top of `relplot`

**Comment by mwaskom** [comment]
I don't think there's a discrepancy here — `relplot` does not pass the `hue` to its internal `FacetGrid` because its axes-level functions (`scatterplot` in this case) both understand `hue`. This produces better results, especially in the case of `scatterplot`, where the ordering of observations in the original dataframe is preserved rather than plotting each hue level on top of the others in layers. A similar pattern is used in the other figure-level functions (`displot`, `catplot`), where it's also better to pass `hue` to the underlying axes-level function otherwise things like dodging, stacking, or shared bins wouldn't work.

**Comment by ChemicalSailor** [comment]
I understand. In that case can some notes be added to the documentation at least, as it’s not obvious that’s what the behaviour, particularly when using `map`, should be. On 27 Jan 2023, at 12:32, Michael Waskom ***@***.***> wrote:﻿
I don't think there's a discrepancy here — relplot does not pass the hue to its internal FacetGrid because its axes-level functions (scatterplot in this case) both understand hue. This produces better results, especially in the case of scatterplot, where the ordering of observations in the original dataframe is preserved rather than plotting each hue level on top of the others in layers. A similar pattern is used in the other figure-level functions (displot, catplot), where it's also better to pass hue to the underlying axes-level function otherwise things like dodging, stacking, or shared bins wouldn't work.
