### ISSUE TITLE
Colorscale agnostic default aesthetics

### ISSUE THREAD

**Issue by matulad** [mwaskom/seaborn#3266]
Hi,

I don't know if it's just me, but I find the default choice of aesthetics ambiguous. Especially, if you use e.g. color mapping in other layers. Let's take a look on the following example:

```{python}
(
    so.Plot(tips, x="total_bill", y="tip")
    .add(so.Dot())
    .add(so.Line(), so.PolyFit(order=1), color="sex")
)
```
The result:
![obrazek](https://user-images.githubusercontent.com/107509750/219724219-d61ee194-872e-4672-852e-7d87d3ae0aa8.png)

On the first glance, it seems that __all the dots are somehow related to the blue line only__. Yeah, I know that there is missing a dot in legend (see the following image for reference). But people tend to do a quick conclusions so I'm worried about the missleading interpretations ... Moreover, the blue line is somehow _lost_ in the plot (although the it's of the same importance as the other line!) so the observer's eyes are catch by the orange line only.

Reference - a plot with color aesthetics mapped for `so.Dot()` object, too. The only difference (legend-related) is the dot.
```{python}
(
    so.Plot(tips, x="total_bill", y="tip")
    .add(so.Dot(), color="smoker")                  # <-- DIFFERENCE
    .add(so.Line(), so.PolyFit(order=1), color="smoker")
)
```
![obrazek](https://user-images.githubusercontent.com/107509750/219726552-6ae83b1e-6de8-4738-9d7e-faf63da1e7cd.png)

----

__The proposal__ - let's make the default aesthetics colorscale agnostic. Either dark grey-ish (that would be my choice) or some color not used in color scale.

![obrazek](https://user-images.githubusercontent.com/107509750/219729106-a1115d55-2cf0-4e30-8b46-e937f792b99b.png)
(Personally, I find the default pointsize too bold so I've also tweak that a bit..)

**Comment by thuiop** [comment]
As a related note, someone complained to me that if, for instance, you group both on the color and on the marker, the markers in the legend will be blue, i.e. the same color as the first one in the default scale.

**Comment by matulad** [comment]
😃 ... actually, that was my side note, too, and I'd  elaborated an example:
![obrazek](https://user-images.githubusercontent.com/107509750/219804002-7ae452ed-7c36-449e-8688-17d786f21455.png)

But I thought it would lower the focus on the original topic of the issue that bothers me a lot more (and which could be misinterpreted easier), so I decided not to include it in the issue description..

**Comment by mwaskom** [comment]
I agree that you should not make a plot that looks like your first example. But you need only pass a color for the `Dot` layer and the problem is solved. If someone makes the first plot and it misleads, that is on them.

I debated having the color property default to black and decided against it. (Consider that you are not the first person to have thought of these issues...).

If marks defaulted to `color="k"`, there would be no way to change the default color of (non-mapped) marks through the theme interface. And black-and-white plots are very boring and not consistent with the established aesthetics of seaborn.

I agree that the colors for the legend entries when color is mapped to another variable is not ideal. It is the flipside to having the legend entries generally correspond to the non-mapped property values. I intend to address it at least by providing an interface for setting properties on the legend artists. I also think that it makes sense to have a concept of a "null" (not in the sense of missing) value for a property that could be used in the legend when that property is otherwise mapped.

Once that concept of a null property is defined, it may be worth considering changing the default behavior to also "null out" the properties of the mark itself when that property is mapped in other layers. That would need some consideration.

But I am 👎 on always having color default to black.

**Comment by matulad** [comment]
Hi,

thanks for your reply and explanation. 

> Consider that you are not the first person to have thought of these issues..

Well, of course I do not thing I'm the first person who is bothered by those issues. And I really did my best to search for related issues/questions/discussions. I did not find anything concerning ambiguity of default colors. If I missed something, it would be great if you can point me to the right resources. 

>If marks defaulted to color="k", there would be no way to change the default color of (non-mapped) marks through the theme interface. And black-and-white plots are very boring and not consistent with the established aesthetics of seaborn.

Oh, __that is interesting__. I didn't see the drawback for the use of theme interface, thanks. As I haven't started with coding before rising the issue (as requested), I'm quite curious why it is such a blocker. I need to take a look.. 🙂 .

On the other side, the boringness I do not count for an argument in discussion of clarity and non-misleadingness of charts. Although, I take the consistency.

But still, __this is a workaround solution to my issue__, isn't it? To create some (let's say) conservative theme for those who prefere unambiguity against boringness and sentiment.. The new [https://github.com/mwaskom/seaborn/pull/3223](3223) feature may be of great use here, I can't wait for this functionality.

And I'm looking forward to the `null`/`null out` stuff, too, it sounds interesting.

**Comment by mwaskom** [comment]
> On the other side, the boringness I do not count for an argument in discussion of clarity and non-misleadingness of charts. 

I'm going to say this very directly: I do not care whether you count something for an argument.

The software is free: you can use it or not us it, and you are welcome to form whatever opinions about it that you please. GitHub does provide a forum for you to share those opinions, but the maintainer of a library is under no obligation to rebut or even engage with them.

As I've said, I won't be revisiting the default color of the marks, so further discussion would be a waste of time and energy that is better directed towards more productive ends.

**Comment by matulad** [comment]
Oh, my appologies, I didn't mean to be offensive in a tiny bit! English is not my primary language so the wording I've chosen was maybe a bit rude. 

I definitely didn't want to make you do something! As you said, there is an option to discuss your ideas in GitHub. I have opened an issue to do so, but now I see I should used another place.

Thanks for stating your opinion clearly, I'm ok with that. I'm looking forward to 0.13 that will ease the theming.  Later on, it would be great to have some classic/boring theme, too.
