### ISSUE TITLE
histplot: Only show integer labels when `discrete=True`

### ISSUE THREAD

**Issue by EwoutH** [mwaskom/seaborn#3308]
A [histplot](https://seaborn.pydata.org/generated/seaborn.histplot.html) with `discrete=True` now shows labels with decimals, when only small numbers are present:
```Python
agent_wealth = [0, 0, 1, 0, 2, 2, 1, 3, 1, 0]

# Create a histogram with seaborn
g = sns.histplot(agent_wealth, discrete=True)
g.set_title("Wealth distribution")
g.set_xlabel("Wealth")
g.set_ylabel("Number of agents")
```
![wealth_distribution](https://user-images.githubusercontent.com/15776622/228326399-1140aee1-2bc4-41f0-98fe-05967dc7765c.svg)

It would be great if when `discrete=True`, a histplot would only show integer labels.

Then it looks like this:

![wealth_distribution](https://user-images.githubusercontent.com/15776622/228326302-b84d8803-049a-4412-aede-68893aa5dcaf.svg)

**Comment by mwaskom** [comment]
I can see how this would be a nice feature in some situations, but I'm not sure it's a good idea in general.

To do this we'd need to modify the tick locator, e.g. something like this:

```python
agent_wealth = [0, 0, 1, 0, 2, 2, 1, 3, 1, 0]
ax = sns.histplot(agent_wealth, discrete=True)
ax.xaxis.set_major_locator(mpl.ticker.MaxNLocator(integer=True))
```

The problem is that there's no great way to tell whether the user has already customized the tick locator while setting up the plot, e.g. to control the frequency of ticks. If we clobbered the user's configuration, it would be hard for them to understand why their custom locator is apparently not having an effect, unless they knew about this little magical behavior. At the same time, the upside is relatively small since it only matters for plots with ≈4 or fewer bins. And the user-space solution is a one-liner (assuming you already have `mpl` imported).

So I think on balance I'm -0.5 on the proposal.
