### ISSUE TITLE
`relplot` `kind='scatter'` incompatible with `units` keyword argument

### ISSUE THREAD

**Issue by ahalev** [mwaskom/seaborn#3324]
When calling `seaborn.relplot` with `kind='scatter' and passing a value for `units`, an error is raised:

```python

import seaborn as sns

from matplotlib import pyplot as plt

sns.set_theme(style="ticks")

dots = sns.load_dataset("dots")

# Plot the lines on two facets, successfully:
sns.relplot(
    data=dots,
    x="time",
    y="firing_rate",
    units="coherence",
    kind="line",
    estimator=None
)

plt.show()

# Failure:
sns.relplot(
    data=dots,
    x="time",
    y="firing_rate",
    units="coherence",
    kind="scatter"
)

plt.show()
```

``` shell
Traceback (most recent call last):
  File "/Users/ahalev/miniforge3/envs/forge_rl_env/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ahalev/miniforge3/envs/forge_rl_env/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 2029, in _setattr_cm
    yield
  File "/Users/ahalev/miniforge3/envs/forge_rl_env/lib/python3.9/site-packages/matplotlib/artist.py", line 1197, in _update_props
    raise AttributeError(
AttributeError: PathCollection.set() got an unexpected keyword argument 'units'
python-BaseException
```

This is a bit of a vague exception in my opinion and is caused by the `units` value getting picked up in `seaborn.relational._ScatterPlotter.get_semantics` and then being passed to the plotter function.

I could be convinced that `units` is incompatible with `kind='scatter'`, but it seems to me like it should be ignored or a clearer exception message should be raised instead of this behavior. A check to pop `units` in a scatter plot could alleviate this.

**Comment by mwaskom** [comment]
> I could be convinced that units is incompatible with kind='scatter'

What would you expect it to do? In `lineplot`, `units` controls how observations are aggregated and/or connected, neither of which apply in `scatter`.

> This is a bit of a vague exception in my opinion

I don't disagree but I'm afraid there's not much that can be done here. Because seaborn functions typically pass additional kwargs through to matplotlib functions (which themselves also tend to use kwargs redirection), there's no obvious point at which one could say with certainty whether the user has passed some kwargs that we can't do anything with.

> A check to pop units in a scatter plot could alleviate this.

Yes but think about what this would entail across the library. It's a common pattern that multiple axes level functions are grouped together with a figure-level function because they share a common set of behaviors / parameters while also differing in various ways. You're asking for every function to actively ignore all of the non-common parameters of _other_ functions.

**Comment by ahalev** [comment]
is that not effectively what is being done [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/relational.py#L877-L878)?
