### ISSUE TITLE
Plots created via seaborn.objects and inside for loop do not appear in Jupyter notebook unless p.plot() is called

### ISSUE THREAD

**Issue by erikr** [mwaskom/seaborn#3404]
First, let me preface this issue by thanking @mwaskom for such a wonderful open-source library. I lean heavily on Seaborn for almost all of my data visualization needs. Both the aesthetics and abstractions are superb.

# Summary
I am excited to use the `seaborn.objects` interface.

I am using Jupyter Lab and am iterating through a `for` loop. Inside the loop I seek to generate a plot via the simplest calls to `seaborn.objects` methods.

Sadly, the plot does not appear. If I call these methods outside of a `for` loop, the plot is generated as expected.

I can rescue plot generation with additional code, but I don't know if this is expected behavior.

# Reproducible code example that demonstrates the problem + output

Here are the three scenarios:

## 1. Generates plot as expected
```python
import pandas as pd
import seaborn.objects as so 
import matplotlib.pyplot as plt

dat = pd.DataFrame({'a':[1,2],'b':[3,1]})
so.Plot(dat, x = 'a', y = 'b').on(fig).add(so.Dot())
```

![Screenshot 2023-06-26 at 2 41 18 PM](https://github.com/mwaskom/seaborn/assets/1253422/f179d3f6-7cfc-4f94-95fd-8c30fb79ecb2)

## 2. Fails to generates plot as expected
```python
import pandas as pd
import seaborn.objects as so 
import matplotlib.pyplot as plt

for i in range(3):
    dat = pd.DataFrame({'a':[1,2],'b':[3,i]})
    so.Plot(dat, x = 'a', y = 'b').on(fig).add(so.Dot())
```

## 3. Generates plot as expected, via additional code
```python
import pandas as pd
import seaborn.objects as so 
import matplotlib.pyplot as plt

for i in range(3):
    dat = pd.DataFrame({'a':[1,2],'b':[3,i]})
    fig = plt.figure()
    p = so.Plot(dat, x = 'a', y = 'b').on(fig).add(so.Dot())
    p.plot()
```
![Screenshot 2023-06-26 at 2 42 57 PM](https://github.com/mwaskom/seaborn/assets/1253422/c2028537-e319-4fbf-a3a6-42840e150b72)

# Clear explanation of why you think something is wrong
Nothing in the tutorial at https://seaborn.pydata.org/tutorial/objects_interface.html suggests I would _not_ be able to call `so.Plot` and generate plots inside of an iterable loop.

At first I thought https://github.com/mwaskom/seaborn/issues/3373 described a similar issue, and @mwaskom's reply helped me determine how to rescue plot generation. But I am not aware of another issue describing this behavior.

# The specific versions of seaborn and matplotlib that you are working with
![Screenshot 2023-06-26 at 2 45 42 PM](https://github.com/mwaskom/seaborn/assets/1253422/766d478d-fca4-44e4-9533-34352b577f70)

**Comment by mwaskom** [comment]
This is expected behavior, at least on my end. Something needs to tell `Plot` when it's time to actually compile the plot spec you've defined by calling its methods. In a notebook, when the `Plot` is returned from the last statement in the cell, Jupyter's rich display hooks take care of this (somewhat magically, by invoking `Plot._repr_png_`). But othewise you either need to call `Plot.show` (somewhat more expected when hooking into pyplot using `Plot.on`) or `Plot.show`.

This is demonstrated, if not called out, by the "Integrating with matplotlib" section [in the tutorial](https://seaborn.pydata.org/tutorial/objects_interface.html#integrating-with-matplotlib). I don't know that it's possible to call out all the _specific_ constructs where you'd need to do this (i.e., there's nothing special about the for loop in your example, you'd have the same issue if you just wrote out the three lines).

Note that the docs for [`Plot.on`](https://seaborn.pydata.org/generated/seaborn.objects.Plot.on.html#seaborn.objects.Plot.on) also say

> When using this method, you will also need to explicitly call a method that triggers compilation, such as [Plot.show()](https://seaborn.pydata.org/generated/seaborn.objects.Plot.show.html#seaborn.objects.Plot.show) or [Plot.save()](https://seaborn.pydata.org/generated/seaborn.objects.Plot.save.html#seaborn.objects.Plot.save). If you want to postprocess using matplotlib, you’d need to call [Plot.plot()](https://seaborn.pydata.org/generated/seaborn.objects.Plot.plot.html#seaborn.objects.Plot.plot) first to compile the plot without rendering it.

**Comment by erikr** [comment]
Thanks, your explanation is clear. Indeed, the tutorial describes the behavior. I jumped right in to a notebook to try out some code before I made it down to that section near the bottom.

It would be nice if `Plot._repr_png_` was invoked in a `for` loop within a Jupyter cell, and not only if `Plot` is returned from the last statement. The fact it is not was a surprise.

**Comment by mwaskom** [comment]
I don't think that's too different from this not printing anything:

<img width="297" alt="image" src="https://github.com/mwaskom/seaborn/assets/315810/6822efde-7819-4beb-9f8d-92a73dfaddca">

A terminal interface behaves the same way

```
In [1]: for i in range(3):
   ...:     i + 1
   ...:

```

The mental model you should have is of a REPL, where each cell is a small script that runs top-to-bottom and then can have an "output" that is shown below it.
