### ISSUE TITLE
Migrate examples to use seaborn objects

### ISSUE THREAD

**Issue by beyarkay** [mwaskom/seaborn#3432]
Hi there! love the library.

I've wanted to start using the objects interface as it seems a lot more powerful, but I've often been stymied by the (relative) lack of examples when compared to the existing `sns` examples.  For example, the [swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html) docs have a nice walk through with lots of example code that a user could probably just copy-paste and have it "just work". I think some equivalent would be invaluable for the `so` interface.

Would the project be open to PRs which attempt to reproduce existing examples but using the `so` interface instead of the `sns` interface? I'm not sure how this would be best accomplished, but some approaches might be:

- Reproducing the [`examples`](https://seaborn.pydata.org/examples/different_scatter_variables.html) gallery using `so`
- Including code in the existing `sns` functions (such as [swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html)) showing the user how to accomplish an equivalent function but using the `so` interface
- Rewriting the [tutorial](https://seaborn.pydata.org/tutorial/introduction.html) to use the `so` interface.

I've assumed that the long term goal is to deprecate the `sns` interface in favour of the `so` interface, although I'm realising now that this isn't actually specified anywhere, so apologies if I've made a mistaken assumption. Looking forward to hearing feedback and helping out if possible.

**Comment by mwaskom** [comment]
Thanks for the positive feedback.

> I've assumed that the long term goal is to deprecate the sns interface in favour of the so interface

This is definitely not a goal! Perhaps everyone will naturally migrate at some point and deprecation of the old interface will make sense, but I doubt it, and have no intention to push them in that direction.

From the perspective of reducing maintenance burden, I do think I would like to _rewrite_ the `sns` interface to internally build plots using the objects at some point. But there are enough idiosyncrasies in the `sns` functions that accommodating the full spectrum of behaviors is going to be challenging. And it's independent of user-facing documentation anyway.

> For example, the [swarmplot](https://seaborn.pydata.org/generated/seaborn.swarmplot.html) docs have a nice walk through with lots of example code that a user could probably just copy-paste and have it "just work". I think some equivalent would be invaluable for the so interface.

I'm a little surprised by this comparison because all of the Mark, Stat, and Move objects in the objects interface should have an analogous API page, e.g. here are [so.Bar](https://seaborn.pydata.org/generated/seaborn.objects.Bar.html), [so.KDE](https://seaborn.pydata.org/generated/seaborn.objects.KDE.html), and [so.Dodge](https://seaborn.pydata.org/generated/seaborn.objects.Dodge.html).

> Reproducing the [examples](https://seaborn.pydata.org/examples/different_scatter_variables.html) gallery using so

It is true that the [gallery](https://seaborn.pydata.org/examples/index.html) currently only features the function interface. I'm not sure what the best path forward is there. It could be nice to show both ways of making each example plot, but currently I estimate that only ≈1/3 of the examples in the gallery can be produced with the objects interface. That will grow over time (e.g. I anticipate supporting box/violin-type plots, heatmaps, contours, etc.) but probably not to 100% (I doubt the objects interface will ever offer a way of replacing `clustermap` — but then again I'd like to spin that out of seaborn anyway). And at the same time, there are already lots of things you can do with the objects that you can't (easily) do with the function interface.

If nothing else, I bet people would find a third party "here's how to make (some) of the seaborn gallery with the objects interface" post useful. In the official documentation, overall I'm inclined to keep the objects interface somewhat segregated until it becomes more stable / covers more use cases.

> Rewriting the [tutorial](https://seaborn.pydata.org/tutorial/introduction.html) to use the so interface.

I also expect that the amount of the tutorial devoted to the objects interface will expand, but again probably not through replacement. I don't think that the current tutorial organization of relational/categorical/distribution plots makes sense as a framework for discussing the objects. It is more likely that the concepts in the objects interface, something roughly like the current H2 level organization, will expand and begin to merit their own pages.

**Comment by beyarkay** [comment]
Hey!

> This is definitely not a goal!

Okay TIL, I had kinda assumed it would be a burden to support both, but what you say about eventually migrating the `sns` interface to use the objects interface makes a lot of sense.

> I'm a little surprised by this comparison because all of the Mark, Stat, and Move objects in the objects interface should have an analogous API page, e.g. here are [so.Bar](https://seaborn.pydata.org/generated/seaborn.objects.Bar.html), [so.KDE](https://seaborn.pydata.org/generated/seaborn.objects.KDE.html), and [so.Dodge](https://seaborn.pydata.org/generated/seaborn.objects.Dodge.html).

I guess this is maybe more a function of how I'm not used to the object interface and docs. For example, to make this plot from the docs:

![](https://seaborn.pydata.org/_images/objects.Bar_13_0.png)

I don't (yet!) think in terms of "Make a `Plot` with body mass, species and sex, add a `Bar`, add a `Range`", I'm more thinking the caveman-style "bar plot with lines". I'm 100% on board with the grammar of graphics style plotting that's been introduced with the `so` interface. However, when I picture in my head the plot I want and then try to write some code with the objects interface, I find myself drawing up a blank. 

I think this might be more to do with my lack of familiarity with the objects interface rather than anything else.

> I estimate that only ≈1/3 of the examples in the gallery can be produced with the objects interface

Do you expect the code required to reproduce that 1/3rd to change in the coming years? If not, there's no technical reason (as far as I can tell?) not to start adding `so` style examples to the gallery, or to start adding code to the existing `sns` plots to show how to recreate them using the `so` interface. 

I love the gallery by the way. And in general the massive number of examples you've got on the website. Seeing code examples similar to what I want to create that I can then modify to my means is _really_ useful.

Adding `so` plots to the gallery would (IMO) be a good way to show off what it can do.

> In the official documentation, overall I'm inclined to keep the objects interface somewhat segregated until it becomes more stable / covers more use cases

Ahh okay I understand now. This is fair. I'll close the issue, thanks for clarifying!


PS: Is there an estimated release date for seaborn v0.13? I'm eyeing the `native_scale` parameter in the rest of the categorical plots with the excitement of a 12 year old in a candy store.
