### ISSUE TITLE
`seaborn.objects` really slow when indices are all equal

### ISSUE THREAD

**Issue by paw-lu** [mwaskom/seaborn#3444]
## Problem

When using `so.Plot`, if the DataFrame happens to have equal indices, seaborn will take a _really_ long time to run.

## What I expect

Similar runtime to when indices are unique, or as traditional seaborn functions like `sns.scatterplot`

## Example

This snippet just hangs for a really long time.

```python
import pandas as pd
import seaborn.objects as so

(
    pd.DataFrame({"a": [1] * 100, "b": [2] * 100}, index=[0] * 100)
    .pipe(so.Plot, x="a", y="b")
    .add(so.Dot())
)
```

## Info

- seaborn: 0.12.2
- python: 3.10.9

---

`seaborn.objects` has been pretty fun to use. Thanks for sharing it!

**Comment by thuiop** [comment]
I'm impressed this works at all ; seaborn objects API usually throws an error message when there are duplicate indexes (see #3354).

**Comment by paw-lu** [comment]
I'm not sure it actually does work. It hangs so long I give up on waiting for it.

**Comment by mwaskom** [comment]
Yep this is fundamentally the same as in the linked issues: some internal seaborn operations not working well with a non-unique index (I don't know exactly how to describe pandas scaling behavior with duplicate indices but we have previously described examples of heavily duplicate indices being extremely slow: https://github.com/mwaskom/seaborn/issues/2652).

I'm going to close here (and will weigh in with some thoughts on the other issue) since it's the same root cause even if it manifests differently. Thanks for the clear description and simple reprex.
