### ISSUE TITLE
Legend line is incorrect

### ISSUE THREAD

**Issue by JulienManulife1** [mwaskom/seaborn#3543]
Hello, so I am not sure where to post specifically. This is a bug as of Pandas 2.0.0 I believe, and is when Matplotlib plt legend is called on what I've tested so far being the relplot alone.

pandas = 2.1.2
matplotlib= 3.8.1
seaborn=0.13
![image](https://github.com/mwaskom/seaborn/assets/105056217/9bae593b-d01e-4dfa-b7d6-381ab927b029)

```
import matplotlib.pyplot as plt
from matplotlib.pyplot import *
import seaborn as sns
import pandas as pd

fmri = sns.load_dataset("fmri")

fig = plt.figure(figsize=(12, 10))
sns.set()
ax=sns.relplot(data=fmri, x="timepoint", y="signal", col="region",
    hue="event", style="event", kind="line",legend=False)
plt.legend(bbox_to_anchor=(0,-0.2,1,0),title='', frameon=False, loc="lower center"
           , labels=fmri.event.unique(), ncol=fmri.event.nunique(),handletextpad=0.2,columnspacing=.8)
```

**Comment by mwaskom** [comment]
This is not a bug in any library, just a consequence of matplotlib’s “magic” legend creation not doing what you expect. When you call legend without providing explicit artists, it grabs the first two artists that are attached to the axes; in this case that happens to be the first line and it’s confidence interval because that is the order that seaborn adds things to the plot.

I’m going to close because there is no action to be taken on the library side here and ample discussion of how to customize the legend in the docs and on eg stackoverflow.

**Comment by JulienManulife1** [comment]
Thanks. I brought this up actually as I had experienced it when I updated pandas so it was sudden unexpected behavior. Reverting pandas caused the lines to be drawn correctly

**Comment by mwaskom** [comment]
The point is that the specific ordering of artists in the matplotlib artist list is an implementation detail, so it’s risky to rely on it, as you do when calling legend() without a list of artist handles. I really wish this “feature” didn’t exist in matplotlib — it’s convenient for interactive, direct use of matplotlib, but it makes it too easy to get incorrect results (which may or may not be noticeable as they are here). I personally really urge you not to use it. But there’s not much seaborn can do about that.
