### ISSUE TITLE
violinplot causes Matplotlib warning

### ISSUE THREAD

**Issue by oliverdain** [mwaskom/seaborn#3545]
The following code causes a Matplotlib warning:

```py
  preds = np.empty((len(results),), dtype=np.float32)
  targs = np.empty((len(results),), dtype=np.float32)
  
  # code to fill in preds and targs here

  sns.violinplot(x=targs, y=preds, cut=0)
```

Clearly `preds` and `targs` are numeric as they're `float32` numpy arrays. But the call above causes:

```
INFO:matplotlib.category:Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
```

I actually get 2 such errors per call to `violinplot`.

I'm using Seaborn 0.13.0 and Matplotlib 3.8.1.

**Comment by mwaskom** [comment]
See https://github.com/matplotlib/matplotlib/issues/23422

**Comment by mwaskom** [comment]
In short, you're not doing anything wrong here, seaborn is also not doing anything wrong here, however it is tripping a matplotlib message warning it that it _might_ be doing something wrong, and you are seeing that message because you have your logging configured to show INFO level logs from matplotlib. This isn't a great UX and I do wish upstream would be more receptive to the arguments I'm making in the linked issue about the approach to providing this warning being confusing / hard to work with, but there's not much seaborn can do to work around it. (Save for some non-standard manipulation of the matplotlib logging configuration that I'm not too enthusiastic about pursuing).

**Comment by oliverdain** [comment]
Bummer, but that makes sense. Thanks for the quick reply.

Closing.
