### ISSUE TITLE
Problems when setting positions in boxplot() (mainly on log-scale axis)

### ISSUE THREAD

**Issue by leoluecken** [mwaskom/seaborn#3566]
Hey everybody,
Thanks for adding `native_scale` to boxplot in 0.13!! I've been waiting for this! :)
Now, I tried to do some tweaking dodging boxpositions manually, and encountered the following (I'm on 0.13.0, and matplotlib 3.7.2):

My code:
```python
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    "x":[0.1,0.1,0.1,0.1,1,1,1,1],
    "y":[1,2,3,4,1,2,3,4]
}

xvals = sorted(set(data["x"]))

# logscale dodging
boxpositions = [np.exp(np.log(x)+0.5) for x in xvals]

fig, ax = plt.subplots()
ax.set_xscale("log")
sns.boxplot(data, x="x", y="y", width=0.3, native_scale=True, positions=boxpositions, ax=ax)
plt.show()
```

produces the following image:

![image](https://github.com/mwaskom/seaborn/assets/6482401/c8823211-8a36-4fb5-80f7-6dd419a40781)

This doesn't get better when trying to use log_scale instead of native_scale:

```python
sns.boxplot(data, x="x", y="y", width=0.3, log_scale=True, positions=boxpositions, ax=ax)
```
→

![image](https://github.com/mwaskom/seaborn/assets/6482401/87bbfb63-c96d-46d2-b010-d0b089c94a54)

It works more or less fine on linear scale:

```python
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    "x":[0.1,0.1,0.1,0.1,1,1,1,1],
    "y":[1,2,3,4,1,2,3,4]
}

xvals = sorted(set(data["x"]))

# linscale dodging
boxpositions = [x+0.5 for x in xvals]

fig, ax = plt.subplots()
sns.boxplot(data, x="x", y="y", width=0.3, positions=boxpositions, ax=ax)
plt.show()
```

Only the xlim is not updated:

![image](https://github.com/mwaskom/seaborn/assets/6482401/2bc05e99-bb88-44ed-866d-823c3392cd49)

Cheers,
Leo

**Comment by mwaskom** [comment]
The problem is that `positions` is a keyword argument of the underlying matplotlib function. Matplotlib itself has no idea how to draw a boxplot on a log axis, seaborn needs to do all of the positional adjustments itself to make things like dodging on a log scale work (it's quite complicated and annoying).

I don't think there's any simple way to make this work. It's possible that seaborn should just reject the `positions` keyword since it conflicts with the operations it is doing.

**Comment by leoluecken** [comment]
Hmm. At least the "center lines" were positioned correctly, it seems. 

And seaborn makes nice boxwidths in logscale when I use native_scale without dodging:

```python 
fig, ax = plt.subplots()
ax.set_xscale("log")
sns.boxplot(data, x="x", y="y", width=0.3, native_scale=True, ax=ax)
```
![image](https://github.com/mwaskom/seaborn/assets/6482401/a052f3f2-b028-408b-b718-19c021022009)

That seems to happen in seaborn, doesn't it? Because matplotlib scales boxwidth logarithmically as it seems. At least,
```python 
fig, ax = plt.subplots()
ax.set_xscale("log")
ax.boxplot([[1,2,3,4], [1,2,3,4]], positions=[0.1, 1.0])
```
gives

![image](https://github.com/mwaskom/seaborn/assets/6482401/adaf7ac7-f5ea-401f-bdcf-43d51ca2534a)

That means, the math must be somewhere in there already :)

**Comment by mwaskom** [comment]
> That seems to happen in seaborn, doesn't it? 
>
>That means, the math must be somewhere in there already :)

Not really sure I understand your question here. Yes, seaborn is handling setting the widths properly (for both the boxes and caps) on a log scale because matplotlib does not know how to. To accomplish that, it needs to modify the artists after matplotlib creates them. It does not need to modify the vertical line because that is width-independent. Feel free to look at the code if you would like to know more.

My point is that seaborn already has a way to manage the positions of the boxes the categorical axis (i.e., the value of the x/y variable) and juggling the separate `positions` argument that matplotlib offers would add a lot of complexity without clear benefit. I don't really understand why you need to use `positions` to accomplish what you want to do now that `native_scale` exists; can't you just modify the `x` data?

**Comment by leoluecken** [comment]
The problem in my case is that I want to do a boxplot for two categories side-by-side, but they don't live on the same y-scale. So I am using two different axes (via ax2=ax.twinx()) to plot them. Otherwise I could use the hue parameter, of course.

But I understand that it is perhaps not seaborn's job to support these kind of hacks. 

I will see if I can find the code which dodges the bars on native scale in case of several categories when using the hue keyword. This would just do, what I need here, I think.

**Comment by mwaskom** [comment]
I’m still not following why you can’t apply your positional adjustment to the x data.

Alternatively, you could use hue and hue order to dodge across the twinned axes.

**Comment by mwaskom** [comment]
e.g something like

```python
tips = sns.load_dataset("tips")
x = 10 ** tips["size"]
f, ax1 = plt.subplots()
ax1.set_xscale("log")
ax2 = ax1.twinx()
sns.boxplot(tips, x=np.exp(np.log(x) - .45), y="total_bill", native_scale=True, width=.4, ax=ax1)
sns.boxplot(tips, x=np.exp(np.log(x) + .45), y="tip", native_scale=True, width=.4, color="C1", ax=ax2)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/35298adf-1a24-4cc7-95ab-a74fc4c7f417)

is what you're looking for, no?

**Comment by mwaskom** [comment]
Alternatively,

```python
tips = sns.load_dataset("tips")
x = 10 ** tips["size"]
f, ax1 = plt.subplots()
ax1.set_xscale("log")
ax2 = ax1.twinx()
sns.boxplot(tips, x=x, y="total_bill", hue=0, hue_order=[0, 1], dodge=True, legend=False, native_scale=True, ax=ax1)
sns.boxplot(tips, x=x, y="tip", hue=1, hue_order=[0, 1], dodge=True, legend=False, native_scale=True, ax=ax2)
```
![image](https://github.com/mwaskom/seaborn/assets/315810/a44df24e-8295-4bf7-8989-a47c07a22293)

**Comment by leoluecken** [comment]
Yes, you're right, of course! I didn't get that the first time - sorry! Thanks a lot for looking into this in such detail!
