### ISSUE TITLE
clustermap appears to cast arrays to numpy dtype float64 by default

### ISSUE THREAD

**Issue by matt-sd-watson** [mwaskom/seaborn#3596]
I am attempting to run `sns.clustermap` on an array of size (182440, 34) and continue to get the following error:

```
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 124. GiB for an array with shape (16642085580,) and data type float64
```

However, the error persists even after I cast the expression array into a lower byte dtype:

```
low_mem = anndata.AnnData(np.array(adata.X, dtype=np.float32))
sns.clustermap(low_mem.X)
```

Is the matrix passed to `clustermap` always cast into float64, or is this logic occurring in the scipy `pdist_fn` step?

**Comment by mwaskom** [comment]
It would not surprise me to learn that there were a cast to float somewhere. It's really hard to say without seeing a reproducible example / full traceback, but the shape in your error message doesn't correspond to the shape of your data so that makes me think it's part of the scipy algorithm.

I'll also note that a clustermap with 100k rows is going to be misleading in the sense that your monitor will only have 1k or so pixels to show it with, so it's going to get very aggressively downsampled.

**Comment by matt-sd-watson** [comment]
This has been addressed in the scipy repo where the casting occurs: 
https://github.com/scipy/scipy/issues/19707
