### ISSUE TITLE
Add Color Universal Design palette

### ISSUE THREAD

**Issue by mbhall88** [mwaskom/seaborn#3631]
Hi,

I think the [Color Universal Design](https://jfly.uni-koeln.de/color/) colorblind-friendly palette would be a great addition to seaborn.

I have created a repository with some examples of the palette you can take a look at: <https://github.com/mbhall88/cud>

Not sure if this request is better off at matplotlib or not though?

**Comment by mwaskom** [comment]
The seaborn `colorblind` palette is actually based on this: https://gist.github.com/mwaskom/b35f6ebc2d4b340b4f64a4e28e778486

Although there were some changes made so that it is more of a "colorblind-friendly variant of the seaborn qualitative palette family" (i.e., the colors were reordered, two colors were added, and the shades were adjusted somewhat).

It might make sense to add the literal CUD color values in the original order to matplotlib as a categorical colormap though!

**Comment by mbhall88** [comment]
Cool. Thanks for link. The additions make sense, though it seems black was replaced?

I'll open a request on matplotlib.
