### ISSUE TITLE
What to do with missing values in heatmaps

### ISSUE THREAD

**Issue by sdvillal** [mwaskom/seaborn#375]
Running this snippet:

```python
import seaborn as sns
import numpy as np
import pandas as pd

df = pd.DataFrame(data={'a': [1, 1, 1],
                        'b': [2, np.nan, 2],
                        'c': [3, 3, np.nan]})

sns.heatmap(df)
```

We get something like this:

![missing-get-small](https://cloud.githubusercontent.com/assets/642252/5127852/43a01d08-70d7-11e4-8798-930b3e1763ed.png)

Missing values are happily assigned "the color of the minimum" in the color bar. I wonder if this is a good default or if missing values should be treated differently. I would go for "treating them differently by default" and then the question would be how (maybe having a *missing_color* parameter and issuing a warning if the color is in the colormap/colorbar).

**Comment by jm-contreras** [comment]
+1

**Comment by JWarmenhoven** [comment]
+1 
I agree. Masking works fine and should perhaps be default for missings. There is indeed an issue with masking when used in combination with annotations as jm-contreras mentioned.

**Comment by mwaskom** [comment]
Having looked into this a bit, the issue seems to be that `plt.pcolormesh` doesn't treat `np.nan` as "missing", and instead assigns those cells the "under" value in the colormap. E.g.:

```python
cmap = sns.cubehelix_palette(as_cmap=True, light=.9)
sns.heatmap(flights_missing, cmap=cmap)
```
![pwz xybmyopqlbsupejin2a3wcfmallix4rdkmsuogvuyrjxctelklsfzgxs5luruzskir1ero7jeldxmqusvix x8cv eomwcuqwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/315810/7334558/d56fecc4-eb4b-11e4-98ac-ab6a05942a11.png)

```python
cmap.set_under(".5")
sns.heatmap(flights_missing, cmap=cmap)
```
![kz5akpwicj4jak8 jvl5cfqxhv7ruanyc7gncz lvqsmozz7flxsgilqooyt ymc 3utmskmtflnwzingf dxwozo6tocxypckqytysuus1evm7jikdretuyrjxctelklsfzgxs5luruzskir1kf8h 1lnqm15jhcaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/315810/7334561/e7910cc6-eb4b-11e4-984c-16de18bb3c21.png)

Based on this, it's not really clear what the best thing to do in `heatmap` is. However, note that from a user-perspective you can use the `mask` parameter to be safe (But see #512):

```python
sns.heatmap(flights_missing, cmap=cmap, mask=flights_missing.isnull())
```

![wczboeovfjeuwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/315810/7334565/1dd35852-eb4c-11e4-9f35-93bc7b081a7d.png)

**Comment by mwaskom** [comment]
> There's a masking argument that works pretty well, but it could be improved in at least two respects. First, it could be useful to add an option that makes masked out cells the same color as the image background (this would be especially pleasing for heat maps of upper-triangular or lower-triangular matrices).

@jm-contreras I think this already happens? Perhaps you mean something different:

```python
with sns.axes_style("white"):
    sns.heatmap(flights_missing, cmap=cmap, mask=flights_missing.isnull())
```

![bbvgncetu9iaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/315810/7334575/6e9226ba-eb4c-11e4-8f88-d4d7510c2349.png)

**Comment by mwaskom** [comment]
> Yes, I think that missings are masked-out should be the default behavior. It probably would suffice to create / "or" the mask with np.isnan in _HeatMapper.

@sdvillal  This could work but it does raise the issue of what to do when a user supplies a mask. Take the union of the supplied mask and the null mask? Ignore the missings and just use the supplied mask? Either way feels like it will surprise people.

**Comment by mwaskom** [comment]
A broader question is why `pcolormesh` behaves this way and if it is intentional. Other "matrix" functions in matplotlib (e.g. `imshow`) treat `nans` as missing out of the box.

**Comment by mwaskom** [comment]
See #523, I decided to take the option advocated by @sdvillal and automatically include missing values in the mask. Sorry it took so long to get to this.

**Comment by mwaskom** [comment]
Closed with #523

**Comment by jolespin** [comment]
Great thread.  I learned a lot.

**Comment by jm-contreras** [comment]
@mwaskom That's exactly what I meant. It just wasn't clear that the heat map code needed to be indented within the statement `with sns.axes_style('white')`. Thanks for sharing!

**Comment by pnandigr** [comment]
Hello, is there a way to display only the non-zero values for a heatmap plot with seaborn? I understand that 'annot=True' will display values for each grid point. However, I want to show only the values that are non-zero.

**Comment by JWarmenhoven** [comment]
I am not sure you can suppress the annotation of specific values. Perhaps you can use a mask if you do not want to plot zero values at all?
```
mask = data == 0
ax = sns.heatmap(data, annot=True, mask=mask)
```

**Comment by AnshulRaghav** [comment]
Try this:

`sns.heatmap(df.isnull(),cbar=False,cmap='viridis')`
