### ISSUE TITLE
Marker size for lmplot

### ISSUE THREAD

**Issue by arranger1044** [mwaskom/seaborn#419]
How can I change the marker sizes for a lmplot created from a dataframe?

**Comment by mwaskom** [comment]
`lmplot` kwargs get passed through to `regplot`, and `regplot` has a `scatter_kws` parameter that gets passed to `plt.scatter`. So you want to set the `s` parameter in that dictionary, which corresponds (a bit confusingly) to the squared markersize. In other words,

```python
sns.lmplot("x", "y", data=data, scatter_kws={"s": 100})
```

By the way, this kind of usage question is slightly more at home on [StackOverflow](http://stackoverflow.com/), because I'm sure other people will wonder this and the search functionality/google prominence of stackoverflow questions is a bit better than github issues. Just use the `[seaborn]` tag and I'll see it.

**Comment by arranger1044** [comment]
You are right, this is not the best place, however I could open an issue to make a simpler and more intuitive documentation about this : )
Thank you for your efforts and work.
