### ISSUE TITLE
"transform" kwargs for box/violin plots

### ISSUE THREAD

**Issue by phobson** [mwaskom/seaborn#432]
Curious if you have any interest in transformation parameters for box and violin plots. 

For example, if you had, oh I don't know, lognormally distributed pollutant concentrations in water, you might want to compute the KDEs or boxplot stats in log space (i.e., `transformin = lambda x: np.log(x)`, but still show the plots in native units with or without a log-axis (i.e., `transformout = lambda x: np.exp(x)`.

It's easy enough to simply log-transform your data and label the axes as such. You could even use a fancy matplotlib `FuncFormatter` to fix all the major tick labels. But the transformations aren't always `np.log`/`np.exp`. For example, the discussion [here](http://stats.stackexchange.com/questions/112705/boxplots-with-lognormally-distributed-data) indicates that some folks even draw boxplot on the square-roots of their data. So perhaps a generalized transformation system could be useful.

I think I see in both `_BoxPlotter` and `_ViolinPlotter` where these transformation would need to take place. But, if there's no interest in this, I'll shelve it and get back to the documentation I've been meaning to write.

**Comment by mwaskom** [comment]
I played around with this a bit and then ended up punting because it seemed very complicated. But yeah I agree in general plotting these distributions in some transformed space is useful and it would be nice to make that as easy as possible in seaborn.

For boxplots specifically, I think we'd need to compute the boxplot statistics ourselves in the intermediate space, and then transform those back out? (I'm actually a little confused about why going into and then back out of log space would influence how the boxplot gets drawn, since they're just order statistics, but maybe it influences the whisker range and what counts as an outlier?) IIRC you added the ability to draw a boxplot from the statistics in 1.4, but that might be a bit of an issue since we aim to support 1.1+ (I think; the real rule is whatever keeps the debian stable builds happy). Of course it wouldn't be that hard to draw boxes ourselves, but we'd lose (or have to reimplement) stuff like notches, which we currently get for free.

Let's revisit this after I finish unifying box/violin/stripplots with bar/pointplots, at which point the architecture will be a lot more stable.

**Comment by phobson** [comment]
> but maybe it influences the whisker range and what counts as an outlier

That's exactly what it does, and the difference can be pretty dramatic.
![bxp](https://cloud.githubusercontent.com/assets/1163939/5904560/4d522cd8-a53e-11e4-8f0e-920f1d09a7a3.png)

So yeah -- you punting on it doesn't give me much confidence that I'll figure it out. But I'll take a stab at nonetheless and let you know if anything magical happens.

**Comment by phobson** [comment]
I've come around to thinking that you should transform the data, plot that, and label the axes as such. It's much less ambiguous that way.

I'm going to close this.
