### ISSUE TITLE
Add documentation about 'tidy data' and expected DataFrame format

### ISSUE THREAD

**Issue by Bercio** [mwaskom/seaborn#442]
It's kind of hard for a statistic's noob to understand what col,row,hue do and how they do it by browsing the tutorials. I know there's a quoted paper which is helpful if a little hidden, but for example just showing how the datasets you use in the examples(tips, anscombes, etc.)  are formatted would be of great help.

**Comment by mwaskom** [comment]
I've thought about doing something like this, although it never seemed like a great use of time since I don't think I could do a better job explaining it than Hadley does in that paper. But do note that you can always load the example datasets yourself with `sns.load_data` (requires a network connection as it fetches from the internet) and then look at how the data are structured to get a better sense.

**Comment by Bercio** [comment]
Thanks! I still think a snippet of a dataset would help understand the concept, like just put tips.head() before the example graphs in the page "Plotting on data-aware grids"

**Comment by mwaskom** [comment]
Closed with #566
