### ISSUE TITLE
direct control of factorplot figure width

### ISSUE THREAD

**Issue by tku137** [mwaskom/seaborn#444]
Up to now, you can not define the figure width and height of a factor plot directly. Instead you define the figure height with the "size" argument and the aspect ratio of facet width to facet height.

This also leads to ignored settings like set_context() or matplotlib.figure(figsize=(x,y)) or setting rcParams in any way. 

Example notebook showing the effects: https://gist.github.com/tku137/2c81cb603ef4198a783c

Using set_context() and the like to control factorplots would be nice. Defining the figure width and height directly would be more convenient, because it makes no sense to go over the facet ratio. One has to calculate this ratio backwards when trying to set the width.

**Comment by mwaskom** [comment]
It's going to be confusing one way or the other. Personally I think it makes more sense to specify the size of each facet and then the overall figure size is a function of the number of levels on the faceting variables.

Why do I think this is better? Because you generally do (or should do) a lot more plotting for exploratory analysis than for "final products" that might need to have a particular figure size (i.e. to fit onto a talk slide or into a paper). So from my perspective, the way it's done minimizes the overall amount of thinking about boring things like figure size. (Also the fact that IPython scales down large images in the notebook cell output also helps because past a certain size you get automatic figure scaling). And for exploratory analysis, you want to be able to iterate quickly over a number of different analyses and  IMO it's more useful to have facets that are the same size than to have overall figures that are the same size in that context. Then when you're in a situation when you need to have something that's exactly a certain size overall, you a) know precisely what you want and b) can afford to take a second and work through the calculation.

So, basically, I disagree.

**Comment by shoyer** [comment]
I agree with @mwaskom here. I like facets that are consistently sized, and more importantly, have a sane default size. The default matplotlib figure size is way too small for multi-panel plots.

**Comment by tku137** [comment]
Well ok, now I totally get @mwaskom 's point. Unfortunately, I just started using python to get away from Madlab (pun intended) and this was my very first "real" usage (except playing around) of seaborn to get some nice graphs for a grant I am working on. So yeah, my point of view was generating the final graph only, not considering the more important stuff that one can do with exploratory data analysis. I knew already what has to be shown and did not think of the usual way to get there.

Anyway, I am still not quite comfortable with the way this affects set_context() functionality. IMO set_context() is there to set certain properties of figures for publishing like a "poster" or "talk". It is just what I assume. So I do not understand why set_context() controls plots and boxplots etc in a very convenient way for publication ready pictures, but not a factorplot.

IMO it would be awesome if there could be a parameter that switches size and aspect of a factorplot to control the figure size and not the facet size. Then if one sets the context e.g. to "poster", every graph would look the same, because IMO this is the way you (or at least me) would expect what set_context() is doing.

I hope a made my point of view clear here. It is just the way factorplot ignores some settings which gets me the feeling of inconsistancy.

**Comment by mwaskom** [comment]
> Anyway, I am still not quite comfortable with the way this affects set_context() functionality. IMO set_context() is there to set certain properties of figures for publishing like a "poster" or "talk". It is just what I assume. So I do not understand why set_context() controls plots and boxplots etc in a very convenient way for publication ready pictures, but not a factorplot.

It does for the most part: the text size, line widths, etc. parameters are all used, it's really just the figure size that is ignored by the higher-level functions. But, in my experience, most "publication-ready" figures aren't going to be well served by using one default overall figure size. The size of each figure should be tailored to maximize the information shown in the space allotted by slide/poster layout or journal format.

In any case, I think the kind of behavior you're proposing would introduce a considerable amount of complexity without much tangible benefit, so I'm going to close this.
