### ISSUE TITLE
seaborn with pylab inline?

### ISSUE THREAD

**Issue by gliptak** [mwaskom/seaborn#451]
Running in ipython3:
```
%pylab inline
import seaborn as sns
```
displays this following warning:
```
Populating the interactive namespace from numpy and matplotlib

WARNING: pylab import has clobbered these variables: ['figure']
`%matplotlib` prevents importing * from pylab and numpy
```

Is there another recommended way to invoke/import?

Thanks

**Comment by pylang** [comment]
Have you tried  IPython's `%matplotlib inline`?  This lets you plot in a notebook vs. a popup.  All other modules can imported explicitly, such as `pyplot`, e.g.:

`import matplotlib.pyplot as plt`
`import seaborn as sns`

`%matplotline inline`

`pylab` is being used less due to poor reproducibility of results across different systems.

**Comment by mwaskom** [comment]
Yes, this is unrelated to seaborn. See [this blog post](http://carreau.github.io/posts/10-No-PyLab-Thanks.ipynb.html) for more information on why `%matplotlib inline` is preferred over `%pylab inline`.

**Comment by gliptak** [comment]
Thank you both.
