### ISSUE TITLE
Functionality in PairGrid

### ISSUE THREAD

**Issue by josepablog** [mwaskom/seaborn#461]
I love the stacked histogram functionality for the diagonal frames of PairGrid (which, btw, I don't think it's available independently).

Unfortunately, the documentation says that the axis are arbitrary:

> It’s possible to plot a different function on the diagonal to show the univariate distribution of the variable in each column. Note that the axis ticks won’t correspond to the count or density axis of this plot, though.

I wished the stacked histogram was available independently, or, that the axis could be shown for the diagonal.  It is pretty frustrating for the histogram axis to neither be the count or density. What is it then?!!

**Comment by mwaskom** [comment]
The stacked histogram is just vanilla matplotib: `plt.hist(..., histtype="barstacked")`. The reason the axes are arbitrary is because they correspond to the y variable in the scatterplots; there is no way to cleanly show both the axes for the y variable and for the histogram (which will be counts of the x variable). But it's easy to show such a plot directly in matplotlib.
