### ISSUE TITLE
Factor plot does not completely obey axes specification

### ISSUE THREAD

**Issue by fonnesbeck** [mwaskom/seaborn#488]
I'm trying to generate a `factorplot` on a specific set of axes, which I generate using matplotlib's `subplots` function.

    import seaborn as sb
    sb.set_context("talk", font_scale=0.8)
    sb.set_style("white")

    f, axes = plt.subplots(figsize=(14,8))
    g = sb.factorplot("Age", "S", "Confirmation", S_age_june, kind="box",
                       palette="PRGn", aspect=1.25, linewidth=0.3, fliersize=0, ax=axes)
    g.despine(offset=10, trim=True)
    g.set_axis_labels("Age Group", "Susceptibles");

However, running this code in IPython generates an extra, blank, partially-formatted set of axes below the plot of the data (which has not received the formatting specified to `g`):

![](http://d.pr/i/8wxN+)

![](http://d.pr/i/1hCTq+)

Running 0.6.dev on Python 3.4 (Homebrew).

**Comment by fonnesbeck** [comment]
Solved my particular problem using `size` and `aspect`, but nevertheless I would expect that once `ax` is specified for `g` that all subsequent methods applied to `g` would operate on those axes.

**Comment by mwaskom** [comment]
Indeed, we can say more strongly: factorplot does not *at all* obey axes specification. See [here](http://stackoverflow.com/questions/23969619/plotting-with-seaborn-using-the-matplotlib-object-oriented-interface) for an explanation.

If you just want to set up the axes that way so you can have a figure with a specific size, you can pass `size=8, aspect=14 / 8.` to `factorplot`. Note also that since you're on 0.6 dev you can do hue grouping in [`sns.boxplot`](http://stanford.edu/~mwaskom/software/seaborn-dev/generated/seaborn.boxplot.html#seaborn.boxplot), which can plot onto an existing Axes.

**Comment by fonnesbeck** [comment]
OK, I'm satisfied. Thanks.
