### ISSUE TITLE
Allow reversing cumulative density when using kdeplot in distplot

### ISSUE THREAD

**Issue by lbeltrame** [mwaskom/seaborn#491]
Rationale: I can invert the cumulative histogram in `matplotlib`, so it would be nice if I could reverse also the result of `kdeplot` when using `distplot`.

**Comment by mwaskom** [comment]
OK, but, why would you want to do that?

**Comment by lbeltrame** [comment]
> OK, but, why would you want to do that?

Replicating this plot: 
http://master.bioconductor.org/packages/release/bioc/vignettes/TEQC/inst/doc/TEQC.pdf 
(page 13 of the PDF), unless there are better ways to do so.

**Comment by mwaskom** [comment]
I'm not sure what that is showing. A cumulative density function has a specific definition and I'm not sure what would be gained from showing a "reversed cumulative density". Though you can always reverse matplotlib axes and relabel the ticks if you really want to.

**Comment by lbeltrame** [comment]
That's fine, I found a clean solution using statsmodels, so it should be good enough for me.

**Comment by erinboyle** [comment]
I think this has real use.  I'm trying to show what fraction of clients at my company have accumulated at least N datapoints.  Cumulative in the normal direction is showing me how many clients have accumulated at _most_ N datapoints -- much less relevant to the question we're interested in.  I'm using `plt.hist` instead since they offer reverse, but far prefer seaborn's formatting.
