### ISSUE TITLE
corrplot does not show cell coordinates with nbagg backend

### ISSUE THREAD

**Issue by michaelaye** [mwaskom/seaborn#495]
I was trying the gallery plot from [here](http://stanford.edu/~mwaskom/software/seaborn/examples/many_pairwise_correlations.html)
and noticed that while using the nbagg backend, that the x and y displayer just stays empty, so not even the cursor coordinate is shown.

The jointplot from [here](http://stanford.edu/~mwaskom/software/seaborn/examples/joint_kde.html) works fine, so it seems that there's is no general nbagg problem.

IPython version: 3.0.0
Python 3.4
Seaborn: 0.5.1

**Comment by mwaskom** [comment]
Does `heatmap` work? I'm probably going to deprecate and remove corrplot as it is redundant and generally inferior.

**Comment by michaelaye** [comment]
Nope, same problem.

**Comment by mwaskom** [comment]
I'm actually not completely sure I understand the problem, as I don't use nbagg. A better comparison would be with `plt.imshow` (what `corrplot` uses) or `plt.pcolormesh` (what `heatmap` uses). In other words, is this a seaborn issue or incomplete coverage of the underlying matplotlib functions.

**Comment by michaelaye** [comment]
I did this to check:

```python
import seaborn as sns

flights_long = sns.load_dataset("flights")
flights = flights_long.pivot("month", "year", "passengers")
flights = flights.reindex(flights_long.iloc[:12].month)

plt.imshow(flights.values)
```
and confirmed that the x,y indicators work in this case.

**Comment by mwaskom** [comment]
It looks like the x, y are reading from the ticklabels, and so the issue arises when the ticklabels are either missing or string types.

**Comment by mwaskom** [comment]
I think it's fair to call this a matplotlib issue and not a problem with anything seaborn is doing, so I'm going to close.

**Comment by michaelaye** [comment]
I think it's fair then to add to the README that seaborn is not fully supporting the `nbagg/notebook` backend.

**Comment by mdboom** [comment]
What lead you to believe this is nbagg-specific?  I get the same problem with the GtkAgg and QtAgg backends (the coordinates display as simply `x= y=`).

**Comment by WeatherGod** [comment]
The x/y displayer code does not read from ticklabels. By default, it uses the data coordinates of the cursor. Is there some sort of subclassed axes going on here that might inhibit `format_coords()`? Note that the OP noted that joinplots work fine.

**Comment by mwaskom** [comment]
I can easily make this happen without anything to do with seaborn:

![screenshot 2015-03-31 12 41 04](https://cloud.githubusercontent.com/assets/315810/6927598/4a31811a-d7a3-11e4-8eb8-21983231e2ee.png)

Hence, this does not appear to be a seaborn issue.

**Comment by mwaskom** [comment]
This was done on on tmpnb.org, so feel free to try for yourself...

**Comment by michaelaye** [comment]
@mdboom It works in the inline backend, didn't try out all other backends before the report and I seriously hope that is not expected, otherwise I can just pack it in with my diligent issue reporting. :(

**Comment by mdboom** [comment]
@michaelaye: I'm confused.  The default inline backend is static, so doesn't have a coordinate display.

In any event, this doesn't seem to be seaborn-specific, so it's fine this issue is closed.  Progress over on matplotlib/matplotlib#4302.

**Comment by michaelaye** [comment]
Sorry, I meant it worked in QT for me. See https://www.dropbox.com/s/b0zc0duj7f1spa6/Screenshot%202015-03-31%2013.54.16.png?dl=0

**Comment by tacaswell** [comment]
If you use `set_xticklabels` you are using a `FixedFormatter` for formatting in the tick labels.  This de-couples the tick labels from the data (as near as I can tell by design, you want to use this for things like labeling bar plots where the quantitative value along the axis is meaningless).  By default the message formatter uses the x and y tick label formatters to generate the message, however, `FixedFormatter` only returns a non-empty string in the case where you are _at_ at tick label and passed it's ordinal position along the tick axis (again, by design, what is the label halfway between 'pen' and 'aardvark'?).

If you want to both use `set_xticklabels` (or `FixFormatter`s in general) and the cursor position you need to manually override `ax.format_coord` or `ax.format_xdata` and `ax.format_ydata` to do the right thing for your graph (ex http://matplotlib.org/examples/api/image_zcoord.html).

I am working on a PR to fix this at least for heat maps.

https://github.com/matplotlib/matplotlib/pull/3989 is probably also of interest.

**Comment by michaelaye** [comment]
I'm confused, I wasn't using any set_xticklabels to see the problem?

**Comment by tacaswell** [comment]
Seaborn is in both `heatmap` and `corrplot`.

**Comment by tacaswell** [comment]
@michaelaye Sorry, I should avoid commenting while cranky (due to external circumstances, my trains were all delayed today and I had not had dinner yet...).  I am in a better mood now :smile: 

Yes, in this case 'you' -> 'seaborn'.  Should have been clearer about that.

Does the patch in #496 work for you?
