### ISSUE TITLE
Multiple calls to FacetGrid.set_titles() create misaligned margin titles

### ISSUE THREAD

**Issue by ebellm** [mwaskom/seaborn#509]
I'd like to use multiple calls to FacetGrid.map() to layer multiple outputs.  However, the right margin titles become misaligned, because each call to map() triggers an additional set_titles() call, and it appears the inferred bounding box coordinates are changing.

Here's a minimal working example from v 0.5.1:

```
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style="darkgrid")

tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, row="sex", col="time", margin_titles=True)
bins = np.linspace(0, 60, 13)
g.map(plt.hist, "total_bill", color="steelblue", bins=bins, lw=0)
g.map(plt.hist, "total_bill", color="green", bins=bins, lw=0)
```

The following also reproduces the problem:

```
g2 = sns.FacetGrid(tips, row="sex", col="time", margin_titles=True)
g2.map(plt.hist, "total_bill", color="steelblue", bins=bins, lw=0)
g2.set_titles()
```

![factorgrid_titles](https://cloud.githubusercontent.com/assets/733983/7098598/9540697c-df97-11e4-81e8-d56d90ff37be.png)

**Comment by mwaskom** [comment]
I think this might be somewhat unavoidable, because the margin titles are basially a hack that are just adding matplotlib figure texts (matplotlib doesn't support title object off the side of the Axes). I'm not sure exactly how it could be handled in seaborn, but if you want to avoid this you could remove all the `figure.texts` objects before the final call to `FacetGrid.map`, I think that will work.

**Comment by mwaskom** [comment]
See #440 for an example.

**Comment by ebellm** [comment]
Ah, great!  Calling `plt.setp(g.fig.texts, text="")` before the last `map` call does indeed work around the problem.  Thanks!

**Comment by shoyer** [comment]
Just encountered this issue and @ebellm's hack fixed it for me. Perhaps we could add it to the docs?

**Comment by mwaskom** [comment]
Added two notes on this in #586, hopefully that will help dispel confusion. (Alternatively someone could try to get official support for titling an Axes off the right margin into matplotlib itself, then this issue would go away).

**Comment by mwaskom** [comment]
See #612, which changes how the margin titles are drawn. This improves a few things, including adding a solid background to the text object to hide any texts behind it. So this hack is hopefully no longer necessary.

**Comment by parchd-1** [comment]
This is still an issue in current versions of seaborn and matplotlib. #612 may have improved things for some cases, but I ran into this because the new titles were shorter than the originals.

A comment on #612 says that the hack described here no longer works.

I didn't realise this was a know issue until coming to report it, so my solution for anyone facing this in the future was the following before the final call to set_titles:

```python
for row in g.axes:
    row[-1].texts = []
```

Leaving it there in case it can help anyone in the future.

**Comment by mmmatthew** [comment]
My figure is a heatmap that uses  `annot=True` to display values within the cells. However, the solutions presented here remove all text from the figure before redrawing. Is there a way to only remove the undesired titles and not other text?
