### ISSUE TITLE
TypeError in categorical factorplot on Python 3.4

### ISSUE THREAD

**Issue by fonnesbeck** [mwaskom/seaborn#515]
It appears that the use of `factorplot` for categorical data is broken under Python 3.4 and NumPy 1.10. Using an example from the user's guide:

    import seaborn as sb
    titanic = sb.load_dataset("titanic")
    sb.factorplot("class", data=titanic, palette="PuBuGn_d");

results in the following:

    /usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/numpy-1.10.0.dev_fb898ce-py3.4-macosx-10.10-x86_64.egg/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
         71         ret = ret.dtype.type(ret / rcount)
         72     else:
    ---> 73         ret = ret / rcount
         74 
         75     return ret

    TypeError: unsupported operand type(s) for /: 'str' and 'int'

Running Seaborn 0.6.dev on OS X 10.10.3.

**Comment by mwaskom** [comment]
This was part of the updates to categorical plots for 0.6 (by the way this is not well-advertised but the development version is documented [here](http://stanford.edu/~mwaskom/software/seaborn-dev/)). Because the plots can be drawn horizontally or vertically, you now have to specify `kind="count"` in `factorplot` (or use the axes-level [`countplot`](http://stanford.edu/~mwaskom/software/seaborn-dev/generated/seaborn.countplot.html) function) rather than not passing a quantitative variable.

**Comment by fonnesbeck** [comment]
Ah, sorry. Will bookmark the dev docs!

**Comment by isaac47** [comment]
thanks mwaskom for your help

**Comment by amitbansode** [comment]
Thanks for your help

**Comment by minalb24** [comment]
Thanks for help..code is working fine 👍 

levels=[]  # empty list

for level in deck:
    levels.append(level[0])  # append first letter of data
    
cabin_df=DataFrame(levels)

cabin_df.columns=['Cabin'] # set column =Cabin

sns.factorplot('Cabin',data=cabin_df,palette='winter_d',kind="count")  # Plot data

cabin_df=cabin_df[cabin_df.Cabin!='T']
sns.factorplot('Cabin',data=cabin_df,palette='summer',kind="count")
