### ISSUE TITLE
Getting a colormap from a color_palette as cmap [question]

### ISSUE THREAD

**Issue by ElDeveloper** [mwaskom/seaborn#531]
I was trying to retrieve a colormap by calling `sns.color_palette('Blues')`, but there's no `as_cmap` argument to this function, other functions such as `cubehelix_palette` or `dark_palette` do have that argument, so it is weird that `color_palette` doesn't have it.

Tagging as a question as I know with matplotlib you can do `plt.get_cmap`.

**Comment by mwaskom** [comment]
Yep `color_palette` doesn't have that option as it's focused either on a) palettes that are categorical and hence don't make sense to use as a colormap or b) matplotlib palettes, which are naturally colormaps and best used directly that way.

By the way, you can always (maybe almost always, though I cannot think of any counterexamples at the moment) just pass a string (i.e. `"Blues"`) instead of an actual colormap object to matplotlib or seaborn functions and it will work fine. So I can't see of any reason to provide an option that would just involve more typing!

**Comment by ElDeveloper** [comment]
Thanks makes sense, I did not know about that nifty feature!

The only downside I can see is that darkened maps like "Blues_d" would not work in any of the alternatives (unless of course I'm missing something).

Closing as your answer pretty much resolves the original issue.

**Comment by mwaskom** [comment]
> The only downside I can see is that darkened maps like "Blues_d" would not work in any of the alternatives (unless of course I'm missing something).

No, that's right, but I wouldn't advocate using a colormap made out of those. They're really intended for coloring a relatively small set of plot elements where you want to make sure the lightest elements are visible. But they are really not optimal as continuous colormap because the dynamic range would be quite poor.

**Comment by ElDeveloper** [comment]
Thanks! That's something I didn't think about! :beers:

**Comment by lzkelley** [comment]
I think it would be really nice if something like `sns.hls_palette(8, l=.3, s=.8)` would accept an `as_cmap` parameter. Internally, it looks like that would be trivial by wrapping the return value with a `blend_palette` command, is that true?
