### ISSUE TITLE
Add mpl @image_comparison tests

### ISSUE THREAD

**Issue by phobson** [mwaskom/seaborn#575]
I've gotten pretty handy with writing `@image_comaparison` tests for external (to MPL) libraries lately.

I know the API is in flux, but once that's settled in, I could branch from master and pretty quickly hit all of the high notes before the 0.6 release.

**Comment by mwaskom** [comment]
Sorry for the slow response.

Given my experience with image comparison tests in the old `ipynbdoctest.py` framework, I'd be wary to add those. The test images added a bunch of bloat to the repository and were a pain to keep passing for various reasons (many having to do with the randomness inherent in a lot of seaborn functions). I suppose that there would be some advantages to doing the image comparisons in the unit tests rather than the docs, since there can be more boilerplate code to set random seeds, the figures can be smaller, etc. But I'm currently pretty happy with the approach of testing the matplotlib objects but assume that matplotlib is drawing things properly. Do you think that approach is limited?

**Comment by phobson** [comment]
I think that's perfectly reasonable. My thought was that a few img_comp tests on some basic functions might tip us off if say, a KDE implementation gets refactored in scipy or statsmodels and changed in some way (good or bad).

Just a handful of tests (<20?) that confirm that matplotlib still draws things and the external algorithms still work as expected. 

I myself would argue that we can trust scipy/numpy to catch those things, but I was on a role when I made the issue and it seemed like a small enough effort to be worth it.

**Comment by phobson** [comment]
Any renewed interest in this or should this just be closed? Still happy to do it, but you convinced me it's not really necessary.
