### ISSUE TITLE
Getting min-max ranges with factorplot

### ISSUE THREAD

**Issue by jackjackk** [mwaskom/seaborn#583]
If I use a 100% confidence interval, do I get min-max ranges over the "units" dimension with factorplot?
In this trivial case, is there a combination of parameters I could pass to factorplot to avoid the bootstrap and speed up the procedure?
Thanks

**Comment by mwaskom** [comment]
No, a 100% CI would give you the minimum and maximum of the bootstrap distribution. It's not straightforwardly related to what you want to show, thought it sounds like you might be better suited with a boxplot?

**Comment by mbatchkarov** [comment]
This is something that I'd like to see in `factorplot`, too. Since I'm not sure what the proper names for what I'm talking about are, I'll make up some terminology:
 - *CI of the mean* is what `factorplot` shows currently with `kind='bar'`, which is estimated via bootstrapping
 - *CI of the data* is what the OP is asking for, percentiles of the original data. This is what `boxplot`/`violinplot` show.

I want the latter. A box/violin plot would do, but they are much harder to read as the natural visual grouping by treatment is lost. Compare the two plots below: in the box plot it is not at all obvious that the two leftmost treatments are the same (Add). Also, I find it a bit confusing that the error bars represent one thing if I use `kind='box'` and another if I use `kind='bar'`.


![bar](https://cloud.githubusercontent.com/assets/937114/8575529/5ee6cdf6-2594-11e5-898e-e9af3bca7b51.png) ![box](https://cloud.githubusercontent.com/assets/937114/8575531/5f05daf2-2594-11e5-8932-4e3fd41e9bc7.png)

Would it make sense to have something like `err_style='ci_mean_bars'` vs `err_style='ci_data_band'` for `factorplot`?

I don't think what I want is possible currently. The closest to a solution I've got is 

    sns.factorplot(..., estimator=lambda foo: foo)

This is broken because:
 - the new estimator return a list, not a scalar, so [this](https://github.com/mwaskom/seaborn/blob/8d46524a8514dcab228c9f78a1f9b2be645bfd40/seaborn/algorithms.py#L76-77) would fail
 - would still bootstrap, so kind of slow
 - not sure if estimating *CI of the data* through bootstrapping makes sense
