### ISSUE TITLE
Missing trace in tsplot

### ISSUE THREAD

**Issue by davclark** [mwaskom/seaborn#585]
For some reason, I have data that won't plot with tsplot. It is not very complex at all. I can replicate the problem with this very simply code (the dict-of-dicts is just because of pandas.to_dict()). I'm using 'unit_traces' to show that 2 of the 3 IDs get plotted. I can get a mean of those 2 to appear using `estimator=scipy.stats.namean`.

```
import pandas as pd
import seaborn as sns

df = pd.DataFrame({'AnonID': {0: '3', 1: '3', 3: '1', 4: '1', 5: '2', 6: '2'},
 u'Congruent Error Rate': {0: 0.12777777777777777,
  1: 0.055555555555555552,
  3: 0.061111111111111109,
  4: 0.022222222222222223,
  5: 0.066666666666666666,
  6: 0.050000000000000003},
 'time_dummy': {0: 0, 1: 1, 3: 0, 4: 1, 5: 0, 6: 1}})

sns.tsplot(df, time='time_dummy', value='Congruent Error Rate', unit='AnonID', err_style='unit_traces')
```

The error comes from the irregularity in the index of the DataFrame. For example, this DataFrame is no problem:

```
df = pd.DataFrame({'AnonID': ['3', '3', '1', '1', '2', '2'],
 u'Congruent Error Rate': [0.12777777777777777,
  0.055555555555555552,
  0.061111111111111109,
  0.022222222222222223,
  0.066666666666666666,
  0.050000000000000003],
 'time_dummy': [0, 1, 0, 1, 0, 1]})
```

Super weird. Any ideas? I'm running seaborn 0.5.1, matplotlib 1.4.3, and pandas 0.16.11 - running on  python 2.7 AND 3.4 on OS X 10.10 (Yosemite) in case any of that matters. But it seems that the index shouldn't affect the plot, right?

**Comment by mwaskom** [comment]
This is particularly weird because that *should* end up calling

```python
df.pivot("AnonID", "time_dummy", "Congruent Error Rate")
```

but

```python
sns.tsplot(df.pivot("AnonID", "time_dummy", "Congruent Error Rate").values, err_style="unit_traces")
```

works fine.

Anyway `tsplot` is a bit rough around the edges anyway, and anyway for your case I might suggest `pointplot`:

```python
sns.pointplot(x="time_dummy", y="Congruent Error Rate", hue="AnonID", data=df)
```
![hyspdliintiyaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/315810/8016688/d82184a8-0b9b-11e5-9aa2-e5f31cefb21a.png)

**Comment by davclark** [comment]
Except I am using this as an approach to provide reasonable reports of small group performance, and so the thick overplot of a mean over the individual traces makes sense to me.

I know this sounds like fishing - but I've done a clinical pre-registration, and NIH wants to see this kind of data. So, the tsplot approach was the closest thing to what I wanted.

Probably I should mess with styles on pointplot and then overlay a thicker average line (basically re-implementing unit_traces).

But in any case, I've solved my problem by doing a df.reset_index() - I just wanted to make sure you were aware. It cost me maybe a couple hours to track down why I wasn't seeing what I thought I should.

**Comment by mwaskom** [comment]
Sure, I understand what you're doing, just saying that I would probably use `pointplot` for that sort of thing. In any case, I've made a note in the `tsplot` docs about the index issue. Not sure what the problem is right now, but `tsplot` needs a complete refactor anyway so I expect it will go away next time I get the chance to touch the code.
