### ISSUE TITLE
Is it possible to change the way errorbars look in factorplots

### ISSUE THREAD

**Issue by JelteF** [mwaskom/seaborn#597]
I would like for my errorbars to have a larger capsize. But I can't figure out how to do this in seaborn. 
Is this possible?

**Comment by mwaskom** [comment]
No the error bars aren't drawn with `plt.errorbar`, they're just line segments, so there aren't actually any caps to make larger. I guess if you really feel strongly about it it would be possible to get the line data and add some short line segments at the top and bottom of each, but that would be a hassle.

**Comment by JelteF** [comment]
Hmm, that's too bad. Thanks anyway. Is there any reason why it doesn't use `plt.errorbar`

**Comment by mwaskom** [comment]
A few reasons. The error bars are computed from confidence intervals rather than by calculating the standard error, so it's easier just to draw a line from [low, high]. Also at the time this code was written there was an annoying bug in `plt.errorbar` in terms of the z-order of the various elements. That may have been fixed. But I also prefer the non-capped errorbar style so have not felt urgency to go change all the places they appear :)

**Comment by mwaskom** [comment]
See #606
