### ISSUE TITLE
Weird render factorplot for legend and bars

### ISSUE THREAD

**Issue by entee** [mwaskom/seaborn#600]
Not sure why this is happening but this code:
```python
import seaborn as sns

titanic = sns.load_dataset("titanic")

g = sns.factorplot(data=titanic, x='class', y='fare', hue='pclass',
                   col='embarked', col_wrap=2, kind='bar')

sns.plt.show()
```
yields this using the current pip installed dev version:
![dev_version](https://cloud.githubusercontent.com/assets/4186164/8220944/ada1c334-150d-11e5-8b90-030c97bd6781.png)

If you fix issue # 464 in the stable release, you get this:
![stable_plus_464](https://cloud.githubusercontent.com/assets/4186164/8220955/c7330eb6-150d-11e5-80a9-3792f8f5d779.png)

In neither case is the legend actually out of the grid, but also, the dev version doesn't show the color box, and aligns the bars strangely.

**Comment by mwaskom** [comment]
There's a few issues here:

- I believe the legend inside the plot thing is the same issue as #494 and is related to a bug in the matplotlib OSX backend.
- The "bonus" axes in the lower right seems to have to do with null values in the `embarked` variable; it goes away if you pass `data=titanic.loc[titanic.embarked.notnull()]`, but this is an bug.
- I am not sure why there aren't patches in the legend, though they come back if you convert `pclass` to string, so something about using a numerical variable in `hue`; also a bug.
- I'm not sure what you mean by "align the bars strangely"; it looks right to me, unless you mean it's different from the stable version in which case it's because default rules for ordering categories have changed in 0.6 and it now uses order of appearance in the DataFrame unless specified (through an `order` kwarg or by setting the category order on the Pandas object).

**Comment by entee** [comment]
Cool, thanks for the quick response!

Your explanation on the last bullet point actually clarifies something for me. This actually stems from a set of plots I was generating where I ran across this issue. I hadn't appreciated that the hue variable controls the number of bars in each x-axis category. In the figures I'm generating that's actually not desired, I just want to use the hue variable to color the bars. This explains the behavior nicely though, thanks for the tip! :)

Also really nice package, thanks for the work!

**Comment by mwaskom** [comment]
Oh, yes, if you don't have `hue` the bars should still be colored with a palette by default, at least in the dev version. I don't remember, in the stable version it might default to the same color but you can just pass a `palette` and it should be applied across the `x` levels.

**Comment by mwaskom** [comment]
The fact that docs for the development version are online is (currently) very poorly advertised, but you can see other barplot examples (almost everything generalizes to `factorplot`) here: http://stanford.edu/~mwaskom/software/seaborn-dev/generated/seaborn.barplot.html#seaborn.barplot
