### ISSUE TITLE
How to make a scatter plot in seaborn?

### ISSUE THREAD

**Issue by zhuzelong** [mwaskom/seaborn#617]
I found it extremely hard to plot a basic scatter plot in seaborn 0.6.0.

I have two 2D datasets (continuous data), one of them has a third columns indicating labels. Now I want to plot the first dataset in scatter plot and color points based on labels. Then I want to put the second dataset in the same axes.

- `pointplot` is now dedicated to categorical data (I cannot see why) and the scatter plots generated by `pointplot` is wrong.
- `lmplot` does not support `ax` argument so I cannot put two plots in one axes
- `regplot` does support `ax` but does not support `hue`

I guess I miss something but why is it so difficult to make a basic scatter plot in seaborn 0.6.0? Could anyone give me hand? Thank you.

**Comment by mwaskom** [comment]
As noted on the [introduction](http://stanford.edu/~mwaskom/software/seaborn/introduction.html) page, there generally aren't tools in seaborn that simply duplicate what is available in matplotlib, because you can (and should) simply mix seaborn and "raw" matplotlib code. For that reason I would suggest just using `plt.scatter`.

**Comment by zhuzelong** [comment]
@mwaskom Thank you. I will turn to matplotlib for the solution.
