### ISSUE TITLE
Improve docs for categorical plotting for providing separate vectors

### ISSUE THREAD

**Issue by Phlya** [mwaskom/seaborn#620]
Hi, thanks again for a wonderful package and for a recent update.

I think an example needs to be created for categorical plotting for usage of these functions when supplying with separate vectors (e.g. lists, 1D arrays, pandas Series, etc). It's is said it can be used, but I couldn't find an example ant it took me a while of trial and error to figure it out (using data=[vector1, vector2] worked for me - is this the intended usage?). Although it is always possible to convert these things into a proper long or wide format, sometimes it just requires extra time and effort, so I think making this way to use these wonderful functions as clear as possible is also important.

But of course maybe I missed something?

**Comment by mwaskom** [comment]
Well I guess there's an example in the second plot here: http://stanford.edu/~mwaskom/software/seaborn/tutorial/categorical.html#drawing-multi-panel-categorical-plots

Though perhaps not the most obvious place.

Also the first [API example](http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.boxplot.html#seaborn.boxplot
) actually uses this format, although without a grouping variable: http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.boxplot.html#seaborn.boxplot

Plus in the parameters reference:

```
x, y, hue : names of variables in data or vector data, optional
    Inputs for plotting long-form data. See examples for interpretation.
```

**Comment by Phlya** [comment]
Sorry, it seems I wasn't quite clear... Is there an example showing how to plot 2 box-/violin-/strip-/.../plots alongside each other from 2 vectors, each vector with data for each box-/whatever-/plot? Something like this:

    x = np.random.random(100)
    y = np.random.random(100)+2
    sns.violinplot(data=[x, y])
    plt.show()

![figure_1](https://cloud.githubusercontent.com/assets/2895034/8463078/ab0d4eca-2040-11e5-851f-bda9f4d1280e.png)

**Comment by mwaskom** [comment]
Ah, ok. This is actually an error in the parameter docs. They should (and now do, with 3ae80919ec8b1a35741f8ae06e3a2cc07dcb0fac), read

```
data : DataFrame, array, or list of arrays, optional
    Dataset for plotting. If x and y are absent, this is interpreted as wide-form. Otherwise it is expected to be long-form.
```

There are a few examples of passing a wide-form DataFrame. I don't have examples for passing a list of arrays because while I didn't want to remove that option I want to deemphasize it, for two reasons:

1. I want users to primarily use Pandas objects so that the plots can have meaningful labels
2. The code to handle that case is rather complex, and somewhere down the line it would be nice to remove it (though not without warning)

In your case, I would encourage you to simply pass your arrays to a DataFrame with some useful column names to identify the two groups:

```python
sns.violinplot(data=pd.DataFrame(dict(groupa=x, groupb=y))
```

But for the foreseeable future, `sns.violiplot(data=[x, y])` will work too.

**Comment by Phlya** [comment]
I see, thanks for the clarification!
What do you think about using variable names for labelling? E.g. x and y in my example, instead of 0 and 1? This should be a fairly simple feature, but quite helpful in some cases, so one wouldn't need to construct a new dataframe or explicitly set labels just for a small plot.

**Comment by mwaskom** [comment]
That kind of thing works really well in R but is either impossible or a huge hack in Python.

**Comment by Phlya** [comment]
Yeah, I googled it now - seems like it is possible, but indeed a hack.
