### ISSUE TITLE
Should category order sort numerical variables?

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#626]
I've found myself annoyed recently drawing categorical plots where the "categorical" variable is numeric. It is tiresome to have to re-sort the DataFrame for each plot, and it doesn't make sense to turn the variables into categoricals because there are other contexts where one would want to do math on them.

For string object types, I think appearance-order is at least equally as good as sorted order, if not better, but I don't think that's true for numerical variables. So I think `seaborn.utils.category_order` should have an additional rule where numerical variables (i.e. those that can be successfully coerced to float) are sorted.

It's not clear what to do about booleans. Does [False, True] as a default make more sense than appearance order? Not sure.

cc: @wrobstory since this is his fault and @shoyer and @JanSchulz as they were involved in the original discussion to change this behavior

**Comment by wrobstory** [comment]
Since this is my fault:

I suppose I try to follow the principle of least surprise when handling these cases. Will your users be surprised or delighted when you sort numerical items in a categorical plot? I think for every user that says "Oh, neat", you will have a few users that are annoyed that the behavior changes depending on the dimension type. I think categorical API consistency should win out here. 

That being said...

One thing that matplotlib does well is defining a set of valid keyword arguments that apply to almost all API calls for a given object (say, [patches](http://matplotlib.org/api/patches_api.html)), usually for appearance defaults.

You could give `_CategoricalPlotter` a constructor with some keyword args for top-level categorical behavior preferences, say `sort_numeric=False`.  Your subclasses can accept `**kwargs` in the constructor, make things SUPER  `super(_ViolinPlotter, self).__init__(**kwargs)`, and then your actual user behavior would look like: 
```python
cat_prefs = {"sort_numeric": True}
vplot = sns.violinplot(x1, y1, **cat_prefs)
splot = sns.stripplot(x2, y2, **cat_prefs)
```

Those API calls aren't beautiful, but it does preserve consistent API behavior for categorical plots, and also allows you to define top-level categorical defaults in one place that you can apply to all categorical chart calls.

¯\_(ツ)_/¯

**Comment by mwaskom** [comment]
> I suppose I try to follow the principle of least surprise when handling these cases. Will your users be surprised or delighted when you sort numerical items in a categorical plot? I think for every user that says "Oh, neat", you will have a few users that are annoyed that the behavior changes depending on the dimension type. I think categorical API consistency should win out here.

I guess my feeling is that this box has already been opened with the fact that it treats categorical dtypes different from object dtypes, even if the values are identical. So if the principle is that categorical ordering is "smart", I think adding a rule where numerical variables are sorted is the smart thing to do.

I agree there will probably be someone out there who finds this surprising, but it's kind of hard for me to imagine situations in which one wants to put a numerical variable on the x axis of a plot but not actually have the order be numerically correct.

> One thing that matplotlib does well is defining a set of valid keyword arguments that apply to almost all API calls for a given object (say, patches), usually for appearance defaults.

I'm not sure adopting the matplotlib approach for generic kwargs would work, as the current operating principle for most seaborn functions is to take additional kwargs and pass them along to the main matplotlib function responsible for a seaborn plot.

**Comment by shoyer** [comment]
This seems like a reasonable change to me. Automatic sorting was annoying when it applied to strings and when there wasn't a categorical dtype to indicate that the column shouldn't be sorted. Strings are still often used as a sort of "implicit categorical". For other sortable types (numbers or dates), sorting would generally be a sensible thing to do.

**Comment by Phlya** [comment]
Just noticed this yesterday on my own, fully support the autosorting of numerical variables idea.

**Comment by wrobstory** [comment]
> take additional kwargs and pass them along to the main matplotlib function

Ah, yeah, then my suggestion is a Bad Idea. 

I suppose what I'm most focused on is a clear separation between nominal and ordinal categories. Maybe a single argument `ordinal=True` to be explicit about ordinality (is that a word?), in which case Things Sort. Otherwise, appearance order. 

But honestly this is me being stubborn about semantics and if you automatically sorted all numeric things there's a 99% chance you never get a user complaint.
