### ISSUE TITLE
Control Cell Size of Heatmap

### ISSUE THREAD

**Issue by weblack** [mwaskom/seaborn#658]
Is there a command that would allow you to control the size of square heatmap cells in inches? The hope is that correlation matrix plots size is scaled based on the number of variables.

If so, the original plot can be set arbitrarily large and the exported image can be clipped with a bbox after.

**Comment by mwaskom** [comment]
I'm not sure I understand what you are saying. You can't control the size of the cells, but you can control the size of the figure via normal matplotlib commands. The heatmap should not grow "arbitrarily large", I'm not sure what you're doing to see that bheavior.

**Comment by weblack** [comment]
I'll try and clear up the question...wasn't structured very well.

I was hoping that you would be able to set the size of the cells somehow (which you said you can't) so that the the size of the final figures are determined based on the number of variables (i.e., number of cells).

As for the arbitrarily large comment, it would only be true if the above was possible. If so then you would set the figure size via normal matplotlib commands to something larger then the plotted heatmap. The excess white space could then be clipped in the exporting process.

The motivation is to have correlation matrices with consistent cell size regardless of the number of variables in my papers...assuming there aren't enough that it makes it larger then the size of a page.

Outside of having control of the cell size directly, I think the only way to get close to the desired output is to calculate the figure size needed to send to matplotlib. The calculation would have to consider axis labels, titles,  and the colour bar if present.

**Comment by mwaskom** [comment]
It's not possible because heatmap is an axes-level function and by design is agnostic to the size/shape/etc. of the figure it is being plotted into. You'll have to figure out how big to make the figure as a function of the number of cells in your heatmap. As you note, that might be annoying because you'll have to account for other objects in the figure, but I would point out that would also be true for seaborn, all you can change in matplotlib is the figure size. In fact as the caller you're in a much better position to know about what else is going on in the figure and what you need to account for, the heatmap code has no idea if there are other axes in the figure, etc.

**Comment by weblack** [comment]
Makes sense, thanks for the help.

I'll write up a function that calculates the figure size to pass on to seaborn. It'll at least get the cells roughly the same size.
