### ISSUE TITLE
How to recreate corrplot

### ISSUE THREAD

**Issue by twiecki** [mwaskom/seaborn#663]
```
The `corrplot` function has been deprecated in favor of `heatmap` and will be removed in a forthcoming release. Please update your code.
  warnings.warn(("The `corrplot` function has been deprecated in favor "
```

I don't see a good way to get the same result from `heatmap()` though. It's quite nice to have the diagonal have the labels and the upper triangle to have the correlation value.

**Comment by mwaskom** [comment]
Yeah you can't get it exactly without a hack. You can have annotations and you can have a triangular heatmap. (You could do something like plot the lower triangle, then plot the upper triangle with annotations but a colormap that makes all of the cells white or some other color. But that will take a little effort).

It's something I am open to including as a parameter in `heatmap` — I was wondering how many people would ask for this. Yet I am ambivalent. While the way corrmap works is nice in theory, because it removes redundancy, I actually have found it kind of annoying in practice. It's hard to look at some part of the lower triangle (that pops out due to how we process color) and then figure out which part of the upper triangle corresponds to it. It ends up feeling like a treasure hunt. For my own visualizations these days, when I want to know the actual correlation values, I just put them in the cell using heatmap. But I could be persuaded there are virtues to the `corrplot` style.

**Comment by twiecki** [comment]
Yeah, that's a good point regarding the treasure hunt and displaying the correlation in addition to the color seems like a better approach. Yet, the missing features are the names along the diagonal which is nice, and the ** markers for significance which is also nice. For me the selling point of `seaborn` was that it's a statistical plotting package, rather than just a general purpose one, and the existence of `corrplot` certainly fits very well with that (and actually feels like a missing feature if it went away).

**Comment by mwaskom** [comment]
The diagonal names feature is another thing that sounds nice in theory but ended up being more of  pain in practice, IMO. For anything but the smallest datasets with the shortest variable names, you would end up with names that didn't fit where they wanted to go and with plots that looked crappy. And also, because the variable names were just drawn with figure texts, there was no way to change them post-hoc through normal matplotlib operations like you can when ticklabels are used for the names.

As for the significance annotations, their removal is the result of a different sort of shift in perspective. Though as you say, seaborn is a library for statistical visualization, I don't think think that should be the same thing as a library that does statistical *tests* for the user. To the extent that statistical models are used, they should be in the service of improving the visual presentation of data (i.e. a regression line). There are just too many tricky details involved in doing statistical testing that cannot feasibly be handled through the current seaborn interface. `corrplot` was sort of a border case where it seemed possible, but even there problems were arising with the permutation-based approach for computing significance, which was useful because it provides a fairly general approach for controlling for multiple comparisons but scaled poorly to large datasets. (And who knows if that's really the right/best way to do multiple comparisons correction for a particular dataset).

The final point is just a matter of principle: if you give people little stars, they aren't even going to look at the rest of the plot (sometimes). I'd think, as a Bayesian, you'd be sympathetic to my reticence to embrace NHST in the plots :)

**Comment by twiecki** [comment]
Ouch -- talk about beating someone at their own game ;). I have to say, that reasoning makes a lot of sense and like it's the right strategic decision. Probably a heatmap then with names on the axes and an easy way to center text in each cell is a solid replacement.

**Comment by mwaskom** [comment]
I should say that if there are some cells in a heatmap you want to emphasize (perhaps because they are significant, or for other resons), it's not [too hard](http://stackoverflow.com/questions/31707033/change-certain-squares-in-a-seaborn-heatmap) to do with just two function calls.

**Comment by twiecki** [comment]
Thanks!

**Comment by wel51x** [comment]
Given the lack of comments (plus the fact that this stuff is more than three years old), should I assume you're not going to move forward with including it as a parameter in heatmap?
