### ISSUE TITLE
kdeplot takes `clip` parameter but violinplot doesn't (but has `kwargs` which silently swallows it)

### ISSUE THREAD

**Issue by ianozsvald** [mwaskom/seaborn#668]
Hi Michael. First - thanks - seaborn is ace, I've been increasingly using it in the last 6 months. I'll also be demoing it on stage at the next PyDataLondon to 200+ data scientists next month.

I've found an inconsistency which left me floundering for a bit of yesterday. The KDEPlot
https://web.stanford.edu/~mwaskom/software/seaborn/generated/seaborn.kdeplot.html
can take a set of args including `clip`. Clip will remove outliers from the source data.

Behind the scenes you're using:
http://statsmodels.sourceforge.net/0.6.0/generated/statsmodels.nonparametric.kde.KDEUnivariate.html

For the violinplot you don't have a `clip` parameter but you do have `kwargs` which swallows `clip` if you provide it (I figured it used a KDE so it'd take the same param set as the other KDE plot...):
https://web.stanford.edu/~mwaskom/software/seaborn/generated/seaborn.violinplot.html

Behind the scenes you're using:
http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.gaussian_kde.html
which doesn't seem to take any sort of clip parameter so you have to filter your data before you pass it in.

I'm guessing you might aim to make both calls use `KDEUnivariate` in the future, for the time being maybe you could add a warning/exception to `violinplot` if an unexpected argument like `clip` gets passed, that'd otherwise get swallowed by the `kwargs`?

**Comment by mwaskom** [comment]
Cleaning up some old issues ...

`violinplot` still does not accept `clip` but it no longer silently swallows it. I don't think adding `clip` to `violinplot` is worth the effort. We no long use statsmodels in the backend and have to support it manually in `kdeplot`. On the other hand, the operation is very simple to support in user-space (by filtering the dataframe). It's a minor API inconsistency, but it should no longer cause extended confusing (passing it in violinplot will simply raise instead of silently having no effect).
