### ISSUE TITLE
PairGrid should pass **kwargs through to plt.subplots

### ISSUE THREAD

**Issue by richardsheridan** [mwaskom/seaborn#700]
I wanted to tighten up my pairgrid to remove dead space, and the only reasonable way I found to do that is was to hack the PairGrid __init__ to take a gridspec_kw keyword and pass that through to subplots.

It seems harmless to just collect any extra keywords with **kwargs and pass them straight to the subplots call. Or is there another way to do this that's more seabornic?

Example desired code:

    import matplotlib.pyplot as plt
    import seaborn as sns; sns.set()
    iris = sns.load_dataset("iris")
    g = sns.PairGrid(iris, gridspec_kw={'wspace':0, 'hspace':0})
    g = g.map(plt.scatter)

Desired output:

![figure_1](https://cloud.githubusercontent.com/assets/8000454/9773692/c2377e10-5711-11e5-9f0a-dcac86990838.png)

(it's a bit ugly but after massaging the spines and background it will look good)

**Comment by mwaskom** [comment]
In your case, it would be just as easy to get what you want posthoc

```
g = sns.PairGrid(iris)
g.map(plt.scatter)
g.fig.subplots_adjust(hspace=0, wspace=0)
```

It may be reasonable for `PairGrid` to have a `subplot_kws` parameter (rather than passing `**kwargs`) although the fact that it doesn't suggests there might be a reason that I am forgetting at the moment. One thing that comes to mind is that it will make reliance on `subplots` part of the public API, which might be a problem later if I get around to implementing something like "only show the lower triangle of axes".

**Comment by richardsheridan** [comment]
This works, but it doesn't play as nicely with tight_layout(). I'll
consider the issue resolved, though.

**Comment by mwaskom** [comment]
What do you mean doesn't play as nicely? PS you can also control the spacing between the axes in `tight_layout`.

**Comment by richardsheridan** [comment]
With the kwargs hack, tight_layout "just works". Otherwise, I have to call
subplots_adjust after I call tight_layout. Just a detail, but it took some
experimentation to figure it out.
