### ISSUE TITLE
Pie charts?

### ISSUE THREAD

**Issue by blindmelon** [mwaskom/seaborn#766]
Seaborn provides improved defaults for a lot of matplotlib functionality, but doesn't seem to address pie charts. As one of the most common visualisations, this seems like a massive oversight.

I'm aware that a lot of people seem to hate pie charts because they are badly used, but that doesn't mean there shouldn't be attractive defaults for using them correctly ;).

**Comment by mwaskom** [comment]
Sorry, no, seaborn will never support pie charts.

**Comment by blindmelon** [comment]
Hi @mwaskom - it's your project, so your decision. I'd really be interested in the reason, would you mind enlightening me?

**Comment by mmagnuski** [comment]
Just to spice up the discussion - a fun fact: did you know that "pies" means "dog" in polish? :smiley: 
:cake: == :dog2:

**Comment by mwaskom** [comment]
Well there you go. We already have a dog plot, so it would be redundant :)

**Comment by freekvh** [comment]
Since you don't like pie charts and you certainly aren't obligated to give any reason for that, what would you recommend as an alternative? Something like a cumulative barplot? Is that planned?

**Comment by parchd-1** [comment]
As much as I would still love to hear @mwaskom's reason for being against ever including pie charts, I'll make my suggestion to you @freekvh:
sometimes pie charts, like any other chart, are the correct tool for the job. Either because they are the only chart to tell the story you want to tell (and visualisation is all about telling a story) or they are the best option considering your audience and their expectations. If a pie chart is the right thing for what you are doing, forget about a new and exotic chart type, and just use matplotlib directly, and then add a splash of seaborn style to it to make it conform to your other plots.

**Comment by unnir** [comment]
@freekvh  try **bokeh**  https://stackoverflow.com/questions/29201177/how-do-i-create-a-pie-chart-using-bokeh
