### ISSUE TITLE
savefig as EPS does not work

### ISSUE THREAD

**Issue by MMCMA** [mwaskom/seaborn#781]
Originally I posted the question at stackoverflow (see link http://stackoverflow.com/questions/33882426/savefig-as-eps-yields-a-non-usable-eps?noredirect=1#comment55529635_33882426 ). 

I tried to save a seaborn plot in IPython as eps, it seems to work at first, but once I try to access the plot via latex or word it does not display anything. If I save the plot as png or jpg it works without problem. The problem occurs both with the command savefig() but also when I try to save the plot via an ipython figure. It always only occurs when I import seaborn, standard matplotlib eps saving works fine. (the link shows an example)

**Comment by mwaskom** [comment]
Can you please try to reduce your issue to understand what aspect is causing the problem?

**Comment by MMCMA** [comment]
Ok, the problem persits using this very basic example. As soon as I use import seaborn ( version: 0.6.0, python 3.4.3, matplotlib 1.5.0, win 8.1), the eps is not readable (by latex, word or eps viewer). As soon as I uncomment the `import seaborn as sns`  line the eps file is perfectly accessable. I hope this helps and can be replicated.
   
    import os
    import pandas as pd
    import numpy as np
    import seaborn as sns

    path = os.getcwd()
    df =  pd.DataFrame(np.random.standard_normal((100)))

    ax = df.plot()
    fig = ax.get_figure()
    fig.savefig('\\'.join([path,'rand_fig.eps']))

**Comment by mwaskom** [comment]
Not sure, sorry. When I run this code I get an .eps file that Mac preview is able to open (although it converts it to PDF which is I guess how Preview renders eps files).

BTW a good trick for writing code that is easy to copy and paste across platforms is to use `os.path.join(path_list)`, which will insert the appropriate path separator for whatever platform is running the code.

**Comment by gibbycu** [comment]
Works fine here on python 2 and 3, win 7, matplotlib 1.5, seaborn 0.6.  I used Adobe to view the eps file.

**Comment by MMCMA** [comment]
Well. I checked on another machine as well, similar set up (win 7, matplotlib 1.5, seaborn 0.6) and the same code, it works perfectly fine. After reinstalling matplotlib & seaborn it still does not work as eps on the machine where I face the problem originally. Still puzzled...

**Comment by vsb1357** [comment]
I found this page when I googled 'matplotlib savefig does not save eps', which is the problem I faced. I could save figures as png, but the same figures with a different filename were not saved as eps. More confusing was that some of eps files were saved and some not, seemingly at random. After wasting a lot of time I discovered this is because the savefig command is used in a function which is being called using Paralle from joblib library. I did not bother to investigate what is happening under the hood in joblib to cause such a problem, but thought to share this in case somebody else runs into the same issue.
