### ISSUE TITLE
confusing behavior in categorical plots

### ISSUE THREAD

**Issue by neuromusic** [mwaskom/seaborn#786]
the documentation indicates that the boxplot-inspired categorical plots (`pointplot` etc) can accept "Anything accepted by plt.boxplot (e.g. a 2d array or list of vectors)" as the input data.

However, passing in a list of vectors *which are not the same length* throws an "operands could not be broadcast together with shapes" ValueError

see https://gist.github.com/neuromusic/9f86dd5c9b7ccc3bec0c

**Comment by neuromusic** [comment]
hmm. it looks like I was misunderstanding how variables get assigned.

`sns.pointplot([x1,x2])` concatenates the two vectors in the list
`sns.pointplot(data=[x1,x2])` does what would be expected of `plt.boxplot([x1,x2])`

that said, it's not clear to me why a list of vectors assigned to `x` or `y` should be concatenated, but perhaps there is some good reason?

**Comment by mwaskom** [comment]
You can draw a categorical plot by passing a single vector to `x` or `y`, which you've done unintentionally. `pointplot` is trying to compute the mean of that vector, which means it's calling `np.mean([x1, x2])`, not knowing that the entires in the vector are themselves vectors. You can see through simple experiment that this will fail when the inner vectors are different lengths, because numpy can't make a list out of them:

`np.mean([np.arange(2), np.arange(3)])` give your error.

**Comment by neuromusic** [comment]
Got it. While I'd prefer that the behavior matched that of boxplot, perhaps it just needs some clarification in the documentation, as there is no indication that the "list of vectors" should be passed to `data` rather than `x` (the list of parameters indicates that `data` needs to be a DataFrame, whereas it's clear that vectors can be passed to x).

**Comment by mwaskom** [comment]
This was already fixed in https://github.com/mwaskom/seaborn/commit/3ae80919ec8b1a35741f8ae06e3a2cc07dcb0fac
