### ISSUE TITLE
Blue boxplot outlier issue seems to have reappeared

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#794]
Not sure why that is.

Also passing any `boxprops` forces the box lines to be blue, for some reason.

**Comment by phobson** [comment]
I might have fixed this in matplotlib already: https://github.com/matplotlib/matplotlib/pull/5526

**Comment by mwaskom** [comment]
I don't think I understand why adding rcparams would fix this, but i assume it's something to do with matplotlib magic?

**Comment by jrderuiter** [comment]
I'm also seeing blue outliers in my box plots. What is the easiest fix/work-around for the moment?

**Comment by mwaskom** [comment]
This works, although I'm not sure if it is easiest:

```
ax = sns.boxplot(x="day", y="total_bill", hue="time", data=tips)
plt.setp(ax.lines, mfc=".3")
```

Matplotlib boxplot code seems rather screwy right now :/

**Comment by mwaskom** [comment]
Also I still think this is a bug in matplotlib, but based on a little testing, seaborn could work around it by setting `markerfacecolor` instead of `color` [here](https://github.com/mwaskom/seaborn/blob/master/seaborn/categorical.py#L512).

**Comment by phobson** [comment]
This issue was that when MPL added boxplot configurations to its rcParams, they didn't fully specify everything that they should have. When some of the symbology fell back to global defaults, you got things like lines connecting the outliers. My PR was initially unrelated to that, but ended up (hopefully) fixing it nonetheless.

There were similar issues elsewhere in MPL. Things are a bit messy at the moment. But I think when the dust settles, things will be much better. 

Despite all that -- I might get bored over the holiday and write an external boxplotter that has perhaps a more functional approach (e.g., can handle before/after transformations, custom bootstrappers, etc). If (in my eyes) it ends up not sucking, I'll show it to you and it'll be yours if you want it.
