### ISSUE TITLE
wrong color when using hue with lmplot

### ISSUE THREAD

**Issue by khamael** [mwaskom/seaborn#802]
I'm using lmplot to plot a pandas dataframe, setting the hue a column, but has you can see in the screenshot, it assigns purple to 'p1', but the 3 first datapoints (with the hue column values being 'p1' are grayish. Ideas?

![screen shot 2015-12-17 at 23 45 55](https://cloud.githubusercontent.com/assets/5000837/11884207/5d34542a-a518-11e5-95ac-76b9cd135d32.png)

**Comment by amcpherson** [comment]
This also happens for a stripplot.  The reason for stripplot, likely the same for lmplot, is because seaborn internally converts to an rgb tuple, even if you provide a hex color.  If you happen to have 3 datapoints in a group, matplotlib's scatter will interpret the group specific color triple as 3 greyscale values.

I think for this reason hex should be the preferred way of inputting colors to matplotlib.

**Comment by khamael** [comment]
So can I pass a pallete like:
flatui = ["#9b59b6", "#3498db", "#95a5a6", "#e74c3c", "#34495e", "#2ecc71"]
sns.color_palette(flatui)

has the same issue with 3 items being grayscale

**Comment by amcpherson** [comment]
Yep, that likely wont work because internally seaborn is converting back to rgb triples anyway.  Note that at least for stripplot this issue is fixed in master.
