### ISSUE TITLE
Confusing lvplot results with small n

### ISSUE THREAD

**Issue by mwaskom** [mwaskom/seaborn#803]
Paging @drewokane 

My understanding is that each feature in the letter value plot should correspond to an actual observation in the dataset. However, this seems to break down for small ns:

``` python
np.random.seed(0)
x = np.random.randn(6)
sns.lvplot(x)
sns.stripplot(x)
```

![image](https://cloud.githubusercontent.com/assets/315810/11915582/92c7def0-a661-11e5-88c2-e21c949807b3.png)

Is this correct behavior?

**Comment by drewokane** [comment]
So one thought I have on this bug is that the calculation of the number of boxes breaks down for small n. The 'proportion' method for calculating the number of levels gives a result of 7 boxes for n = 6. One way of fixing this is to use one of the other methods, 'tukey' or 'trustworthy', since they will give a more reasonable answer of 1 box. I would be in favor of this. Thoughts?

**Comment by MaozGelbart** [comment]
The problem with 'proportion' approach for small n and for small `outlier_prop` p is that `np < 1` and therefore `-log2(np) > 0` and eventually boxes are added to `log2(n) + 1` boxes instead of being subtracted to allow for more outliers. Since each box covers 50% of the data from of previous level, this results in excess boxes that don't contain any observation. As a rule of thumb, in any case where `np < 1` and 'proportion' is used I propose to fallback to 'tukey' method with an appropriate warning.

**Comment by MaozGelbart** [comment]
With the default `outlier_prop=0.007` this currently affects all plots where `n<143` (which I think most example plots are and probably many use cases). This will result in most examples / tests generating warnings which is annoying. So I suggest to just remove this factor from 'proportion' k calculation if this results with boxes that do not cover real observations.

**Comment by mwaskom** [comment]
Is there a compelling reason to keep `proportion` as the default? When I skimmed the paper recently, it seemed like it was arguing that "trustworthy" was the most principled approach.

If different approaches are better in different size regimes, I think an `"auto"` default would be a good idea.
