### ISSUE TITLE
FacetGrid add_legend missing marker for pointplot

### ISSUE THREAD

**Issue by TomAugspurger** [mwaskom/seaborn#822]
```python
In [23]: df = pd.DataFrame({'A': [1, 1, 2, 2], 'B': [1, 3, 2, 4], 'C': [True, False, True, False]})

In [24]: g = sns.FacetGrid(df, hue='C')

In [25]: g.map(sns.pointplot, 'A', 'B')
Out[25]: <seaborn.axisgrid.FacetGrid at 0x11a3628d0>

In [26]: g.add_legend()
Out[26]: <seaborn.axisgrid.FacetGrid at 0x11a3628d0>
```
![legend](https://cloud.githubusercontent.com/assets/1312546/12363259/6848e912-bb8d-11e5-831c-344160c1a847.png)

It does seem to add the marker for e.g. scatter, so maybe it's confused about what the marker type should be for `pointplot`

No time to look right now, maybe this weekend.

**Comment by TomAugspurger** [comment]
Another hint, the legend does work when hue is passed to the map,

```python
In [23]: df = pd.DataFrame({'A': [1, 1, 2, 2], 'B': [1, 3, 2, 4], 'C': [True, False, True, False]})

In [24]: g = sns.FacetGrid(df)

In [25]: g.map(sns.pointplot, 'A', 'B', 'C)
```

**Comment by mwaskom** [comment]
It's "expected" in the sense that pointplot doesn't do anything with the `label` kwarg if there's no `hue` variable.

This is generally true of the categorical plots I think. The reason is that for most of the plots, the `hue` variable also determines position on the categorical axis, which `FacetGrid` can't do anything about, and so the right usage is to delegate `hue` conditioning to the function call, not to the `FacetGrid`.

Actually, the *right* usage is to use `factorplot`; otherwise the combination of default category order rules and "dumb" ticklabeling by `FacetGrid` can lead to incorrect plots if the user isn't careful to set category orders on the variables or use the `order` keywords.

**Comment by TomAugspurger** [comment]
That works for me,  I'm not sure why I wasn't using factorplot here.
