### ISSUE TITLE
Annotations do not appear when xticklabels or yticklabels are False in heatmaps

### ISSUE THREAD

**Issue by BrianLandry** [mwaskom/seaborn#837]
In heatmaps when either xticklabels or yticklabels are false annotations do not appear on the heatmap.

```
import numpy as np; np.random.seed(0)
import seaborn as sns; sns.set()
uniform_data = np.random.rand(10, 12)
ax = sns.heatmap(uniform_data, annot = True)
```

![image](https://cloud.githubusercontent.com/assets/2424677/12568638/07c136c8-c38d-11e5-9bd4-a5dc0aef0557.png)

```
ax = sns.heatmap(uniform_data, annot = True, xticklabels = False)
```

![image](https://cloud.githubusercontent.com/assets/2424677/12568640/0c65d4cc-c38d-11e5-8b70-e9655591130a.png)

This bug is present in 0.7.0 but is not in 0.6.0

**Comment by mwaskom** [comment]
Interesting. I reckon it was caused by #831. ATTN @gkunter; any thoughts?

**Comment by gkunter** [comment]
I've had a look at the issue. It doesn't seem to have been introduced by #831 – disabling the call to ```update_scalarmappable()``` doesn't improve the second heatmap. The offending line from ```_HeatMapper._annotate_heatmap()``` that causes the bug is one:
```python
        xpos, ypos = np.meshgrid(ax.get_xticks(), ax.get_yticks())

```
What is happening when the tick labels are disabled for the x axis is that ```ax.get_ticks()``` returns an empty list,  which in turn causes ```np.meshgrid()``` also to return only a tuple of two empty lists.

**Comment by mwaskom** [comment]
Thanks for looking into it, I guess it's been around for a little while but nobody noticed (makes sense I guess, it's rare that you'd have enough space for annotations but not for labels).

Solution is probably to save the ticklabel locations immediately after plotting and before futzing with the labels.

**Comment by compi1234** [comment]
This problem comes up naturally when you want to incorporate multiple heatmaps in a single figure with subplots where you want to share X and/or Y labels.
There are actually more things that seem to break in seaborn when you do that, such as the behavior of the ytickmarks that I don't manage to control in part of the figure
here's a snippet of code (in the left heatmap the rotation of the yticks does not work - in the right one it does:
# now plot it all
f,( ax_t, ax_o ) = plt.subplots(1,2,figsize=(12,5), \
                       gridspec_kw={"width_ratios":[nstates+1,nlabels]})

ax_t.set_title("INIT and TRANSITION PROBS",weight='bold')
sns.heatmap(itmat,ax=ax_t,xticklabels=itlabels,yticklabels=states,\
            square=True,cmap='cool',linewidths=.1,vmin=0.0,vmax=1.0, \
            annot=True,fmt=".3f",annot_kws={'color':'black','fontsize':14})
plt.yticks(rotation='horizontal')

ax_o.set_title("OBSERVATION PROBS",weight='bold')
sns.heatmap(omat,ax=ax_o,xticklabels=labels,yticklabels=states,\
            square=True,cmap='cool',linewidths=.1,vmin=0.0,vmax=1.0, \
            annot=True,fmt=".3f",annot_kws={'color':'black','fontsize':14})
plt.yticks(rotation='horizontal')

plt.show()

**Comment by mwaskom** [comment]
Your problem there is that `plt.yticks` operates on the currently active axes, which doesn't change over the course of your code.

**Comment by jleinonen** [comment]
The easy workaround is to set ``xticklabels`` and/or ``yticklabels`` to a list of empty strings.

**Comment by originalberto** [comment]
I'm using Seaborn '0.7.1' and the problem is still not fixed, if I set either xticklabels or yticklabels to False, the annotations do not appear in the heatmap

**Comment by mmagnuski** [comment]
@originalberto 
Can you update to 0.8.1 and see if it works for you?

**Comment by iaciac** [comment]
Hi! Just encountered this problem. Apparently it hasn't been fixed yet

**Comment by mmagnuski** [comment]
@iaciac
Which seaborn version are you using?

**Comment by originalberto** [comment]
@mmagnuski apologies for the delay. After updating to Seaborn 0.8.1 the problem seems to be fixed.
Thank you!
