### ISSUE TITLE
Stripplot argument in barplot and boxplot

### ISSUE THREAD

**Issue by rchurt** [mwaskom/seaborn#853]
Since it's such a common task, it would be helpful to have a "stripplot=True" argument in the barplot and boxplot commands that would automatically overlay the data points used to make the bar/boxplots onto the plots themselves. A "swarmplot=True" argument would be great as well.

[open_field_distance_traveled_barplot.pdf](https://github.com/mwaskom/seaborn/files/120379/open_field_distance_traveled_barplot.pdf)

**Comment by mwaskom** [comment]
I agree that would be nice, but then how do you pass all of the options for configuring the strips/swarms? Better to just call two functions.

**Comment by rchurt** [comment]
I was picturing the simple case of just wanting dots of the same color as the bars with gray edges, which I assume would be the most common usage. But you're right, anyone who wanted to customize the dots would be free to call each plotting command separately.

**Comment by arahuja** [comment]
I actually came here to open a similar issue, but I see the argument against it. While we use the above solution to generate the plots now (two overlayed) I was going to ask if it's possible to add this into the `factorplot` since it useful to see the median along with the strip plot. Would it possible to add a median line to the strip plot? (Happy to contribute as well)
