### ISSUE TITLE
Consider not clipping the plotted lines

### ISSUE THREAD

**Issue by Phyks** [mwaskom/seaborn#875]
Hi,

When using seaborn theme to plot some functions, sometimes the resulting graph is cropped. Actually, seaborn is affected by the point raised in https://github.com/matplotlib/matplotlib/issues/6084.

A [solution](https://github.com/matplotlib/matplotlib/issues/6084#issuecomment-190783738) is to unclip the plotted lines, so that they are not truncated.

I did not find any way to set it globally, but I guess it could go in the `rcParams` or something equivalent. Is there any specific reasons for not doing it in `seaborn.set()`?

Thanks

**Comment by mwaskom** [comment]
A quick grep of the rcparams file suggests that this is not something that is configured in matplotlib through that mechanism, so it's not possible for seaborn to set default behavior.

Additionally, it's not clear to me that turning clipping off by default is the better option (since in most cases, some spines exist, and lines will be plotted on top of them in a way that will look equally if not more weird than the case where the line gets clipped when the axes invisibly "ends".)

**Comment by Phyks** [comment]
Ok for not being able to set the default behavior.

@mwaskom, I think I missed your second point about clipping off by default not being the better option. Why would it be weird if spines exist?
