### ISSUE TITLE
Refactoring tsplot?

### ISSUE THREAD

**Issue by caichinger** [mwaskom/seaborn#896]
By means of this issue I want to promote PR #814 which is about refactoring `tsplot` to allow future developments. Please see the PR's description for further information.
Questions regarding additional features for `tsplot` pop up regularly and I would like to help. 

It would be great if someone could take a look and provide feedback.

Thank you!

**Comment by mwaskom** [comment]
Sorry, but I'm just not going to be able to give your PR any real considering in the near future, as I'm working on my Phd dissertation.

Given that tsplot isn't that well integrated with the rest of seaborn anyway, I'd probably encourage you or others who are interested in enhanced timeseries plotting to develop it as a standalone library dependent on matplotlib.

**Comment by caichinger** [comment]
I perfectly understand that you are very busy.
Thank you for the quick response and the effort that you have put into this great project!

All the best for your dissertation!

**Comment by mmagnuski** [comment]
@caichinger Have you changed your tsplot refactor into a separate repo? I'd be interested. :)

**Comment by caichinger** [comment]
@mmagnuski No I have not but maybe we can give it a try ;)
However, I must admit that I have for some time not taken a look into this topic and I am at the moment very busy.
I will send you a mail to avoid spamming this issue.

**Comment by mwaskom** [comment]
There's also a related issue at the matplotlib repo: https://github.com/matplotlib/matplotlib/issues/8184

I think it would be great to have an errorband function in matplotlib itself that will take care of the "basic" usecase for `tsplot`.

**Comment by caichinger** [comment]
Thanks for pointing that out, I was not aware of this issue. Will take a look.

**Comment by beojan** [comment]
@caichinger That's because it's new. Ideally (for me, at least), the `tsplot` error band plotting code could be included in matplotlib.

**Comment by pwaller** [comment]
I just spent a non-negligable amount of time squinting at the docs for tsplot trying to figure out how to feed my own error in rather than having it calculate one via bootstrapping. It is surprising that you cannot!

**Comment by mwaskom** [comment]
Sounds like an inefficient allocation of your time, @pwaller, because if you already have the error values it's trivial to make the plot using matplotlib directly...

**Comment by pwaller** [comment]
That may well be! Aren't we all granted a bit of inefficient time allocation in our lives? :)

[![image](https://cloud.githubusercontent.com/assets/438648/24918281/c969794c-1ed7-11e7-890f-2c6435704b07.png)](http://seaborn.pydata.org/examples/timeseries_from_dataframe.html)

However, you might be interested to know that I arrived at that place trying to make plots consistently using the lovely seaborn API, seeing what I wanted in [the seaborn visual gallery](http://seaborn.pydata.org/examples/index.html) (which is easy to skim with just 36 plots) and thinking "aha, I'm done, now I just need to feed in the error... wait, is one of these parameters the error? Or can it be made to do take an error? Wait, where does it even get its existing error?"

"Trivial to make the plot using matplotlib directly" - well, the [gallery for matplotlib](http://matplotlib.org/gallery.html) is much bigger (fwiw, I count 488 `<img>` tags), and none of them look like the pretty thing you have in your gallery) and the examples are not one-liners as with sns. As far as I can tell, I have to do some incantation with `fill_between` which requires doing additional computation to make the error-bands. I will give one 🍪 to someone who can find a matplotlib function which can produce a plot as pretty as the seaborn one above with a one-liner.

Yes, these things are all doable, but not as easy as is typical with seaborn.

Seaborn facilitates a few obvious usecases for plotting data really well. Drawing error bands as shown in the above timeseries plot  — which happen to not be time-series — are surely one of them, especially since it is a superset of "error bands on time series".

Sorry for the diatribe. It's with ❤️. Hope that's OK.
