### ISSUE TITLE
Standard deviation in barplots [question/feature request]

### ISSUE THREAD

**Issue by ChuckDaniels87** [mwaskom/seaborn#926]
Could it be possible to represent __standard deviation bars__ instead __standard error bars__ in barplots?

I don't know if it is already possible tweaking _ci_ and _estimator_. If this feature is not too complex to implement in Seaborn, I could help to develop it as much as I can.

_Note: I was going to ask this in StackOverflow but I found this [unanswered question](http://stackoverflow.com/questions/36067194/how-to-show-error-bar-with-standard-deviation-in-a-barplot-using-seaborn-in-pyth)_

**Comment by mwaskom** [comment]
No, it's not possible, sorry.

**Comment by ChuckDaniels87** [comment]
Thanks for answering that quick anyways. You're doing a great job with this library. :+1:

**Comment by jadolfbr** [comment]
I don't see how this is not possible the way the code is written now.  What makes it impossible? Instead of bootstrapping to append confint, we could could calculate confint.  I think the only issue is with the interface to the function where ci is a float.  There could be another variable, draw_stddev, that would be a boolean, default False.  If this were to be passed true, the standard deviations could be drawn instead of the confidence intervals...

**Comment by ChuckDaniels87** [comment]
@jadolfbr Could create a patch/PR with that approach? I could try to help if it is needed.

**Comment by jadolfbr** [comment]
@ChuckDaniels87 Sounds good. Will do!
