### ISSUE TITLE
Seaborn doesn't support PeriodIndex

### ISSUE THREAD

**Issue by jeanodoux** [mwaskom/seaborn#936]
Seaborn doesn't properly support pandas PeriodIndex: dates should be converted to their actual values before being plotted.

```
import pandas as pd #Pandas 0.18.1
import seaborn as sns #Seaborn 0.7.0
index = pd.PeriodIndex(start='2000', end='2005', freq='A')
df = pd.DataFrame(np.random.randint(0,10,(len(index), 2)), index=index, columns=['A', 'B'])
sns.heatmap(df)
```

![download](https://cloud.githubusercontent.com/assets/13455369/15648246/7c65b0e6-2669-11e6-9d31-ec8d57ee2017.png)

I'm not familiar with PRs, I guess there's not much to change as converting the PeriodIndex to a regular datetime type does the trick
`sns.heatmap(df.pipe(lambda x: x.set_index(x.index.to_datetime())))`

**Comment by mwaskom** [comment]
You could do `sns.heatmap(df, yticklabels=index.to_datetime().tolist())`.

**Comment by mwaskom** [comment]
Closing because I don't think this special case is worth the clutter.

**Comment by davidgilbertson** [comment]
For most time series data I work with I use the Pandas `Period` instead of `TimeStamp`, so out of the box something like this fails: `sns.lineplot(data=df, x="Date", y="Price")` (where my index has the name `Date`).

My workaround is `sns.lineplot(data=df, x=df.index.to_timestamp(), y="Price")` but that seems pretty clunky. I wouldn't have thought using the `Period` type for time series data is considered a special case, perhaps things have changed since 2017?

Or maybe this is a problem with Pandas' `pd.to_numeric()` not handling a series with dtype `Period`?

**Comment by mwaskom** [comment]
Unlike `heatmap`, `lineplot` delegates all unit handling to matplotlib and should be able to plot datatype that has a unit converter in the relevant matplotlib registry.

If you do

```python
pd.plotting.register_matplotlib_converters()
mpl.units.registry

**Comment by davidgilbertson** [comment]
Thanks for the detailed reply! This works for me:
```py
pd.plotting.register_matplotlib_converters()
ax.xaxis.freq = df.index.freq  # or use decorate_axes() from pandas
sns.lineplot(data=df, x="Date", y="AdjClose")
```
![image](https://user-images.githubusercontent.com/4443482/174916812-c076d2ff-24c2-49b6-9a75-559e6f1bb719.png)

That seems a bit brittle/fussy though.

I might log an issue with Pandas, but I suspect they won't really be interested in fixing this either.

I think I'll switch to good ol' timestamp indexes.

**Comment by mwaskom** [comment]
Weird, what version of pandas / matplotlib are you on?

Agreed that this is really something that should be made to work better in pandas.

**Comment by davidgilbertson** [comment]
pandas: `1.4.2`
matplotlib: `3.5.2`
Python: `3.10.2`

BTW Seaborn is great. Good docs too, things are nicely explained.
