### ISSUE TITLE
FacetGrid.despine(offset=10) , brings the ticklabels back

### ISSUE THREAD

**Issue by dasdebapriya** [mwaskom/seaborn#946]
Hello,

I am new to Seaborn and facing a problem using the despine function. Here is the code snippet I am using,

tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col = 'time')
g = g.map(plt.hist, "tip")
which gives the output of Image 1
![image_1](https://cloud.githubusercontent.com/assets/19952866/16081015/e6ab572c-330b-11e6-9d9a-f63a84c13ed2.png)

But when I insert the line 
g.despine(offset=10) in the existing code such that
tips = sns.load_dataset("tips")
g = sns.FacetGrid(tips, col = 'time')
g.despine(offset=10)
g = g.map(plt.hist, "tip")

the output changes by bringing back the xticklabels. The image is here.
![image_2](https://cloud.githubusercontent.com/assets/19952866/16081074/25640f86-330c-11e6-92fc-3a6844242aca.png)

How can I get rid off the xticklabels and yticklabels keeping the despine offset on. I have tchecked the problem exists in the matplotlib as well.

Thanks.

**Comment by mwaskom** [comment]
So this happens because matplotlib calls `axis.reset_ticks()` internally when moving the spine. Otherwise, the spine gets moved but the ticks stay in the same place. It's not configurable in matplotlib and, even if it were, I don't know if there is a public API for moving individual ticks. Unfortunately I think you'll have to remove the tick labels yourself after offsetting the spines.
